// GENERATED by shell/gen_panel_map.py -- do not edit by hand.
// Sources: hardware/reva/panel-map.json, hardware/reva/blocks.py,
// control/params.hpp; the RESERVED list lives in the generator.
// Spec: docs/superpowers/specs/2026-10-02-rev-a-p6a-panel-scan-design.md,
// classification: 2026-10-09-rev-a-p6b1-shared-control-law-design.md 4.2
#pragma once
#include "controls.h"
#include "keys.h"
#include "mux_plan.h"

namespace shell {

// P2 sections 3 and 4: 10 74HC4051 on 4 sense pins, one mux per sense pin
// per step; a 40-bit 595 chain -- address 0-2, enables 3-12, LEDs 13-27.
inline constexpr ChainProfile kRevaChain{
    4, kSenseAdcBase, 10,
    {8, 8, 8, 8, 8, 8, 8, 8, 8, 8},
    {0, 0, 0, 1, 1, 1, 2, 2, 3, 3},
    40, 0, 3, 13, 15, -1, 3, true};

// One row per pot in (mux, channel) order; SHELL_PLAY_V prints the values
// in this order. param -1: scanned and reported, sent nowhere (spec 2.3);
// every other row writes its control-law knob (P6b-1 spec 4.2).
inline constexpr ControlEntry kRevaControls[] = {
    {0, 0, ffctl::ENGINE_A, 0},  // row 0 ENGINE_A -- ENGINE_A
    {0, 1, ffctl::STEPS_A, 0},  // row 1 STEPS_A -- STEPS_A
    {0, 2, ffctl::SONG_A, 0},  // row 2 SONG_A -- SONG_A
    {0, 3, ffctl::RATE_A, 0},  // row 3 RATE_A -- RATE_A
    {0, 4, ffctl::MOD_A, 0},  // row 4 MOD_A -- MOD_A
    {0, 5, ffctl::SHAPE_A, 0},  // row 5 SHAPE_A -- SHAPE_A
    {0, 6, ffctl::DENSITY_A, 0},  // row 6 DENSITY_A -- DENSITY_A
    {0, 7, ffctl::SOURCE_A, 0},  // row 7 SOURCE_A -- SOURCE_A
    {1, 0, ffctl::SMOOTH_A, 0},  // row 8 SMOOTH_A -- SMOOTH_A
    {1, 1, ffctl::RANGE_A, 0},  // row 9 RANGE_A -- RANGE_A
    {1, 2, ffctl::ATTACK_A, 0},  // row 10 ATTACK_A -- ATTACK_A
    {1, 3, ffctl::DECAY_A, 0},  // row 11 DECAY_A -- DECAY_A
    {2, 0, ffctl::COLOR_A, 0},  // row 12 COLOR_A -- COLOR_A
    {2, 1, ffctl::TUNE_A, 0},  // row 13 TUNE_A -- TUNE_A
    {2, 2, ffctl::FLUX_A, 0},  // row 14 FLUX_A -- FLUX_A
    {2, 3, ffctl::FLUXRATE_A, 0},  // row 15 FLUXRATE_A -- FLUXRATE_A
    {2, 4, -1, 0},  // row 16 ROOT_A -- reserved: per-deck scale root, follow-up to spec 2026-10-07 section 4
    {2, 5, ffctl::DETUNE_A, 0},  // row 17 DETUNE_A -- DETUNE_A
    {2, 6, ffctl::FLUXFB_A, 0},  // row 18 FLUXFB_A -- FLUXFB_A
    {2, 7, ffctl::LINK_A, 0},  // row 19 LINK_A -- LINK_A
    {3, 0, ffctl::SONG_B, 1},  // row 20 SONG_B -- SONG_B
    {3, 1, ffctl::STEPS_B, 1},  // row 21 STEPS_B -- STEPS_B
    {3, 2, ffctl::ENGINE_B, 1},  // row 22 ENGINE_B -- ENGINE_B
    {3, 3, ffctl::SHAPE_B, 1},  // row 23 SHAPE_B -- SHAPE_B
    {3, 4, ffctl::MOD_B, 1},  // row 24 MOD_B -- MOD_B
    {3, 5, ffctl::RANGE_B, 1},  // row 25 RANGE_B -- RANGE_B
    {3, 6, ffctl::SMOOTH_B, 1},  // row 26 SMOOTH_B -- SMOOTH_B
    {3, 7, ffctl::COLOR_B, 1},  // row 27 COLOR_B -- COLOR_B
    {4, 0, ffctl::RATE_B, 1},  // row 28 RATE_B -- RATE_B
    {4, 1, ffctl::FILT_B, 1},  // row 29 FILT_B -- FILT_B
    {4, 2, ffctl::SOURCE_B, 1},  // row 30 SOURCE_B -- SOURCE_B
    {4, 3, ffctl::DENSITY_B, 1},  // row 31 DENSITY_B -- DENSITY_B
    {4, 4, ffctl::RES_B, 1},  // row 32 RES_B -- RES_B
    {4, 5, ffctl::DECAY_B, 1},  // row 33 DECAY_B -- DECAY_B
    {4, 6, ffctl::ATTACK_B, 1},  // row 34 ATTACK_B -- ATTACK_B
    {4, 7, ffctl::COMP_B, 1},  // row 35 COMP_B -- COMP_B
    {5, 0, ffctl::FLUXRATE_B, 1},  // row 36 FLUXRATE_B -- FLUXRATE_B
    {5, 1, ffctl::FLUX_B, 1},  // row 37 FLUX_B -- FLUX_B
    {5, 2, ffctl::TUNE_B, 1},  // row 38 TUNE_B -- TUNE_B
    {5, 3, ffctl::GRIT_B, 1},  // row 39 GRIT_B -- GRIT_B
    {5, 4, ffctl::LINK_B, 1},  // row 40 LINK_B -- LINK_B
    {5, 5, ffctl::FLUXFB_B, 1},  // row 41 FLUXFB_B -- FLUXFB_B
    {5, 6, ffctl::DETUNE_B, 1},  // row 42 DETUNE_B -- DETUNE_B
    {5, 7, -1, 1},  // row 43 ROOT_B -- reserved: per-deck scale root, follow-up to spec 2026-10-07 section 4
    {6, 0, ffctl::MELODY_A, 2},  // row 44 MELODY_A -- MELODY_A
    {6, 1, ffctl::SCALE, 2},  // row 45 SCALE -- SCALE
    {6, 2, ffctl::FILT_A, 2},  // row 46 FILT_A -- FILT_A
    {6, 3, ffctl::DEPTH_A, 2},  // row 47 DEPTH_A -- DEPTH_A
    {6, 4, ffctl::TIDE, 2},  // row 48 TIDE -- TIDE
    {6, 5, ffctl::RES_A, 2},  // row 49 RES_A -- RES_A
    {6, 6, ffctl::TEMPO, 2},  // row 50 TEMPO -- TEMPO
    {7, 0, ffctl::SUB_A, 2},  // row 51 SUB_A -- SUB_A
    {7, 1, ffctl::COMP_A, 2},  // row 52 COMP_A -- COMP_A
    {7, 2, ffctl::PAN_A, 2},  // row 53 PAN_A -- PAN_A
    {7, 3, ffctl::COUPLE, 2},  // row 54 COUPLE -- COUPLE
    {7, 4, ffctl::GRIT_A, 2},  // row 55 GRIT_A -- GRIT_A
    {7, 5, ffctl::REV_MIX_A, 2},  // row 56 REV_MIX_A -- REV_MIX_A
    {7, 6, ffctl::REV_DIFF, 2},  // row 57 REV_DIFF -- REV_DIFF
    {8, 0, ffctl::CHOKE, 3},  // row 58 CHOKE -- CHOKE
    {8, 1, ffctl::PULL, 3},  // row 59 PULL -- PULL
    {8, 2, ffctl::MELODY_B, 3},  // row 60 MELODY_B -- MELODY_B
    {8, 3, ffctl::MORPH, 3},  // row 61 MORPH -- MORPH
    {8, 4, ffctl::PACE, 3},  // row 62 PACE -- PACE
    {8, 5, ffctl::DEPTH_B, 3},  // row 63 DEPTH_B -- DEPTH_B
    {8, 6, ffctl::SUB_B, 3},  // row 64 SUB_B -- SUB_B
    {9, 0, ffctl::REV_SIZE, 3},  // row 65 REV_SIZE -- REV_SIZE
    {9, 1, ffctl::SHUFFLE, 3},  // row 66 SHUFFLE -- SHUFFLE
    {9, 2, ffctl::REV_DECAY, 3},  // row 67 REV_DECAY -- REV_DECAY
    {9, 3, ffctl::DRIFT, 3},  // row 68 DRIFT -- DRIFT
    {9, 4, ffctl::PAN_B, 3},  // row 69 PAN_B -- PAN_B
    {9, 5, ffctl::REV_TONE, 3},  // row 70 REV_TONE -- REV_TONE
    {9, 6, -1, 3},  // row 71 REV_MOD -- reserved: reverb tail wobble (WOBL), follow-up to spec 2026-10-07 section 4
    {9, 7, ffctl::REV_MIX_B, 3},  // row 72 REV_MIX_B -- REV_MIX_B
};
inline constexpr ControlTable kRevaTable{
    kRevaControls,
    static_cast<int>(sizeof(kRevaControls) / sizeof(kRevaControls[0]))};

// The calibration channels (P2 section 3): the panel reads its own span.
inline constexpr MuxChannel kRevaCalZero{1, 4};  // CAL_GND
inline constexpr MuxChannel kRevaCalRail{1, 5};  // CAL_3V3

// REC_A, REC_B, MODBTN, SHIFTBTN on the 165's D0..D3; the first bit shifted out is D7.
inline constexpr KeyPad kRevaKeys{4, {7, 6, 5, 4}};

} // namespace shell
