// GENERATED by shell/gen_panel_map.py -- do not edit by hand.
// Sources: hardware/reva/panel-map.json, hardware/reva/blocks.py,
// engine/param_table.h; the SAFE/UNMAPPED/RESERVED lists live in the generator.
// Spec: docs/superpowers/specs/2026-10-02-rev-a-p6a-panel-scan-design.md
#pragma once
#include "controls.h"
#include "keys.h"
#include "mux_plan.h"

namespace shell {

// P2 sections 3 and 4: 10 74HC4051 on 4 sense pins, one mux per sense pin
// per step; a 40-bit 595 chain -- address 0-2, enables 3-12, LEDs 13-27.
inline constexpr ChainProfile kRevaChain{
    4, kSenseAdcBase, 10,
    {8, 8, 8, 8, 8, 8, 8, 8, 8, 8},
    {0, 0, 0, 1, 1, 1, 2, 2, 3, 3},
    40, 0, 3, 13, 15, -1, 3, true};

// One row per pot in (mux, channel) order; SHELL_PLAY_V prints the values
// in this order. param -1: scanned and reported, sent nowhere (spec 2.3).
inline constexpr ControlEntry kRevaControls[] = {
    {0, 0, -1, 0},  // row 0 ENGINE_A -- unmapped: UI remap, Fireflow.cpp:906-914
    {0, 1, -1, 0},  // row 1 STEPS_A -- unmapped: 0 = STEP off, per-deck set_step, Fireflow.cpp:1149-1150
    {0, 2, -1, 0},  // row 2 SONG_A -- unmapped: 14-rung ladder, Fireflow.cpp:1163-1175
    {0, 3, spky::P_RATE_A, 0},  // row 3 RATE_A -- safe: set_rate(mvp), Fireflow.cpp:783
    {0, 4, spky::P_DEPTH_A, 0},  // row 4 MOD_A -- safe: set_depth(pp(MOD)), Fireflow.cpp:790; apply_param(P_DEPTH) calls set_depth
    {0, 5, spky::P_SHAPE_A, 0},  // row 5 SHAPE_A -- safe: set_shape(mvp), Fireflow.cpp:784
    {0, 6, -1, 0},  // row 6 DENSITY_A -- unmapped: also drives sampler_overlap, Fireflow.cpp:993
    {0, 7, -1, 0},  // row 7 SOURCE_A -- unmapped: no ParamId; LANE_SOURCE base, Fireflow.cpp:994
    {1, 0, spky::P_SMOOTH_A, 0},  // row 8 SMOOTH_A -- safe: set_smooth(mvp), Fireflow.cpp:786
    {1, 1, spky::P_RANGE_A, 0},  // row 9 RANGE_A -- safe: set_range(mvp), Fireflow.cpp:787
    {1, 2, -1, 0},  // row 10 ATTACK_A -- unmapped: one pot with STAGES; the BBD re-points it, Fireflow.cpp:1022
    {1, 3, spky::P_DECAY_A, 0},  // row 11 DECAY_A -- safe: set_voice_decay(mvp), Fireflow.cpp:794
    {2, 0, spky::P_COLOR_A, 0},  // row 12 COLOR_A -- safe: set_color(mv), Fireflow.cpp:799
    {2, 1, spky::P_TUNE_A, 0},  // row 13 TUNE_A -- safe: set_tune(mvp), Fireflow.cpp:791
    {2, 2, -1, 0},  // row 14 FLUX_A -- unmapped: also switches the FX block on, Fireflow.cpp:840
    {2, 3, -1, 0},  // row 15 FLUXRATE_A -- unmapped: no ParamId; detented index, Fireflow.cpp:822-823
    {2, 4, -1, 0},  // row 16 ROOT_A -- reserved: per-deck scale root, follow-up to spec 2026-10-07 section 4
    {2, 5, -1, 0},  // row 17 DETUNE_A -- unmapped: squared; SPREAD on FEED, Fireflow.cpp:812-819, 1097
    {2, 6, -1, 0},  // row 18 FLUXFB_A -- unmapped: no ParamId; FX target base, Fireflow.cpp:824-825
    {2, 7, spky::P_LINK_A, 0},  // row 19 LINK_A -- safe: set_link(mv), Fireflow.cpp:832
    {3, 0, -1, 1},  // row 20 SONG_B -- unmapped: 14-rung ladder, Fireflow.cpp:1163-1175
    {3, 1, -1, 1},  // row 21 STEPS_B -- unmapped: 0 = STEP off, per-deck set_step, Fireflow.cpp:1149-1150
    {3, 2, -1, 1},  // row 22 ENGINE_B -- unmapped: UI remap, Fireflow.cpp:906-914
    {3, 3, spky::P_SHAPE_B, 1},  // row 23 SHAPE_B -- safe: set_shape(mvp), Fireflow.cpp:784
    {3, 4, spky::P_DEPTH_B, 1},  // row 24 MOD_B -- safe: set_depth(pp(MOD)), Fireflow.cpp:790; apply_param(P_DEPTH) calls set_depth
    {3, 5, spky::P_RANGE_B, 1},  // row 25 RANGE_B -- safe: set_range(mvp), Fireflow.cpp:787
    {3, 6, spky::P_SMOOTH_B, 1},  // row 26 SMOOTH_B -- safe: set_smooth(mvp), Fireflow.cpp:786
    {3, 7, spky::P_COLOR_B, 1},  // row 27 COLOR_B -- safe: set_color(mv), Fireflow.cpp:799
    {4, 0, spky::P_RATE_B, 1},  // row 28 RATE_B -- safe: set_rate(mvp), Fireflow.cpp:783
    {4, 1, spky::P_FILT_B, 1},  // row 29 FILT_B -- safe: set_voice_filt(raw), Fireflow.cpp:798
    {4, 2, -1, 1},  // row 30 SOURCE_B -- unmapped: no ParamId; LANE_SOURCE base, Fireflow.cpp:994
    {4, 3, -1, 1},  // row 31 DENSITY_B -- unmapped: also drives sampler_overlap, Fireflow.cpp:993
    {4, 4, -1, 1},  // row 32 RES_B -- unmapped: VCV knob 0..1 (Fireflow.cpp:479), table 0..0.75
    {4, 5, spky::P_DECAY_B, 1},  // row 33 DECAY_B -- safe: set_voice_decay(mvp), Fireflow.cpp:794
    {4, 6, -1, 1},  // row 34 ATTACK_B -- unmapped: one pot with STAGES; the BBD re-points it, Fireflow.cpp:1022
    {4, 7, -1, 1},  // row 35 COMP_B -- unmapped: level/compressor split with a curve, Fireflow.cpp:872-883
    {5, 0, -1, 1},  // row 36 FLUXRATE_B -- unmapped: no ParamId; detented index, Fireflow.cpp:822-823
    {5, 1, -1, 1},  // row 37 FLUX_B -- unmapped: also switches the FX block on, Fireflow.cpp:840
    {5, 2, spky::P_TUNE_B, 1},  // row 38 TUNE_B -- safe: set_tune(mvp), Fireflow.cpp:791
    {5, 3, -1, 1},  // row 39 GRIT_B -- unmapped: bipolar with a dead zone and a mode, Fireflow.cpp:1143-1148
    {5, 4, spky::P_LINK_B, 1},  // row 40 LINK_B -- safe: set_link(mv), Fireflow.cpp:832
    {5, 5, -1, 1},  // row 41 FLUXFB_B -- unmapped: no ParamId; FX target base, Fireflow.cpp:824-825
    {5, 6, -1, 1},  // row 42 DETUNE_B -- unmapped: squared; SPREAD on FEED, Fireflow.cpp:812-819, 1097
    {5, 7, -1, 1},  // row 43 ROOT_B -- reserved: per-deck scale root, follow-up to spec 2026-10-07 section 4
    {6, 0, -1, 2},  // row 44 MELODY_A -- unmapped: SCAN on the sampler, Fireflow.cpp:1082-1083
    {6, 1, spky::P_SCALE, 2},  // row 45 SCALE -- safe: set_scale(round), Fireflow.cpp:1253; 13 steps both sides
    {6, 2, spky::P_FILT_A, 2},  // row 46 FILT_A -- safe: set_voice_filt(raw), Fireflow.cpp:798
    {6, 3, -1, 2},  // row 47 DEPTH_A -- unmapped: LANE_MOTION base, Fireflow.cpp:1130
    {6, 4, spky::P_TIDE, 2},  // row 48 TIDE -- safe: set_tide(mv), Fireflow.cpp:1230
    {6, 5, -1, 2},  // row 49 RES_A -- unmapped: VCV knob 0..1 (Fireflow.cpp:479), table 0..0.75
    {6, 6, -1, 2},  // row 50 TEMPO -- unmapped: VCV maps 40 + 200 v (Fireflow.cpp:1256), table 50..140
    {7, 0, -1, 2},  // row 51 SUB_A -- unmapped: LANE_SIZE on the sampler, Fireflow.cpp:1095
    {7, 1, -1, 2},  // row 52 COMP_A -- unmapped: level/compressor split with a curve, Fireflow.cpp:872-883
    {7, 2, spky::P_PAN_A, 2},  // row 53 PAN_A -- safe: set_pan(mv), Fireflow.cpp:898
    {7, 3, -1, 2},  // row 54 COUPLE -- unmapped: sync zone split, Fireflow.cpp:1211-1216
    {7, 4, -1, 2},  // row 55 GRIT_A -- unmapped: bipolar with a dead zone and a mode, Fireflow.cpp:1143-1148
    {7, 5, spky::P_REVMIX_A, 2},  // row 56 REV_MIX_A -- safe: set_reverb_mix(part, raw), Fireflow.cpp:1241-1242
    {7, 6, spky::P_REV_DIFF, 2},  // row 57 REV_DIFF -- safe: set_reverb_diffusion(mv), Fireflow.cpp:1240
    {8, 0, spky::P_CHOKE, 3},  // row 58 CHOKE -- safe: set_choke(raw), Fireflow.cpp:1231
    {8, 1, spky::P_PULL, 3},  // row 59 PULL -- safe: set_pull(raw), Fireflow.cpp:1232
    {8, 2, -1, 3},  // row 60 MELODY_B -- unmapped: SCAN on the sampler, Fireflow.cpp:1082-1083
    {8, 3, spky::P_MORPH, 3},  // row 61 MORPH -- safe: set_morph(mv), Fireflow.cpp:1204
    {8, 4, spky::P_PACE, 3},  // row 62 PACE -- safe: set_pace(raw), Fireflow.cpp:1262
    {8, 5, -1, 3},  // row 63 DEPTH_B -- unmapped: LANE_MOTION base, Fireflow.cpp:1130
    {8, 6, -1, 3},  // row 64 SUB_B -- unmapped: LANE_SIZE on the sampler, Fireflow.cpp:1095
    {9, 0, spky::P_REV_SIZE, 3},  // row 65 REV_SIZE -- safe: set_reverb_size(mv), Fireflow.cpp:1237
    {9, 1, spky::P_SHUFFLE, 3},  // row 66 SHUFFLE -- safe: set_shuffle(raw), Fireflow.cpp:781
    {9, 2, spky::P_REV_DECAY, 3},  // row 67 REV_DECAY -- safe: set_reverb_decay(mv), Fireflow.cpp:1238
    {9, 3, -1, 3},  // row 68 DRIFT -- unmapped: settle zone, Fireflow.cpp:1223-1229
    {9, 4, spky::P_PAN_B, 3},  // row 69 PAN_B -- safe: set_pan(mv), Fireflow.cpp:898
    {9, 5, spky::P_REV_TONE, 3},  // row 70 REV_TONE -- safe: set_reverb_tone(mv), Fireflow.cpp:1239
    {9, 6, -1, 3},  // row 71 REV_MOD -- reserved: reverb tail wobble (WOBL), follow-up to spec 2026-10-07 section 4
    {9, 7, spky::P_REVMIX_B, 3},  // row 72 REV_MIX_B -- safe: set_reverb_mix(part, raw), Fireflow.cpp:1241-1242
};
inline constexpr ControlTable kRevaTable{
    kRevaControls,
    static_cast<int>(sizeof(kRevaControls) / sizeof(kRevaControls[0]))};

// The calibration channels (P2 section 3): the panel reads its own span.
inline constexpr MuxChannel kRevaCalZero{1, 4};  // CAL_GND
inline constexpr MuxChannel kRevaCalRail{1, 5};  // CAL_3V3

// REC_A, REC_B, MODBTN, SHIFTBTN on the 165's D0..D3; the first bit shifted out is D7.
inline constexpr KeyPad kRevaKeys{4, {7, 6, 5, 4}};

} // namespace shell
