"""Guard for read_settle.py's parser. Runs as a plain script; pytest is not
installed on this machine and the tools/ guards that had no runner stood red
for 23 days behind exactly that gap.

The fixture is generated by build_block() rather than pasted as literal
strings: task-6-amendments.md sec F says the bring-up plan's SAMPLE block is
stale in every line (settle_probe.cpp gained SHELL_SETTLE_CLK, _OFFSET, _REF
and _BAND since the plan was written, and SHELL_SETTLE_CAL grew four fields),
and a generator is the only way to keep twelve cases readable at 2 pairs x 2
grid points.
"""
import sys

from read_settle import parse_block, format_csv

FAILURES = []


def check(label, cond):
    if not cond:
        FAILURES.append(label)


def build_block(num_pairs=2, grid_points=2, sweep_dir=0, gates_ok=1):
    """A format-faithful SHELL_SETTLE block: every line kind settle_probe.cpp
    prints, in its real order, at the smallest size (2 pairs x 2 grid
    points) that still exercises the per-pair completeness checks."""
    lines = [
        "SHELL_SETTLE_CFG sample_cycles=165 adc_khz=6146 repeats=64 "
        "grid_step_ns=200 grid_points=%d park_ns=20000 sweep_dir=%d"
        % (grid_points, sweep_dir),
        "SHELL_SETTLE_CLK span_short_cyc=100 span_long_cyc=200 "
        "smp_short_tenths=165 smp_long_tenths=3875",
    ]
    for p in range(num_pairs):
        lines.append(
            "SHELL_SETTLE_OFFSET pair=%d offset_ns=20 smp_tenths=165" % p)
    for p in range(num_pairs):
        d_values = [i * 200 for i in range(grid_points)]
        if sweep_dir:
            d_values = list(reversed(d_values))
        for d in d_values:
            lines.append(
                "SHELL_SETTLE pair=%d sense=0 from=1 to=10 d_ns=%d n=64 "
                "mean=100 min=98 max=102" % (p, d))
    lines.append(
        "SHELL_SETTLE_CAL lat_mean_ns=320 lat_min_ns=300 lat_max_ns=340 "
        "b0=12 cal_from=1 cal_to=10 timeouts=0 gates_ok=%d" % gates_ok)
    for p in range(num_pairs):
        lines.append(
            "SHELL_SETTLE_KNEE pair=%d d_settle_ns=100 at_or_below_offset=0 "
            "predicted_ns=88 reference=%d" % (p, 1 if p == 0 else 0))
    for p in range(num_pairs):
        lines.append(
            "SHELL_SETTLE_REF pair=%d tail_ref=100 tail_spread=2 "
            "settled_raw_pre=99 settled_raw_post=101" % p)
    for p in range(num_pairs):
        lines.append(
            "SHELL_SETTLE_BAND pair=%d widest_sample_band_counts=4 "
            "at_d_ns=100" % p)
    lines.append("SHELL_SETTLE_GATES g1=%d g2=%d g3=%d g4=%d"
                 % (gates_ok, gates_ok, gates_ok, gates_ok))
    lines.append("SHELL_SETTLE_END")
    return lines


def drop_first(lines, prefix):
    """A copy of `lines` with the first line starting with `prefix` removed
    -- the shape of the only corruption task-6-amendments.md sec B reports
    seeing on hardware: a whole line lost in transit."""
    out = list(lines)
    for i, line in enumerate(out):
        if line.startswith(prefix):
            del out[i]
            return out
    raise AssertionError("no line starts with %r" % prefix)


# --- 1-4: a complete block, and what it carries ---
base = build_block()
block = parse_block(base)
check("a complete block parses", block is not None)
check("every point is kept", block and len(block["points"]) == 4)
check("the verdict is carried", block and block["cal"]["gates_ok"] == 1)
check("the knees are carried", block and len(block["knees"]) == 2)

# --- 5: cut off before the end marker ---
# This is the whole reason the reader accumulates instead of returning on
# the first match: a partial block reports a clean instrument because the
# failing tail never arrived.
check("a block truncated before SHELL_SETTLE_END is refused",
      parse_block(base[:-1]) is None)

# --- 6: cut in the middle, missing a SHELL_SETTLE row ---
# What a serial read timeout actually produces: the end marker arrives, a
# row does not.
missing_point = drop_first(
    base, "SHELL_SETTLE pair=0 sense=0 from=1 to=10 d_ns=0")
check("a block missing a SHELL_SETTLE row is refused",
      parse_block(missing_point) is None)

# --- 7: missing a BAND line (the splice corruption, sec B) ---
# The total-point-count check alone cannot catch this -- only a per-kind,
# per-pair count can.
missing_band = drop_first(base, "SHELL_SETTLE_BAND pair=0")
check("a block missing a BAND line is refused",
      parse_block(missing_band) is None)

# --- 8: a run whose gates failed still parses, and is marked ---
# Refusing to parse it would hide the very numbers that say why.
failed_run = parse_block(build_block(gates_ok=0))
check("a failed run still parses", failed_run is not None)
check("a failed run is marked",
      failed_run and failed_run["cal"]["gates_ok"] == 0)

# --- 9: a descending sweep (sweep_dir=1, d_ns large-to-small) ---
descending = parse_block(build_block(sweep_dir=1))
check("a descending block parses", descending is not None)
check("a descending block keeps all its points",
      descending and len(descending["points"]) == 4)
check("a descending block's points arrive large-to-small, not reordered",
      descending and descending["points"][0]["d_ns"] == 200
      and descending["points"][1]["d_ns"] == 0)

# --- 10: the two meanings of d_settle_ns=-1 ---
two_meanings = list(base)
for i, line in enumerate(two_meanings):
    if line.startswith("SHELL_SETTLE_KNEE pair=0"):
        two_meanings[i] = (
            "SHELL_SETTLE_KNEE pair=0 d_settle_ns=-1 at_or_below_offset=1 "
            "predicted_ns=88 reference=1")
    elif line.startswith("SHELL_SETTLE_KNEE pair=1"):
        two_meanings[i] = (
            "SHELL_SETTLE_KNEE pair=1 d_settle_ns=-1 at_or_below_offset=0 "
            "predicted_ns=88 reference=0")
knee_block = parse_block(two_meanings)
knees_by_pair = {k["pair"]: k for k in knee_block["knees"]} if knee_block else {}
check("a block with -1 knees of both kinds still parses",
      knee_block is not None)
check("settled-at-or-below-offset is distinguishable from never-settled",
      knee_block
      and knees_by_pair[0]["d_settle_ns"] == -1
      and knees_by_pair[0]["at_or_below_offset"] == 1
      and knees_by_pair[1]["d_settle_ns"] == -1
      and knees_by_pair[1]["at_or_below_offset"] == 0)

# --- 11: the CSV ---
csv = format_csv(block)
check("the CSV has a header and one row per point",
      len(csv.strip().split("\n")) == 5)
check("the CSV carries sweep_dir", "sweep_dir" in csv.splitlines()[0])

# --- 12: libDaisy's own "$$" overflow marker ---
# A truncated field must not raise out of the parser, and the block it sits
# in must not be accepted as complete either.
truncated_field = list(base)
truncated_field[-2] = truncated_field[-2][:-2] + "$$"  # corrupts the GATES line
check("a $$-truncated field does not crash the parser, and yields no block",
      parse_block(truncated_field) is None)

# The other corruption sec B names: a splice, where the truncated tail of
# one line and the start of the next arrive fused ("S$$SHELL_SETTLE_END").
spliced_end = list(base)
spliced_end[-1] = "S$$SHELL_SETTLE_END"
check("a spliced end marker does not crash the parser, and yields no block",
      parse_block(spliced_end) is None)

if FAILURES:
    for f in FAILURES:
        print("FAIL: %s" % f, file=sys.stderr)
    raise SystemExit(1)
print("read_settle guard: ok")
