"""Guard for read_settle.py's parser. Runs as a plain script; pytest is not
installed on this machine and the tools/ guards that had no runner stood red
for 23 days behind exactly that gap.

The fixture is generated by build_block() rather than pasted as literal
strings: task-6-amendments.md sec F says the bring-up plan's SAMPLE block is
stale in every line (settle_probe.cpp gained SHELL_SETTLE_CLK, _OFFSET, _REF
and _BAND since the plan was written, and SHELL_SETTLE_CAL grew four fields),
and a generator is the only way to keep thirteen cases readable at 2 pairs x
2 grid points.

Case 12 covers the metadata file the reader now writes beside the grid-point
CSV: before it, the knees, the offsets and the gate verdicts reached stderr
only, and the file the document tells a reader to keep could not reproduce a
single settle time.
"""
import os
import re
import sys

import pot_round
from read_settle import parse_block, format_csv, format_meta_csv, pot_readings, pot_report

FAILURES = []


def check(label, cond):
    if not cond:
        FAILURES.append(label)


def build_block(num_pairs=2, grid_points=2, sweep_dir=0, gates_ok=1):
    """A format-faithful SHELL_SETTLE block: every line kind settle_probe.cpp
    prints, in its real order, at the smallest size (2 pairs x 2 grid
    points) that still exercises the per-pair completeness checks."""
    lines = [
        "SHELL_SETTLE_CFG sample_cycles=165 adc_khz=6146 repeats=64 "
        "grid_step_ns=200 grid_points=%d park_ns=20000 sweep_dir=%d"
        % (grid_points, sweep_dir),
        "SHELL_SETTLE_CLK span_short_cyc=100 span_long_cyc=200 "
        "smp_short_tenths=165 smp_long_tenths=3875",
    ]
    for p in range(num_pairs):
        # A different offset per pair, so a check that recovers
        # "true settle = knee + offset" from the metadata file has to pick
        # the right pair's row rather than passing on a shared constant.
        lines.append(
            "SHELL_SETTLE_OFFSET pair=%d offset_ns=%d smp_tenths=165"
            % (p, 20 + 10 * p))
    for p in range(num_pairs):
        d_values = [i * 200 for i in range(grid_points)]
        if sweep_dir:
            d_values = list(reversed(d_values))
        for d in d_values:
            lines.append(
                "SHELL_SETTLE pair=%d sense=0 from=1 to=10 d_ns=%d n=64 "
                "mean=100 min=98 max=102" % (p, d))
    lines.append(
        "SHELL_SETTLE_CAL lat_mean_ns=320 lat_min_ns=300 lat_max_ns=340 "
        "b0=12 cal_from=1 cal_to=10 timeouts=0 gates_ok=%d" % gates_ok)
    for p in range(num_pairs):
        lines.append(
            "SHELL_SETTLE_KNEE pair=%d d_settle_ns=100 at_or_below_offset=0 "
            "predicted_ns=88 reference=%d" % (p, 1 if p == 0 else 0))
    for p in range(num_pairs):
        lines.append(
            "SHELL_SETTLE_REF pair=%d tail_ref=100 tail_spread=2 "
            "settled_raw_pre=99 settled_raw_post=101" % p)
    for p in range(num_pairs):
        lines.append(
            "SHELL_SETTLE_BAND pair=%d widest_sample_band_counts=4 "
            "at_d_ns=100 settled_mean_spread=%d" % (p, 3 + p))
    lines.append("SHELL_SETTLE_GATES g1=%d g2=%d g3=%d g4=%d cfg_ok=1 "
                 "init_ok=1 cal_ok=1"
                 % (gates_ok, gates_ok, gates_ok, gates_ok))
    lines.append("SHELL_SETTLE_END")
    return lines


def drop_first(lines, prefix):
    """A copy of `lines` with the first line starting with `prefix` removed
    -- the shape of the only corruption task-6-amendments.md sec B reports
    seeing on hardware: a whole line lost in transit."""
    out = list(lines)
    for i, line in enumerate(out):
        if line.startswith(prefix):
            del out[i]
            return out
    raise AssertionError("no line starts with %r" % prefix)


# --- 1-4: a complete block, and what it carries ---
base = build_block()
block = parse_block(base)
check("a complete block parses", block is not None)
check("every point is kept", block and len(block["points"]) == 4)
check("the verdict is carried", block and block["cal"]["gates_ok"] == 1)
check("the knees are carried", block and len(block["knees"]) == 2)

# --- 5: cut off before the end marker ---
# This is the whole reason the reader accumulates instead of returning on
# the first match: a partial block reports a clean instrument because the
# failing tail never arrived.
check("a block truncated before SHELL_SETTLE_END is refused",
      parse_block(base[:-1]) is None)

# --- 6: cut in the middle, missing a SHELL_SETTLE row ---
# What a serial read timeout actually produces: the end marker arrives, a
# row does not.
missing_point = drop_first(
    base, "SHELL_SETTLE pair=0 sense=0 from=1 to=10 d_ns=0")
check("a block missing a SHELL_SETTLE row is refused",
      parse_block(missing_point) is None)

# --- 7: missing a BAND line (the splice corruption, sec B) ---
# The total-point-count check alone cannot catch this -- only a per-kind,
# per-pair count can.
missing_band = drop_first(base, "SHELL_SETTLE_BAND pair=0")
check("a block missing a BAND line is refused",
      parse_block(missing_band) is None)

# --- 8: a run whose gates failed still parses, and is marked ---
# Refusing to parse it would hide the very numbers that say why.
failed_run = parse_block(build_block(gates_ok=0))
check("a failed run still parses", failed_run is not None)
check("a failed run is marked",
      failed_run and failed_run["cal"]["gates_ok"] == 0)

# --- 9: a descending sweep (sweep_dir=1, d_ns large-to-small) ---
descending = parse_block(build_block(sweep_dir=1))
check("a descending block parses", descending is not None)
check("a descending block keeps all its points",
      descending and len(descending["points"]) == 4)
check("a descending block's points arrive large-to-small, not reordered",
      descending and descending["points"][0]["d_ns"] == 200
      and descending["points"][1]["d_ns"] == 0)

# --- 10: the two meanings of d_settle_ns=-1 ---
two_meanings = list(base)
for i, line in enumerate(two_meanings):
    if line.startswith("SHELL_SETTLE_KNEE pair=0"):
        two_meanings[i] = (
            "SHELL_SETTLE_KNEE pair=0 d_settle_ns=-1 at_or_below_offset=1 "
            "predicted_ns=88 reference=1")
    elif line.startswith("SHELL_SETTLE_KNEE pair=1"):
        two_meanings[i] = (
            "SHELL_SETTLE_KNEE pair=1 d_settle_ns=-1 at_or_below_offset=0 "
            "predicted_ns=88 reference=0")
knee_block = parse_block(two_meanings)
knees_by_pair = {k["pair"]: k for k in knee_block["knees"]} if knee_block else {}
check("a block with -1 knees of both kinds still parses",
      knee_block is not None)
check("settled-at-or-below-offset is distinguishable from never-settled",
      knee_block
      and knees_by_pair[0]["d_settle_ns"] == -1
      and knees_by_pair[0]["at_or_below_offset"] == 1
      and knees_by_pair[1]["d_settle_ns"] == -1
      and knees_by_pair[1]["at_or_below_offset"] == 0)

# --- 11: the CSV ---
csv = format_csv(block)
check("the CSV has a header and one row per point",
      len(csv.strip().split("\n")) == 5)
check("the CSV carries sweep_dir", "sweep_dir" in csv.splitlines()[0])

# --- 12: the metadata CSV ---
# The whole point of the second file: the grid-point CSV cannot yield the
# settle times or the verdict, and before this those reached stderr only.
meta_rows = [row.split(",") for row in format_meta_csv(block).strip().split("\n")]
check("the metadata CSV has the four-column header",
      meta_rows[0] == ["scope", "pair", "key", "value"])
meta = {(r[0], r[1], r[2]): r[3] for r in meta_rows[1:]}


def meta_int(scope, pair, key):
    """A metadata value as an int, or None if that row is missing -- so a
    missing row reports as a named FAIL below instead of a KeyError
    traceback that stops the remaining checks from running at all."""
    value = meta.get((scope, str(pair), key))
    return None if value is None else int(value)



check("the metadata carries the block's configuration",
      meta.get(("cfg", "", "grid_points")) == "2"
      and meta.get(("cfg", "", "sweep_dir")) == "0")
check("the metadata carries the clock spans",
      meta.get(("clk", "", "span_long_cyc")) == "200")
check("the metadata carries the calibration pass",
      meta.get(("cal", "", "lat_mean_ns")) == "320"
      and meta.get(("cal", "", "b0")) == "12")
check("the metadata carries the gate verdicts",
      all(meta.get(("gates", "", g)) == "1" for g in ("g1", "g2", "g3", "g4")))
check("the metadata carries the three HAL statuses beside the gates",
      all(meta.get(("gates", "", k)) == "1"
          for k in ("cfg_ok", "init_ok", "cal_ok")))

# "true settle = knee + that pair's offset" -- the arithmetic behind the
# whole settle-time table, recomputed here from the file alone.
check("the metadata yields true settle = knee + offset, per pair",
      all(meta_int("knee", p, "d_settle_ns") is not None
          and meta_int("offset", p, "offset_ns") is not None
          and meta_int("knee", p, "d_settle_ns")
              + meta_int("offset", p, "offset_ns") == 100 + 20 + 10 * p
          for p in (0, 1)))

check("the metadata carries each pair's settled-region reference",
      meta.get(("ref", "0", "tail_ref")) == "100"
      and meta.get(("ref", "1", "tail_spread")) == "2")
check("the metadata carries each pair's settled-region mean spread",
      meta.get(("band", "0", "settled_mean_spread")) == "3"
      and meta.get(("band", "1", "settled_mean_spread")) == "4")
check("the metadata carries the raw per-sample band beside it",
      meta.get(("band", "1", "widest_sample_band_counts")) == "4")
check("a block-level row leaves the pair column empty, not 0",
      all(r[1] == "" for r in meta_rows[1:] if r[0] in ("cfg", "clk", "cal", "gates")))

# A failed run's metadata must still say so -- refusing to write it would
# hide the numbers that explain the refusal, same argument as case 8.
failed_meta = format_meta_csv(parse_block(build_block(gates_ok=0)))
check("a failed run's metadata carries the failed verdicts",
      "gates,,g3,0" in failed_meta)

# --- 13: libDaisy's own "$$" overflow marker ---
# A truncated field must not raise out of the parser, and the block it sits
# in must not be accepted as complete either.
truncated_field = list(base)
truncated_field[-2] = truncated_field[-2][:-2] + "$$"  # corrupts the GATES line
check("a $$-truncated field does not crash the parser, and yields no block",
      parse_block(truncated_field) is None)

# The other corruption sec B names: a splice, where the truncated tail of
# one line and the start of the next arrive fused ("S$$SHELL_SETTLE_END").
spliced_end = list(base)
spliced_end[-1] = "S$$SHELL_SETTLE_END"
check("a spliced end marker does not crash the parser, and yields no block",
      parse_block(spliced_end) is None)

# --- 14: a pot-round block (spec 2026-09-28 sections 4, 6, 7) ---
def pot_block(tail=32768, drop_id=False):
    """build_block() at twelve pairs, the pot lines directly after _CFG, and
    the pot pairs' tail_ref set to `tail` -- the reading PG1 judges."""
    lines = build_block(num_pairs=12)
    pot = pot_round.sample_lines()
    if drop_id:
        pot = pot[:2] + pot[3:]
    lines[1:1] = pot
    out = []
    for line in lines:
        m = re.match(r"SHELL_SETTLE_REF pair=(\d+) tail_ref=100 ", line)
        if m and int(m.group(1)) >= 6:
            line = line.replace("tail_ref=100 ", "tail_ref=%d " % tail)
        out.append(line)
    return out


pb = parse_block(pot_block())
check("14a a twelve-pair pot block parses", pb is not None)
check("14b its pot lines are carried",
      pb is not None and pb["pot_cfg"]["pots"] == 3 and len(pb["pot_ids"]) == 3)
check("14c three readings, one per pot, from P6-P11's tail_ref",
      pb is not None and pot_readings(pb) == [("RV2", 32768.0),
                                              ("RV4", 32768.0),
                                              ("RV6", 32768.0)])
check("14d a pot block missing an ID line is refused",
      parse_block(pot_block(drop_id=True)) is None)
six_with_pots = build_block(num_pairs=6)
six_with_pots[1:1] = pot_round.sample_lines()
check("14e pot lines on a six-pair block are refused",
      parse_block(six_with_pots) is None)
check("14f a block with no pot lines has no readings",
      pot_readings(parse_block(build_block())) == [])
check("14f2 a twelve-pair block with no pot lines at all is refused "
      "(a pot block that lost every pot line must not read as a plain block)",
      parse_block(build_block(num_pairs=12)) is None)
check("14f3 the legacy 2-pair block (no pot lines) still parses",
      parse_block(base) is not None)
_, ok_mid = pot_report(pb)
_, ok_off = pot_report(parse_block(pot_block(tail=28179)))
_, ok_edge = pot_report(parse_block(pot_block(tail=28180)))
check("14g PG1 passes at mid travel", ok_mid)
check("14h PG1 refuses 28179", not ok_off)
check("14i PG1 admits 28180", ok_edge)
pmeta = {tuple(r.split(",")[:3]): r.split(",")[3]
         for r in format_meta_csv(pb).strip().split("\n")[1:]}
check("14j the metadata carries the pot lines",
      pmeta.get(("pot_cfg", "", "pots")) == "3"
      and pmeta.get(("pot_id", "1", "name")) == "RV4")

# --- 15: the first complete block of the real board capture (spec 2026-09-28
# section 10). The board's own values, read from the file, not invented: see
# docs/hardware/captures/README.md for which file and which line. ---
REAL_SETTLE_CAPTURE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "docs", "hardware",
    "captures", "pot-settle-capture-618427c.txt")
with open(REAL_SETTLE_CAPTURE, encoding="utf-8") as fh:
    capture_lines = fh.readlines()
# The first complete block starts at the SHELL_SETTLE_CFG at or after line
# 708 (1-based); everything before it is a partial block that started before
# the port opened (README.md).
real = parse_block(capture_lines[707:])
check("15a the real capture's first complete block parses", real is not None)
check("15b it carries twelve knees",
      real is not None and len(real["knees"]) == 12)
check("15c its three pot readings match the board (RV2/RV4/RV6 tail_ref means)",
      real is not None
      and pot_readings(real) == [("RV2", 32480.0), ("RV4", 32430.5),
                                 ("RV6", 32544.0)])
check("15d PG1 passes on this block",
      real is not None and pot_report(real)[1] is True)
check("15e the block's own calibration gate is recorded as failed (gates_ok=0)",
      real is not None and real["cal"]["gates_ok"] == 0)
check("15f G3 is recorded as failed on this board (the known G3 finding)",
      real is not None and real["gates"]["g3"] == 0)

if FAILURES:
    for f in FAILURES:
        print("FAIL: %s" % f, file=sys.stderr)
    raise SystemExit(1)
print("read_settle guard: ok")
