"""Prepare the bundled factory WAV for a debugger upload into Seed SDRAM."""

from __future__ import annotations

import argparse
import math
import struct
from dataclasses import dataclass
from pathlib import Path


PCM = 1
IEEE_FLOAT = 3
EXTENSIBLE = 0xFFFE


@dataclass(frozen=True)
class Metadata:
    frames: int
    byte_count: int
    fnv1a: int
    sentinels: tuple[float, float, float, float]


def fnv1a32(data: bytes) -> int:
    value = 0x811C9DC5
    for byte in data:
        value = ((value ^ byte) * 0x01000193) & 0xFFFFFFFF
    return value


def _decode_sample(raw: bytes, sample_format: int, bits: int) -> float:
    if sample_format == IEEE_FLOAT:
        if bits != 32:
            raise ValueError("IEEE-float WAV must use 32-bit samples")
        return struct.unpack("<f", raw)[0]
    if sample_format != PCM:
        raise ValueError(f"unsupported WAV format {sample_format}")
    if bits == 16:
        return int.from_bytes(raw, "little", signed=True) / 32768.0
    if bits == 24:
        value = int.from_bytes(raw, "little", signed=False)
        if value & 0x800000:
            value -= 1 << 24
        return value / 8388608.0
    if bits == 32:
        return int.from_bytes(raw, "little", signed=True) / 2147483648.0
    raise ValueError(
        f"unsupported PCM bit depth {bits}; expected 16, 24, or 32"
    )


def decode_wave(path: Path) -> tuple[int, list[float], list[float]]:
    data = path.read_bytes()
    if len(data) < 12 or data[:4] != b"RIFF" or data[8:12] != b"WAVE":
        raise ValueError(f"not a RIFF/WAVE file: {path}")

    sample_format = channels = sample_rate = bits = None
    audio = None
    cursor = 12
    while cursor + 8 <= len(data):
        chunk_id = data[cursor:cursor + 4]
        chunk_size = struct.unpack_from("<I", data, cursor + 4)[0]
        body = cursor + 8
        end = body + chunk_size
        if end > len(data):
            raise ValueError(
                f"WAV chunk {chunk_id!r} extends past end of file"
            )

        if chunk_id == b"fmt ":
            if chunk_size < 16:
                raise ValueError("WAV fmt chunk is shorter than 16 bytes")
            (sample_format, channels, sample_rate, _byte_rate,
             _block_align, bits) = struct.unpack_from("<HHIIHH", data, body)
            if sample_format == EXTENSIBLE:
                if chunk_size < 40:
                    raise ValueError("WAVE_FORMAT_EXTENSIBLE fmt is truncated")
                extension_size = struct.unpack_from("<H", data, body + 16)[0]
                if extension_size < 22:
                    raise ValueError(
                        "WAVE_FORMAT_EXTENSIBLE extension is truncated"
                    )
                sample_format = struct.unpack_from("<H", data, body + 24)[0]
        elif chunk_id == b"data":
            audio = data[body:end]

        cursor = end + (chunk_size & 1)

    if None in (sample_format, channels, sample_rate, bits) or audio is None:
        raise ValueError("WAV is missing fmt or data chunk")
    if channels not in (1, 2):
        raise ValueError(f"unsupported channel count {channels}")
    if sample_format not in (PCM, IEEE_FLOAT):
        raise ValueError(f"unsupported WAV format {sample_format}")

    bytes_per_sample = bits // 8
    frame_bytes = bytes_per_sample * channels
    if bytes_per_sample not in (2, 3, 4) or len(audio) % frame_bytes:
        raise ValueError("WAV data size is not a whole number of frames")

    left: list[float] = []
    right: list[float] = []
    for frame in range(len(audio) // frame_bytes):
        base = frame * frame_bytes
        first = _decode_sample(
            audio[base:base + bytes_per_sample], sample_format, bits
        )
        if channels == 2:
            second = _decode_sample(
                audio[base + bytes_per_sample:base + frame_bytes],
                sample_format,
                bits,
            )
        else:
            second = first
        if not math.isfinite(first) or not math.isfinite(second):
            raise ValueError("WAV contains a non-finite sample")
        left.append(first)
        right.append(second)
    if not left:
        raise ValueError("WAV contains no sample frames")
    return sample_rate, left, right


def _float_literal(value: float) -> str:
    return f"{value:.9g}f"


def write_header(path: Path, metadata: Metadata) -> None:
    first_l, first_r, last_l, last_r = metadata.sentinels
    text = f"""// Generated by prepare_factory.py; do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace audition {{
static constexpr std::size_t kFactoryFrames = {metadata.frames}u;
static constexpr std::size_t kFactoryBytes = {metadata.byte_count}u;
static constexpr std::uint32_t kFactoryFnv1a = 0x{metadata.fnv1a:08x}u;
static constexpr float kFactoryFirstL = {_float_literal(first_l)};
static constexpr float kFactoryFirstR = {_float_literal(first_r)};
static constexpr float kFactoryLastL = {_float_literal(last_l)};
static constexpr float kFactoryLastR = {_float_literal(last_r)};
}}  // namespace audition
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def prepare(source: Path, output: Path, header: Path) -> Metadata:
    sample_rate, left, right = decode_wave(source)
    if sample_rate != 48000:
        raise ValueError(
            f"factory sample must be 48000 Hz, got {sample_rate} Hz"
        )
    planar = struct.pack(f"<{len(left) * 2}f", *(left + right))
    metadata = Metadata(
        frames=len(left),
        byte_count=len(planar),
        fnv1a=fnv1a32(planar),
        sentinels=(left[0], right[0], left[-1], right[-1]),
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(planar)
    write_header(header, metadata)
    return metadata


def main() -> int:
    repo = Path(__file__).resolve().parents[2]
    build = Path(__file__).resolve().parent / "build"
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "source",
        nargs="?",
        type=Path,
        default=repo / "host" / "vcv" / "res" / "factory.wav",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=build / "factory-planar-f32.bin",
    )
    parser.add_argument(
        "--header",
        type=Path,
        default=build / "factory_meta.h",
    )
    args = parser.parse_args()
    metadata = prepare(args.source, args.output, args.header)
    print(
        f"factory: {metadata.frames} frames, {metadata.byte_count} bytes, "
        f"fnv1a=0x{metadata.fnv1a:08x}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
