// GENERATED by res/gen_flow_panel.py -- do not edit by hand.
// Geometry comes from res/touch2_geometry.py, which was measured
// off FireFlow_Website/docs/reference/touch2-fx-2026-08-11.png
// (a sibling repo). Those numbers are photo-derived and
// provisional; they get corrected against the board when it
// arrives. The twelve pad places are laid out on the measured
// field rather than printed from the measured centres -- see
// "the pad field" in the generator. This panel is a VCV panel,
// NOT a faceplate draft.
#pragma once
namespace spkyvcv { namespace glow {
struct XY { float x, y; };
enum WidgetKind { WK_MACRO, WK_PAD, WK_FADER, WK_SWITCH, WK_OUT };
struct PanelCtl { int id; WidgetKind kind; XY mm; const char* label; XY lbl; unsigned char anchor; float lblSize; unsigned lblRgb; const char* tip; };
// anchor: 0 = middle, 1 = start (left-aligned), 2 = end (right-aligned)
struct PanelTxt { XY mm; float size; unsigned rgb; unsigned char anchor; int weight; const char* str; };
enum ParamId {
    MOTION,
    DENSITY,
    BRIGHT,
    DIRT,
    WANDER,
    SPACE,
    PAD_1,
    PAD_2,
    PAD_3,
    PAD_4,
    PAD_5,
    PAD_6,
    PAD_7,
    PAD_8,
    PAD_9,
    PAD_10,
    PAD_11,
    PAD_12,
    FADER_L,
    FADER_R,
    SW_L,
    SW_R,
    NUM_PARAMS
};
enum InputId {
    NUM_INPUTS
};
enum OutputId {
    OUT_L,
    OUT_R,
    NUM_OUTPUTS
};
enum LightId {
    NUM_LIGHTS
};
static constexpr float kPanelW = 81.280f;
static constexpr float kPanelH = 128.500f;
static constexpr float kKnobR   = 3.885f;
static constexpr float kPadW    = 7.600f;
static constexpr float kPadH    = 9.000f;
static constexpr float kPadR    = 2.000f;
static constexpr float kFaderW  = 6.800f;
static constexpr float kFaderH  = 25.290f;
static constexpr float kSwitchW = 5.000f;
static constexpr float kSwitchH = 9.000f;
static constexpr float kJackR   = 4.200f;
static const PanelCtl kParamCtls[] = {
    { MOTION, WK_MACRO, {16.900f, 45.420f}, "", {16.900f, 45.420f}, 0, 2.200f, 0x171713, "MOTION -- how much everything moves  [S31]" },
    { DENSITY, WK_MACRO, {32.730f, 45.480f}, "", {32.730f, 45.480f}, 0, 2.200f, 0x171713, "DENSITY -- how much happens  [S32]" },
    { BRIGHT, WK_MACRO, {48.630f, 45.340f}, "", {48.630f, 45.340f}, 0, 2.200f, 0x171713, "BRIGHT -- spectral centre  [S33]" },
    { DIRT, WK_MACRO, {64.470f, 45.500f}, "", {64.470f, 45.500f}, 0, 2.200f, 0x171713, "DIRT -- clean to driven  [S34]" },
    { WANDER, WK_MACRO, {16.890f, 62.820f}, "", {16.890f, 62.820f}, 0, 2.200f, 0x171713, "WANDER -- predictable to wandering  [S30]" },
    { SPACE, WK_MACRO, {64.460f, 62.830f}, "", {64.460f, 62.830f}, 0, 2.200f, 0x171713, "SPACE -- close to vast  [S35]" },
    { PAD_1, WK_PAD, {5.400f, 82.600f}, "1", {5.400f, 83.510f}, 0, 2.600f, 0x171713, "Place 1 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_2, WK_PAD, {23.020f, 82.600f}, "2", {23.020f, 83.510f}, 0, 2.600f, 0x171713, "Place 2 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_3, WK_PAD, {40.640f, 82.600f}, "3", {40.640f, 83.510f}, 0, 2.600f, 0x171713, "Place 3 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_4, WK_PAD, {58.260f, 82.600f}, "4", {58.260f, 83.510f}, 0, 2.600f, 0x171713, "Place 4 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_5, WK_PAD, {75.880f, 82.600f}, "5", {75.880f, 83.510f}, 0, 2.600f, 0x171713, "Place 5 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_6, WK_PAD, {5.400f, 102.800f}, "6", {5.400f, 103.710f}, 0, 2.600f, 0x171713, "Place 6 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_7, WK_PAD, {23.020f, 102.800f}, "7", {23.020f, 103.710f}, 0, 2.600f, 0x171713, "Place 7 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_8, WK_PAD, {40.640f, 102.800f}, "8", {40.640f, 103.710f}, 0, 2.600f, 0x171713, "Place 8 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_9, WK_PAD, {58.260f, 102.800f}, "9", {58.260f, 103.710f}, 0, 2.600f, 0x171713, "Place 9 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_10, WK_PAD, {75.880f, 102.800f}, "10", {75.880f, 103.710f}, 0, 2.600f, 0x171713, "Place 10 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_11, WK_PAD, {23.020f, 123.000f}, "11", {23.020f, 123.910f}, 0, 2.600f, 0x171713, "Place 11 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_12, WK_PAD, {58.260f, 123.000f}, "12", {58.260f, 123.910f}, 0, 2.600f, 0x171713, "Place 12 -- tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { FADER_L, WK_FADER, {4.610f, 56.750f}, "", {4.610f, 56.750f}, 0, 2.200f, 0x171713, "Fader S36 -- assignable from the context menu" },
    { FADER_R, WK_FADER, {76.740f, 56.800f}, "", {76.740f, 56.800f}, 0, 2.200f, 0x171713, "Fader S37 -- assignable from the context menu" },
    { SW_L, WK_SWITCH, {30.340f, 86.370f}, "", {30.340f, 86.370f}, 0, 2.200f, 0x171713, "Switch S09/S10 -- assignable from the context menu" },
    { SW_R, WK_SWITCH, {45.250f, 92.880f}, "", {45.250f, 92.880f}, 0, 2.200f, 0x171713, "Switch S07/S08 -- assignable from the context menu" },
};
static const PanelCtl kOutputCtls[] = {
    { OUT_L, WK_OUT, {4.310f, 15.150f}, "L", {4.310f, 20.750f}, 0, 2.200f, 0x171713, "Main out, left" },
    { OUT_R, WK_OUT, {4.330f, 30.600f}, "R", {4.330f, 36.200f}, 0, 2.200f, 0x171713, "Main out, right" },
};
static const PanelTxt kTexts[] = {
    { {45.130f, 10.000f}, 4.200f, 0x656056, 2, 300, "FireFlow" },
    { {46.230f, 10.000f}, 4.200f, 0x171713, 1, 700, "GLOW" },
    { {78.280f, 16.750f}, 1.150f, 0xFFFDF7, 0, 700, "ALPHA" },
};
} } // namespace spkyvcv::glow
