// GENERATED by res/gen_flow_panel.py -- do not edit by hand.
// Physical 10+2 geometry comes from res/touch2_geometry.py.
// It is photo-rectified VCV reference data, not fabrication data;
// per-path verification state is carried in PadShape::verified.
#pragma once
#include <cstddef>
#include <cstdint>
#include "pad_geometry.hpp"
namespace spkyvcv { namespace glow {
using XY = spkyvcv::pad_geometry::Point;
enum class PadZone : std::uint8_t { LowerTouch, UpperRear };
struct PadShape { const XY* points; std::size_t pointCount; XY label; XY centre; XY min; XY max; const char* id; PadZone zone; bool verified; };
enum WidgetKind { WK_MACRO, WK_PAD, WK_FADER, WK_SWITCH, WK_OUT };
struct PanelCtl { int id; WidgetKind kind; XY mm; const char* label; XY lbl; unsigned char anchor; float lblSize; unsigned lblRgb; const char* tip; };
// anchor: 0 = middle, 1 = start (left-aligned), 2 = end (right-aligned)
enum ParamId {
    MOTION,
    DENSITY,
    BRIGHT,
    PACE,
    WANDER,
    SPACE,
    PAD_1,
    PAD_2,
    PAD_3,
    PAD_4,
    PAD_5,
    PAD_6,
    PAD_7,
    PAD_8,
    PAD_9,
    PAD_10,
    PAD_11,
    PAD_12,
    FADER_L,
    FADER_R,
    SW_L,
    SW_R,
    NUM_PARAMS
};
enum InputId {
    NUM_INPUTS
};
enum OutputId {
    OUT_L,
    OUT_R,
    NUM_OUTPUTS
};
enum LightId {
    NUM_LIGHTS
};
static constexpr float kPanelW = 81.280f;
static constexpr float kPanelH = 128.500f;
static constexpr float kKnobR   = 3.885f;
static constexpr unsigned kPadCopper    = 0xB96532u;
static constexpr unsigned kPadCopperDim = 0x7D4A30u;
static constexpr unsigned kPadGreen     = 0x1D6F5Fu;
static constexpr unsigned kPadRefused   = 0x8F4A45u;
static constexpr float kPadGlowWidth   = 1.600f;
static constexpr float kPadStrokeWidth = 0.550f;
static constexpr float kPadInnerScale  = 0.820f;
static const XY kPadP00Points[] = { { 15.200f, 77.600f }, { 19.000f, 77.250f }, { 24.000f, 77.250f }, { 28.000f, 77.350f }, { 31.800f, 78.200f }, { 32.000f, 79.800f }, { 30.500f, 81.000f }, { 27.100f, 81.300f }, { 27.000f, 84.000f }, { 26.100f, 86.700f }, { 24.200f, 89.200f }, { 20.500f, 90.000f }, { 17.800f, 88.800f }, { 17.300f, 86.000f }, { 16.500f, 82.500f }, { 15.200f, 79.500f } };
static const XY kPadP01Points[] = { { 33.800f, 77.250f }, { 37.000f, 77.150f }, { 41.000f, 77.150f }, { 45.000f, 77.400f }, { 48.400f, 78.100f }, { 48.200f, 81.000f }, { 46.500f, 84.000f }, { 44.500f, 86.200f }, { 41.700f, 88.200f }, { 39.800f, 90.000f }, { 38.000f, 88.000f }, { 36.200f, 85.500f }, { 34.800f, 83.000f }, { 33.500f, 81.000f }, { 33.200f, 79.000f }, { 33.400f, 78.000f } };
static const XY kPadP02Points[] = { { 49.800f, 77.500f }, { 53.000f, 77.200f }, { 56.500f, 77.200f }, { 60.000f, 77.600f }, { 62.000f, 79.000f }, { 62.200f, 82.000f }, { 61.300f, 85.000f }, { 60.200f, 88.000f }, { 58.800f, 91.000f }, { 55.800f, 90.000f }, { 53.200f, 88.500f }, { 51.200f, 86.000f }, { 49.400f, 84.000f }, { 48.800f, 81.500f }, { 49.000f, 79.000f }, { 49.300f, 78.000f } };
static const XY kPadP03Points[] = { { 0.800f, 100.000f }, { 2.000f, 99.000f }, { 5.000f, 98.500f }, { 9.000f, 98.000f }, { 12.500f, 97.000f }, { 15.000f, 96.000f }, { 16.300f, 99.000f }, { 16.400f, 103.000f }, { 16.000f, 108.000f }, { 14.000f, 113.000f }, { 11.500f, 117.000f }, { 8.000f, 121.000f }, { 4.000f, 124.000f }, { 1.000f, 126.500f }, { 0.500f, 119.000f }, { 0.500f, 106.000f } };
static const XY kPadP04Points[] = { { 18.200f, 93.000f }, { 22.000f, 92.000f }, { 26.500f, 92.000f }, { 29.500f, 93.000f }, { 31.500f, 95.000f }, { 31.800f, 100.000f }, { 31.500f, 105.000f }, { 31.000f, 110.000f }, { 29.000f, 114.000f }, { 25.000f, 115.000f }, { 21.000f, 114.000f }, { 18.500f, 112.000f }, { 17.000f, 108.000f }, { 16.700f, 103.000f }, { 16.800f, 98.000f }, { 17.200f, 94.000f } };
static const XY kPadP05Points[] = { { 34.000f, 93.000f }, { 37.500f, 91.200f }, { 40.000f, 91.500f }, { 41.300f, 94.000f }, { 41.500f, 97.000f }, { 42.400f, 99.000f }, { 44.000f, 101.000f }, { 45.200f, 105.000f }, { 45.200f, 111.000f }, { 44.500f, 117.000f }, { 43.500f, 122.000f }, { 42.500f, 127.000f }, { 39.500f, 128.000f }, { 37.200f, 125.000f }, { 36.000f, 120.000f }, { 35.000f, 113.000f } };
static const XY kPadP06Points[] = { { 48.500f, 94.000f }, { 51.000f, 92.000f }, { 55.000f, 91.000f }, { 60.000f, 92.000f }, { 64.000f, 94.000f }, { 66.000f, 97.000f }, { 66.500f, 102.000f }, { 66.000f, 107.000f }, { 64.500f, 112.000f }, { 61.000f, 115.000f }, { 56.000f, 115.000f }, { 52.000f, 114.000f }, { 49.500f, 112.000f }, { 47.800f, 108.000f }, { 47.000f, 103.000f }, { 48.400f, 98.000f } };
static const XY kPadP07Points[] = { { 69.000f, 100.000f }, { 71.000f, 98.500f }, { 74.000f, 97.500f }, { 78.000f, 97.500f }, { 80.500f, 98.000f }, { 80.800f, 101.000f }, { 80.800f, 105.000f }, { 80.800f, 113.000f }, { 81.000f, 120.000f }, { 80.500f, 127.000f }, { 77.500f, 125.000f }, { 74.000f, 122.000f }, { 71.000f, 119.000f }, { 69.000f, 115.000f }, { 68.000f, 108.000f }, { 68.000f, 102.000f } };
static const XY kPadP08Points[] = { { 11.000f, 119.000f }, { 13.000f, 116.500f }, { 17.000f, 114.500f }, { 23.000f, 113.500f }, { 29.000f, 114.000f }, { 34.000f, 116.000f }, { 36.200f, 119.000f }, { 36.500f, 123.000f }, { 35.000f, 127.300f }, { 30.000f, 128.000f }, { 24.000f, 128.000f }, { 18.000f, 127.800f }, { 13.000f, 127.000f }, { 10.500f, 126.000f }, { 9.800f, 124.000f }, { 10.200f, 121.000f } };
static const XY kPadP09Points[] = { { 47.000f, 118.000f }, { 51.000f, 115.500f }, { 57.000f, 114.500f }, { 63.000f, 115.000f }, { 68.000f, 117.000f }, { 70.000f, 120.000f }, { 70.500f, 123.000f }, { 70.000f, 126.500f }, { 68.000f, 128.000f }, { 62.000f, 128.000f }, { 56.000f, 128.000f }, { 51.000f, 127.800f }, { 47.000f, 127.000f }, { 45.500f, 125.000f }, { 45.300f, 122.000f }, { 46.000f, 120.000f } };
static const XY kPadP10Points[] = { { 28.910f, 2.360f }, { 32.400f, 2.000f }, { 36.370f, 2.180f }, { 40.150f, 2.620f }, { 43.000f, 3.460f }, { 43.500f, 4.880f }, { 42.900f, 6.550f }, { 42.260f, 8.370f }, { 40.730f, 9.790f }, { 37.530f, 10.000f }, { 33.650f, 9.690f }, { 29.480f, 9.470f }, { 26.180f, 8.830f }, { 25.500f, 7.240f }, { 26.100f, 5.390f }, { 27.030f, 3.670f } };
static const XY kPadP11Points[] = { { 47.540f, 2.000f }, { 51.210f, 2.010f }, { 55.240f, 2.700f }, { 58.320f, 3.310f }, { 60.610f, 4.220f }, { 61.810f, 5.670f }, { 62.000f, 7.360f }, { 61.130f, 9.260f }, { 59.260f, 10.840f }, { 56.160f, 11.500f }, { 52.660f, 11.480f }, { 49.350f, 10.780f }, { 46.670f, 9.540f }, { 45.300f, 7.880f }, { 45.000f, 5.960f }, { 45.690f, 3.710f } };
static const PadShape kPadShapes[12] = {
    { kPadP00Points, 16, { 21.200f, 80.200f }, { 22.414f, 82.434f }, { 14.063f, 76.419f }, { 33.032f, 90.809f }, "P00", PadZone::LowerTouch, false },
    { kPadP01Points, 16, { 40.700f, 80.200f }, { 40.683f, 82.027f }, { 32.398f, 76.327f }, { 49.456f, 90.801f }, "P01", PadZone::LowerTouch, false },
    { kPadP02Points, 16, { 55.800f, 80.200f }, { 55.727f, 82.980f }, { 47.985f, 76.356f }, { 63.086f, 91.872f }, "P02", PadZone::LowerTouch, false },
    { kPadP03Points, 16, { 7.200f, 102.000f }, { 7.542f, 109.229f }, { -0.351f, 95.132f }, { 17.257f, 127.473f }, "P03", PadZone::LowerTouch, false },
    { kPadP04Points, 16, { 24.200f, 96.000f }, { 24.230f, 102.976f }, { 15.889f, 91.075f }, { 32.608f, 115.800f }, "P04", PadZone::LowerTouch, false },
    { kPadP05Points, 16, { 39.200f, 102.000f }, { 39.505f, 109.023f }, { 33.105f, 90.029f }, { 46.121f, 128.926f }, "P05", PadZone::LowerTouch, false },
    { kPadP06Points, 16, { 57.000f, 96.000f }, { 56.827f, 103.090f }, { 46.186f, 90.200f }, { 67.300f, 116.065f }, "P06", PadZone::LowerTouch, false },
    { kPadP07Points, 16, { 75.400f, 101.000f }, { 75.174f, 110.260f }, { 67.075f, 96.603f }, { 81.808f, 128.000f }, "P07", PadZone::LowerTouch, false },
    { kPadP08Points, 16, { 22.800f, 120.000f }, { 23.474f, 121.238f }, { 8.993f, 112.679f }, { 37.404f, 128.861f }, "P08", PadZone::LowerTouch, false },
    { kPadP09Points, 16, { 57.800f, 120.000f }, { 58.041f, 121.770f }, { 44.451f, 113.679f }, { 71.300f, 128.912f }, "P09", PadZone::LowerTouch, false },
    { kPadP10Points, 16, { 34.500f, 6.200f }, { 34.569f, 6.020f }, { 24.699f, 1.194f }, { 44.309f, 10.814f }, "P10", PadZone::UpperRear, false },
    { kPadP11Points, 16, { 53.500f, 6.500f }, { 53.312f, 6.763f }, { 44.179f, 1.047f }, { 62.853f, 12.376f }, "P11", PadZone::UpperRear, false },
};
static constexpr float kFaderW  = 6.800f;
static constexpr float kFaderH  = 25.290f;
static constexpr float kSwitchW = 5.000f;
static constexpr float kSwitchH = 9.000f;
static constexpr float kJackR   = 4.200f;
static const PanelCtl kParamCtls[] = {
    { MOTION, WK_MACRO, {16.900f, 45.420f}, "", {16.900f, 45.420f}, 0, 2.200f, 0x171713, "MOTION -- how much everything moves  [S31]" },
    { DENSITY, WK_MACRO, {32.730f, 45.480f}, "", {32.730f, 45.480f}, 0, 2.200f, 0x171713, "DENSITY -- how much happens  [S32]" },
    { BRIGHT, WK_MACRO, {48.630f, 45.340f}, "", {48.630f, 45.340f}, 0, 2.200f, 0x171713, "BRIGHT -- spectral centre  [S33]" },
    { PACE, WK_MACRO, {64.470f, 45.500f}, "", {64.470f, 45.500f}, 0, 2.200f, 0x171713, "PACE -- stretched to rhythmic  [S34]" },
    { WANDER, WK_MACRO, {16.890f, 62.820f}, "", {16.890f, 62.820f}, 0, 2.200f, 0x171713, "WANDER -- predictable to wandering  [S30]" },
    { SPACE, WK_MACRO, {64.460f, 62.830f}, "", {64.460f, 62.830f}, 0, 2.200f, 0x171713, "SPACE -- close to vast  [S35]" },
    { PAD_1, WK_PAD, {22.414f, 82.434f}, "", {21.200f, 80.200f}, 0, 2.600f, 0xB96532, "Touch electrode P00 -- Place 1. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_2, WK_PAD, {40.683f, 82.027f}, "", {40.700f, 80.200f}, 0, 2.600f, 0xB96532, "Touch electrode P01 -- Place 2. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_3, WK_PAD, {55.727f, 82.980f}, "", {55.800f, 80.200f}, 0, 2.600f, 0xB96532, "Touch electrode P02 -- Place 3. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_4, WK_PAD, {7.542f, 109.229f}, "", {7.200f, 102.000f}, 0, 2.600f, 0xB96532, "Touch electrode P03 -- Place 4. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_5, WK_PAD, {24.230f, 102.976f}, "", {24.200f, 96.000f}, 0, 2.600f, 0xB96532, "Touch electrode P04 -- Place 5. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_6, WK_PAD, {39.505f, 109.023f}, "", {39.200f, 102.000f}, 0, 2.600f, 0xB96532, "Touch electrode P05 -- Place 6. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_7, WK_PAD, {56.827f, 103.090f}, "", {57.000f, 96.000f}, 0, 2.600f, 0xB96532, "Touch electrode P06 -- Place 7. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_8, WK_PAD, {75.174f, 110.260f}, "", {75.400f, 101.000f}, 0, 2.600f, 0xB96532, "Touch electrode P07 -- Place 8. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_9, WK_PAD, {23.474f, 121.238f}, "", {22.800f, 120.000f}, 0, 2.600f, 0xB96532, "Touch electrode P08 -- Place 9. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_10, WK_PAD, {58.041f, 121.770f}, "", {57.800f, 120.000f}, 0, 2.600f, 0xB96532, "Touch electrode P09 -- Place 10. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_11, WK_PAD, {34.569f, 6.020f}, "", {34.500f, 6.200f}, 0, 2.600f, 0xB96532, "Touch electrode P10 -- Place 11. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { PAD_12, WK_PAD, {53.312f, 6.763f}, "", {53.500f, 6.500f}, 0, 2.600f, 0xB96532, "Touch electrode P11 -- Place 12. Tap: go there. Hold: reroll all six macro domains, the ground stays. Tap again: back." },
    { FADER_L, WK_FADER, {4.610f, 56.750f}, "", {4.610f, 56.750f}, 0, 2.200f, 0x171713, "Fader S36 -- assignable from the context menu" },
    { FADER_R, WK_FADER, {76.740f, 56.800f}, "", {76.740f, 56.800f}, 0, 2.200f, 0x171713, "Fader S37 -- assignable from the context menu" },
    { SW_L, WK_SWITCH, {30.340f, 86.370f}, "", {30.340f, 86.370f}, 0, 2.200f, 0x171713, "Switch S09/S10 -- assignable from the context menu" },
    { SW_R, WK_SWITCH, {45.250f, 92.880f}, "", {45.250f, 92.880f}, 0, 2.200f, 0x171713, "Switch S07/S08 -- assignable from the context menu" },
};
static const PanelCtl kOutputCtls[] = {
    { OUT_L, WK_OUT, {4.310f, 15.150f}, "L", {4.310f, 20.750f}, 0, 2.200f, 0xD7D1C5, "Main out, left" },
    { OUT_R, WK_OUT, {4.330f, 30.600f}, "R", {4.330f, 36.200f}, 0, 2.200f, 0xD7D1C5, "Main out, right" },
};
} } // namespace spkyvcv::glow
