// GENERATED by res/gen_hw_panel.py -- do not edit by hand.
#pragma once
#include "generated_panel.hpp"
namespace spkyhw {
using namespace spkyvcv;
struct HwOnlyCtl { WidgetKind kind; XY mm; const char* label;
                   XY lbl; unsigned char anchor; float lblSize;
                   unsigned lblRgb; };
static constexpr int kHwHP = 60;
static const PanelCtl kParamCtls[] = {
    {RATE_A, WK_BIGKNOB, {61.000f, 14.500f}, "RATE", {61.000f, 22.500f}, 0, 2.20f, 0x171713, "RATE"},
    {SHAPE_A, WK_BIGKNOB, {18.250f, 34.000f}, "SHAP", {18.250f, 42.000f}, 0, 2.20f, 0x171713, "SHAPE"},
    {DENSITY_A, WK_BIGKNOB, {40.750f, 53.000f}, "DENS", {40.750f, 63.500f}, 0, 2.20f, 0x171713, "DENS"},
    {SMOOTH_A, WK_BIGKNOB, {31.250f, 34.000f}, "SMTH", {31.250f, 42.000f}, 0, 2.20f, 0x171713, "SMTH"},
    {RANGE_A, WK_BIGKNOB, {44.250f, 34.000f}, "RANG", {44.250f, 42.000f}, 0, 2.20f, 0x171713, "RANGE"},
    {MELODY_A, WK_KNOBC, {74.000f, 14.500f}, "VARY", {74.000f, 22.500f}, 0, 2.20f, 0x171713, "Variation"},
    {MOD_A, WK_BIGKNOB, {21.750f, 53.000f}, "MOD", {21.750f, 63.500f}, 0, 2.20f, 0x171713, "MOD"},
    {TUNE_A, WK_BIGKNOB, {17.000f, 76.000f}, "TUNE", {17.000f, 84.000f}, 0, 2.20f, 0x171713, "TUNE"},
    {ATTACK_A, WK_SMKNOB, {68.250f, 34.000f}, "ATK", {68.250f, 42.000f}, 0, 2.20f, 0x171713, "ATK"},
    {DECAY_A, WK_SMKNOB, {81.250f, 34.000f}, "DEC", {81.250f, 42.000f}, 0, 2.20f, 0x171713, "DEC"},
    {RES_A, WK_SMKNOB, {94.250f, 34.000f}, "RES", {94.250f, 42.000f}, 0, 2.20f, 0x171713, "RES"},
    {SUB_A, WK_SMKNOB, {107.250f, 34.000f}, "SUB", {107.250f, 42.000f}, 0, 2.20f, 0x171713, "SUB"},
    {SOURCE_A, WK_SMKNOB, {102.250f, 47.610f}, "TIMB", {102.250f, 55.610f}, 0, 2.20f, 0x171713, "SOURCE"},
    {FLUX_A, WK_SMKNOB, {67.000f, 76.000f}, "MIX", {67.000f, 86.500f}, 0, 2.20f, 0x171713, "FLUX"},
    {GRIT_A, WK_KNOBC, {106.500f, 95.000f}, "GRIT", {106.500f, 103.000f}, 0, 2.20f, 0x171713, "GRIT"},
    {COMP_A, WK_SMKNOB, {106.500f, 76.000f}, "LVL", {106.500f, 86.500f}, 0, 2.20f, 0x171713, "Level / Comp"},
    {STEPS_A, WK_KNOBI, {35.000f, 14.500f}, "STPS", {35.000f, 22.500f}, 0, 2.20f, 0x171713, "STPS"},
    {ENGINE_A, WK_LATCH, {70.250f, 49.250f}, "ENG", {70.250f, 57.250f}, 0, 2.20f, 0x171713, "ENG"},
    {DETUNE_A, WK_SMKNOB, {30.000f, 76.000f}, "DTUN", {30.000f, 84.000f}, 0, 2.20f, 0x171713, "Detune"},
    {SONG_A, WK_KNOBI, {48.000f, 14.500f}, "SONG", {48.000f, 22.500f}, 0, 2.20f, 0x171713, "SONG"},
    {RATE_B, WK_BIGKNOB, {243.800f, 14.500f}, "RATE", {243.800f, 22.500f}, 0, 2.20f, 0x171713, "RATE"},
    {SHAPE_B, WK_BIGKNOB, {286.550f, 34.000f}, "SHAP", {286.550f, 42.000f}, 0, 2.20f, 0x171713, "SHAPE"},
    {DENSITY_B, WK_BIGKNOB, {264.050f, 53.000f}, "DENS", {264.050f, 63.500f}, 0, 2.20f, 0x171713, "DENS"},
    {SMOOTH_B, WK_BIGKNOB, {273.550f, 34.000f}, "SMTH", {273.550f, 42.000f}, 0, 2.20f, 0x171713, "SMTH"},
    {RANGE_B, WK_BIGKNOB, {260.550f, 34.000f}, "RANG", {260.550f, 42.000f}, 0, 2.20f, 0x171713, "RANGE"},
    {MELODY_B, WK_KNOBC, {230.800f, 14.500f}, "VARY", {230.800f, 22.500f}, 0, 2.20f, 0x171713, "Variation"},
    {MOD_B, WK_BIGKNOB, {283.050f, 53.000f}, "MOD", {283.050f, 63.500f}, 0, 2.20f, 0x171713, "MOD"},
    {TUNE_B, WK_BIGKNOB, {287.800f, 76.000f}, "TUNE", {287.800f, 84.000f}, 0, 2.20f, 0x171713, "TUNE"},
    {ATTACK_B, WK_SMKNOB, {236.550f, 34.000f}, "ATK", {236.550f, 42.000f}, 0, 2.20f, 0x171713, "ATK"},
    {DECAY_B, WK_SMKNOB, {223.550f, 34.000f}, "DEC", {223.550f, 42.000f}, 0, 2.20f, 0x171713, "DEC"},
    {RES_B, WK_SMKNOB, {210.550f, 34.000f}, "RES", {210.550f, 42.000f}, 0, 2.20f, 0x171713, "RES"},
    {SUB_B, WK_SMKNOB, {197.550f, 34.000f}, "SUB", {197.550f, 42.000f}, 0, 2.20f, 0x171713, "SUB"},
    {SOURCE_B, WK_SMKNOB, {202.550f, 47.610f}, "TIMB", {202.550f, 55.610f}, 0, 2.20f, 0x171713, "SOURCE"},
    {FLUX_B, WK_SMKNOB, {237.800f, 76.000f}, "MIX", {237.800f, 86.500f}, 0, 2.20f, 0x171713, "FLUX"},
    {GRIT_B, WK_KNOBC, {198.300f, 95.000f}, "GRIT", {198.300f, 103.000f}, 0, 2.20f, 0x171713, "GRIT"},
    {COMP_B, WK_SMKNOB, {198.300f, 76.000f}, "LVL", {198.300f, 86.500f}, 0, 2.20f, 0x171713, "Level / Comp"},
    {STEPS_B, WK_KNOBI, {269.800f, 14.500f}, "STPS", {269.800f, 22.500f}, 0, 2.20f, 0x171713, "STPS"},
    {ENGINE_B, WK_LATCH, {234.550f, 49.250f}, "ENG", {234.550f, 57.250f}, 0, 2.20f, 0x171713, "ENG"},
    {DETUNE_B, WK_SMKNOB, {274.800f, 76.000f}, "DTUN", {274.800f, 84.000f}, 0, 2.20f, 0x171713, "Detune"},
    {SONG_B, WK_KNOBI, {256.800f, 14.500f}, "SONG", {256.800f, 22.500f}, 0, 2.20f, 0x171713, "SONG"},
    {MORPH, WK_BIGKNOB, {152.400f, 53.000f}, "MRPH", {152.400f, 63.500f}, 0, 2.20f, 0x171713, "MORPH"},
    {TEMPO, WK_SMKNOB, {139.400f, 34.000f}, "TEMP", {139.400f, 42.000f}, 0, 2.20f, 0x171713, "TEMPO"},
    {COUPLE, WK_SMKNOB, {152.400f, 34.000f}, "SYNC", {152.400f, 42.000f}, 0, 2.20f, 0x171713, "FREE|GRID"},
    {SCALE, WK_KNOBI, {139.400f, 14.500f}, "SCAL", {139.400f, 22.500f}, 0, 2.20f, 0x171713, "SCALE"},
    {DRIFT, WK_SMKNOB, {152.400f, 14.500f}, "DRFT", {152.400f, 22.500f}, 0, 2.20f, 0x171713, "DRIFT"},
    {REV_SIZE, WK_SMKNOB, {136.400f, 76.000f}, "SIZE", {136.400f, 84.000f}, 0, 2.20f, 0x171713, "SIZE"},
    {REV_DECAY, WK_SMKNOB, {152.400f, 79.000f}, "DECY", {152.400f, 89.500f}, 0, 2.20f, 0x171713, "DECAY"},
    {REV_TONE, WK_SMKNOB, {152.400f, 97.000f}, "TONE", {152.400f, 105.000f}, 0, 2.20f, 0x171713, "TONE"},
    {REV_DIFF, WK_SMKNOB, {168.400f, 76.000f}, "DIFF", {168.400f, 84.000f}, 0, 2.20f, 0x171713, "DIFF"},
    {CHOKE, WK_SMKNOB, {165.400f, 14.500f}, "CHOK", {165.400f, 22.500f}, 0, 2.20f, 0x171713, "CHOKE"},
    {FILT_A, WK_SMKNOB, {86.250f, 51.000f}, "FILT", {86.250f, 61.500f}, 0, 2.20f, 0x171713, "FILT"},
    {FILT_B, WK_SMKNOB, {218.550f, 51.000f}, "FILT", {218.550f, 61.500f}, 0, 2.20f, 0x171713, "FILT"},
    {TIDE, WK_SMKNOB, {136.400f, 50.220f}, "TIDE", {136.400f, 58.220f}, 0, 2.20f, 0x171713, "TIDE"},
    {FLUXRATE_A, WK_KNOBI, {54.000f, 89.860f}, "TIME", {54.000f, 97.860f}, 0, 2.20f, 0x171713, "FLUX time"},
    {FLUXRATE_B, WK_KNOBI, {250.800f, 89.860f}, "TIME", {250.800f, 97.860f}, 0, 2.20f, 0x171713, "FLUX time"},
    {FLUXFB_A, WK_SMKNOB, {67.000f, 95.000f}, "FB", {67.000f, 103.000f}, 0, 2.20f, 0x171713, "FFB"},
    {FLUXFB_B, WK_SMKNOB, {237.800f, 95.000f}, "FB", {237.800f, 103.000f}, 0, 2.20f, 0x171713, "FFB"},
    {COLOR_A, WK_BIGKNOB, {23.500f, 95.000f}, "COLR", {23.500f, 105.500f}, 0, 2.20f, 0x171713, "COLOR"},
    {COLOR_B, WK_BIGKNOB, {281.300f, 95.000f}, "COLR", {281.300f, 105.500f}, 0, 2.20f, 0x171713, "COLOR"},
    {LINK_A, WK_SMKNOB, {80.000f, 89.860f}, "LINK", {80.000f, 97.860f}, 0, 2.20f, 0x171713, "LINK"},
    {LINK_B, WK_SMKNOB, {224.800f, 89.860f}, "LINK", {224.800f, 97.860f}, 0, 2.20f, 0x171713, "LINK"},
    {STAGES_A, WK_SMKNOB, {68.250f, 34.000f}, "", {68.250f, 34.000f}, 0, 2.20f, 0x171713, "BBD Bend"},
    {STAGES_B, WK_SMKNOB, {236.550f, 34.000f}, "", {236.550f, 34.000f}, 0, 2.20f, 0x171713, "BBD Bend"},
    {REC_A, WK_LATCH, {101.000f, 14.500f}, "REC", {101.000f, 21.000f}, 0, 2.20f, 0x171713, "REC"},
    {REC_B, WK_LATCH, {203.800f, 14.500f}, "REC", {203.800f, 21.000f}, 0, 2.20f, 0x171713, "REC"},
    {REV_MIX_A, WK_SMKNOB, {136.400f, 95.000f}, "SEND", {136.400f, 105.500f}, 0, 2.20f, 0x171713, "Room send"},
    {REV_MIX_B, WK_SMKNOB, {168.400f, 95.000f}, "SEND", {168.400f, 105.500f}, 0, 2.20f, 0x171713, "Room send"},
    {SHUFFLE, WK_SMKNOB, {165.400f, 34.000f}, "SHFL", {165.400f, 42.000f}, 0, 2.20f, 0x171713, "SHUFL"},
    {PACE, WK_SMKNOB, {168.400f, 50.220f}, "PACE", {168.400f, 58.220f}, 0, 2.20f, 0x171713, "PACE"},
};
// 1 = big cap, 0 = small. Parallel to kParamCtls, same order.
// The rehearsal widget reads THIS, not c.kind -- kind says
// bipolar/detented, which is not a diameter.
static const unsigned char kParamSize[] = {
    0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
};
static_assert(sizeof(kParamSize) == sizeof(kParamCtls) / sizeof(kParamCtls[0]), "kParamSize desynced");
static const PanelCtl kInputCtls[] = {
    {IN_L, WK_IN, {33.000f, 114.000f}, "IN L", {33.000f, 122.000f}, 0, 2.20f, 0x171713, "IN L"},
    {IN_R, WK_IN, {44.500f, 114.000f}, "IN R", {44.500f, 122.000f}, 0, 2.20f, 0x171713, "IN R"},
    {CLOCK, WK_IN, {136.000f, 114.000f}, "CLK", {136.000f, 122.000f}, 0, 2.20f, 0x171713, "Clock"},
    {RESET, WK_IN, {168.800f, 114.000f}, "RST", {168.800f, 122.000f}, 0, 2.20f, 0x171713, "Reset"},
    {MOD1_A, WK_IN, {79.000f, 114.000f}, "MOD1", {79.000f, 122.000f}, 0, 2.20f, 0x171713, "Mod 1 (unwired)"},
    {MOD2_A, WK_IN, {90.500f, 114.000f}, "MOD2", {90.500f, 122.000f}, 0, 2.20f, 0x171713, "Mod 2 (unwired)"},
    {MOD3_A, WK_IN, {102.000f, 114.000f}, "MOD3", {102.000f, 122.000f}, 0, 2.20f, 0x171713, "Mod 3 (unwired)"},
    {MOD4_A, WK_IN, {113.500f, 114.000f}, "MOD4", {113.500f, 122.000f}, 0, 2.20f, 0x171713, "Mod 4 (unwired)"},
    {MOD1_B, WK_IN, {225.800f, 114.000f}, "MOD1", {225.800f, 122.000f}, 0, 2.20f, 0x171713, "Mod 1 (unwired)"},
    {MOD2_B, WK_IN, {214.300f, 114.000f}, "MOD2", {214.300f, 122.000f}, 0, 2.20f, 0x171713, "Mod 2 (unwired)"},
    {MOD3_B, WK_IN, {202.800f, 114.000f}, "MOD3", {202.800f, 122.000f}, 0, 2.20f, 0x171713, "Mod 3 (unwired)"},
    {MOD4_B, WK_IN, {191.300f, 114.000f}, "MOD4", {191.300f, 122.000f}, 0, 2.20f, 0x171713, "Mod 4 (unwired)"},
};
static const PanelCtl kOutputCtls[] = {
    {OUT_L, WK_OUT, {260.300f, 114.000f}, "OUT L", {260.300f, 122.000f}, 0, 2.20f, 0x171713, "OUT L"},
    {OUT_R, WK_OUT, {271.800f, 114.000f}, "OUT R", {271.800f, 122.000f}, 0, 2.20f, 0x171713, "OUT R"},
    {PITCH_A, WK_OUT, {56.000f, 114.000f}, "PIT", {56.000f, 122.000f}, 0, 2.20f, 0x171713, "Pitch A"},
    {GATE_A, WK_OUT, {67.500f, 114.000f}, "GATE", {67.500f, 122.000f}, 0, 2.20f, 0x171713, "Gate A"},
    {PITCH_B, WK_OUT, {248.800f, 114.000f}, "PIT", {248.800f, 122.000f}, 0, 2.20f, 0x171713, "Pitch B"},
    {GATE_B, WK_OUT, {237.300f, 114.000f}, "GATE", {237.300f, 122.000f}, 0, 2.20f, 0x171713, "Gate B"},
};
static const PanelCtl kLightCtls[] = {
    {GATE_A_L, WK_LIGHT, {116.500f, 14.500f}, "", {116.500f, 14.500f}, 0, 2.20f, 0x171713, ""},
    {GATE_B_L, WK_LIGHT, {188.300f, 14.500f}, "", {188.300f, 14.500f}, 0, 2.20f, 0x171713, ""},
    {REC_A_L, WK_LIGHT, {108.500f, 14.500f}, "", {108.500f, 14.500f}, 0, 2.20f, 0x171713, ""},
    {REC_B_L, WK_LIGHT, {196.300f, 14.500f}, "", {196.300f, 14.500f}, 0, 2.20f, 0x171713, ""},
};
// Hardware-only: no VCV id. Rack does not render SVG text,
// so these captions must come from here (spec 2026-08-10 §5).
static const HwOnlyCtl kHwOnlyCtls[] = {
    {WK_LATCH, {14.000f, 114.000f}, "SHFT", {14.000f, 122.000f}, 0, 2.20f, 0x171713},
    {WK_LATCH, {290.800f, 114.000f}, "MOD", {290.800f, 122.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {130.400f, 34.000f}, "", {130.400f, 34.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {174.400f, 34.000f}, "", {174.400f, 34.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {93.500f, 14.500f}, "", {93.500f, 14.500f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {112.500f, 14.500f}, "", {112.500f, 14.500f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {211.300f, 14.500f}, "", {211.300f, 14.500f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {192.300f, 14.500f}, "", {192.300f, 14.500f}, 0, 2.20f, 0x171713},
};
static const PanelTxt kPanelTexts[] = {
};
} // namespace spkyhw
