// GENERATED by res/gen_hw_panel.py -- do not edit by hand.
#pragma once
#include "generated_panel.hpp"
namespace spkyhw {
using namespace spkyvcv;
struct HwOnlyCtl { WidgetKind kind; XY mm; const char* label;
                   XY lbl; unsigned char anchor; float lblSize;
                   unsigned lblRgb; };
static constexpr int kHwHP = 60;
static const PanelCtl kParamCtls[] = {
    {RATE_A, WK_BIGKNOB, {14.000f, 30.000f}, "RATE", {14.000f, 38.000f}, 0, 2.20f, 0x171713, "RATE"},
    {SHAPE_A, WK_BIGKNOB, {26.500f, 30.000f}, "SHAPE", {26.500f, 22.000f}, 0, 2.20f, 0x171713, "SHAPE"},
    {DENSITY_A, WK_BIGKNOB, {51.500f, 46.000f}, "DENS", {51.500f, 56.500f}, 0, 2.20f, 0x171713, "DENS"},
    {SMOOTH_A, WK_BIGKNOB, {39.000f, 30.000f}, "SMTH", {39.000f, 38.000f}, 0, 2.20f, 0x171713, "SMTH"},
    {RANGE_A, WK_BIGKNOB, {51.500f, 30.000f}, "RANGE", {51.500f, 22.000f}, 0, 2.20f, 0x171713, "RANGE"},
    {MELODY_A, WK_KNOBC, {64.000f, 30.000f}, "VARY", {64.000f, 38.000f}, 0, 2.20f, 0x171713, "Variation"},
    {MOD_A, WK_BIGKNOB, {26.500f, 46.000f}, "MOD", {26.500f, 56.500f}, 0, 2.20f, 0x171713, "MOD"},
    {TUNE_A, WK_BIGKNOB, {70.000f, 66.000f}, "TUNE", {70.000f, 74.000f}, 0, 2.20f, 0x171713, "TUNE"},
    {ATTACK_A, WK_SMKNOB, {14.000f, 66.000f}, "ATK", {14.000f, 74.000f}, 0, 2.20f, 0x171713, "ATK"},
    {DECAY_A, WK_SMKNOB, {26.500f, 66.000f}, "DEC", {26.500f, 74.000f}, 0, 2.20f, 0x171713, "DEC"},
    {RES_A, WK_SMKNOB, {39.000f, 66.000f}, "RES", {39.000f, 74.000f}, 0, 2.20f, 0x171713, "RES"},
    {SUB_A, WK_SMKNOB, {51.500f, 66.000f}, "SUB", {51.500f, 74.000f}, 0, 2.20f, 0x171713, "SUB"},
    {SOURCE_A, WK_SMKNOB, {42.500f, 86.000f}, "TIMB", {42.500f, 96.500f}, 0, 2.20f, 0x171713, "SOURCE"},
    {FLUX_A, WK_SMKNOB, {88.500f, 46.000f}, "MIX", {88.500f, 56.500f}, 0, 2.20f, 0x171713, "FLUX"},
    {GRIT_A, WK_KNOBC, {100.000f, 66.000f}, "GRIT", {100.000f, 74.000f}, 0, 2.20f, 0x171713, "GRIT"},
    {COMP_A, WK_SMKNOB, {100.000f, 86.000f}, "LVL", {100.000f, 96.500f}, 0, 2.20f, 0x171713, "Level / Comp"},
    {STEPS_A, WK_KNOBI, {14.000f, 15.000f}, "STPS", {14.000f, 23.000f}, 0, 2.20f, 0x171713, "STPS"},
    {ENGINE_A, WK_LATCH, {38.500f, 15.000f}, "ENG", {38.500f, 21.500f}, 0, 2.20f, 0x171713, "ENG"},
    {DETUNE_A, WK_SMKNOB, {82.500f, 66.000f}, "DTUN", {82.500f, 74.000f}, 0, 2.20f, 0x171713, "Detune"},
    {SONG_A, WK_KNOBI, {26.500f, 15.000f}, "SONG", {26.500f, 23.000f}, 0, 2.20f, 0x171713, "SONG"},
    {RATE_B, WK_BIGKNOB, {290.800f, 30.000f}, "RATE", {290.800f, 38.000f}, 0, 2.20f, 0x171713, "RATE"},
    {SHAPE_B, WK_BIGKNOB, {278.300f, 30.000f}, "SHAPE", {278.300f, 22.000f}, 0, 2.20f, 0x171713, "SHAPE"},
    {DENSITY_B, WK_BIGKNOB, {253.300f, 46.000f}, "DENS", {253.300f, 56.500f}, 0, 2.20f, 0x171713, "DENS"},
    {SMOOTH_B, WK_BIGKNOB, {265.800f, 30.000f}, "SMTH", {265.800f, 38.000f}, 0, 2.20f, 0x171713, "SMTH"},
    {RANGE_B, WK_BIGKNOB, {253.300f, 30.000f}, "RANGE", {253.300f, 22.000f}, 0, 2.20f, 0x171713, "RANGE"},
    {MELODY_B, WK_KNOBC, {240.800f, 30.000f}, "VARY", {240.800f, 38.000f}, 0, 2.20f, 0x171713, "Variation"},
    {MOD_B, WK_BIGKNOB, {278.300f, 46.000f}, "MOD", {278.300f, 56.500f}, 0, 2.20f, 0x171713, "MOD"},
    {TUNE_B, WK_BIGKNOB, {234.800f, 66.000f}, "TUNE", {234.800f, 74.000f}, 0, 2.20f, 0x171713, "TUNE"},
    {ATTACK_B, WK_SMKNOB, {290.800f, 66.000f}, "ATK", {290.800f, 74.000f}, 0, 2.20f, 0x171713, "ATK"},
    {DECAY_B, WK_SMKNOB, {278.300f, 66.000f}, "DEC", {278.300f, 74.000f}, 0, 2.20f, 0x171713, "DEC"},
    {RES_B, WK_SMKNOB, {265.800f, 66.000f}, "RES", {265.800f, 74.000f}, 0, 2.20f, 0x171713, "RES"},
    {SUB_B, WK_SMKNOB, {253.300f, 66.000f}, "SUB", {253.300f, 74.000f}, 0, 2.20f, 0x171713, "SUB"},
    {SOURCE_B, WK_SMKNOB, {262.300f, 86.000f}, "TIMB", {262.300f, 96.500f}, 0, 2.20f, 0x171713, "SOURCE"},
    {FLUX_B, WK_SMKNOB, {216.300f, 46.000f}, "MIX", {216.300f, 56.500f}, 0, 2.20f, 0x171713, "FLUX"},
    {GRIT_B, WK_KNOBC, {204.800f, 66.000f}, "GRIT", {204.800f, 74.000f}, 0, 2.20f, 0x171713, "GRIT"},
    {COMP_B, WK_SMKNOB, {204.800f, 86.000f}, "LVL", {204.800f, 96.500f}, 0, 2.20f, 0x171713, "Level / Comp"},
    {STEPS_B, WK_KNOBI, {290.800f, 15.000f}, "STPS", {290.800f, 23.000f}, 0, 2.20f, 0x171713, "STPS"},
    {ENGINE_B, WK_LATCH, {266.300f, 15.000f}, "ENG", {266.300f, 21.500f}, 0, 2.20f, 0x171713, "ENG"},
    {DETUNE_B, WK_SMKNOB, {222.300f, 66.000f}, "DTUN", {222.300f, 74.000f}, 0, 2.20f, 0x171713, "Detune"},
    {SONG_B, WK_KNOBI, {278.300f, 15.000f}, "SONG", {278.300f, 23.000f}, 0, 2.20f, 0x171713, "SONG"},
    {MORPH, WK_BIGKNOB, {152.400f, 62.000f}, "MORPH", {152.400f, 51.500f}, 0, 2.20f, 0x171713, "MORPH"},
    {TEMPO, WK_SMKNOB, {127.400f, 30.000f}, "TEMPO", {127.400f, 38.000f}, 0, 2.20f, 0x171713, "TEMPO"},
    {COUPLE, WK_SMKNOB, {139.900f, 30.000f}, "FREE|GRID", {139.900f, 38.000f}, 0, 2.20f, 0x171713, "FREE|GRID"},
    {SCALE, WK_KNOBI, {164.900f, 30.000f}, "SCALE", {164.900f, 38.000f}, 0, 2.20f, 0x171713, "SCALE"},
    {DRIFT, WK_SMKNOB, {177.400f, 30.000f}, "DRIFT", {177.400f, 38.000f}, 0, 2.20f, 0x171713, "DRIFT"},
    {REV_SIZE, WK_SMKNOB, {134.400f, 94.000f}, "SIZE", {134.400f, 102.000f}, 0, 2.20f, 0x171713, "SIZE"},
    {REV_DECAY, WK_SMKNOB, {152.400f, 79.000f}, "DECAY", {161.400f, 80.000f}, 1, 2.20f, 0x171713, "DECAY"},
    {REV_TONE, WK_SMKNOB, {152.400f, 94.000f}, "TONE", {152.400f, 102.000f}, 0, 2.20f, 0x171713, "TONE"},
    {REV_DIFF, WK_SMKNOB, {170.400f, 94.000f}, "DIFF", {170.400f, 102.000f}, 0, 2.20f, 0x171713, "DIFF"},
    {CHOKE, WK_SMKNOB, {164.400f, 46.000f}, "CHOKE", {164.400f, 54.000f}, 0, 2.20f, 0x171713, "CHOKE"},
    {FILT_A, WK_SMKNOB, {23.000f, 86.000f}, "FILT", {23.000f, 96.500f}, 0, 2.20f, 0x171713, "FILT"},
    {FILT_B, WK_SMKNOB, {281.800f, 86.000f}, "FILT", {281.800f, 96.500f}, 0, 2.20f, 0x171713, "FILT"},
    {TIDE, WK_SMKNOB, {140.400f, 46.000f}, "TIDE", {140.400f, 54.000f}, 0, 2.20f, 0x171713, "TIDE"},
    {FLUXRATE_A, WK_KNOBI, {76.000f, 30.000f}, "TIME", {76.000f, 38.000f}, 0, 2.20f, 0x171713, "FLUX time"},
    {FLUXRATE_B, WK_KNOBI, {228.800f, 30.000f}, "TIME", {228.800f, 38.000f}, 0, 2.20f, 0x171713, "FLUX time"},
    {FLUXFB_A, WK_SMKNOB, {88.500f, 30.000f}, "FB", {88.500f, 22.000f}, 0, 2.20f, 0x171713, "FFB"},
    {FLUXFB_B, WK_SMKNOB, {216.300f, 30.000f}, "FB", {216.300f, 22.000f}, 0, 2.20f, 0x171713, "FFB"},
    {COLOR_A, WK_BIGKNOB, {76.250f, 86.000f}, "COLOR", {76.250f, 96.500f}, 0, 2.20f, 0x171713, "COLOR"},
    {COLOR_B, WK_BIGKNOB, {228.550f, 86.000f}, "COLOR", {228.550f, 96.500f}, 0, 2.20f, 0x171713, "COLOR"},
    {LINK_A, WK_SMKNOB, {101.000f, 30.000f}, "LINK", {101.000f, 38.000f}, 0, 2.20f, 0x171713, "LINK"},
    {LINK_B, WK_SMKNOB, {203.800f, 30.000f}, "LINK", {203.800f, 38.000f}, 0, 2.20f, 0x171713, "LINK"},
    {STAGES_A, WK_SMKNOB, {14.000f, 66.000f}, "BEND", {14.000f, 59.000f}, 0, 1.80f, 0x171713, "BBD Bend"},
    {STAGES_B, WK_SMKNOB, {290.800f, 66.000f}, "BEND", {290.800f, 59.000f}, 0, 1.80f, 0x171713, "BBD Bend"},
    {REC_A, WK_LATCH, {69.500f, 15.000f}, "REC", {69.500f, 21.500f}, 0, 2.20f, 0x171713, "REC"},
    {REC_B, WK_LATCH, {235.300f, 15.000f}, "REC", {235.300f, 21.500f}, 0, 2.20f, 0x171713, "REC"},
    {REV_MIX_A, WK_SMKNOB, {110.000f, 46.000f}, "SEND", {110.000f, 56.500f}, 0, 2.20f, 0x171713, "Room send"},
    {REV_MIX_B, WK_SMKNOB, {194.800f, 46.000f}, "SEND", {194.800f, 56.500f}, 0, 2.20f, 0x171713, "Room send"},
    {SHUFFLE, WK_SMKNOB, {152.400f, 30.000f}, "SHUFL", {152.400f, 38.000f}, 0, 2.20f, 0x171713, "SHUFL"},
};
// 1 = big cap, 0 = small. Parallel to kParamCtls, same order.
// The rehearsal widget reads THIS, not c.kind -- kind says
// bipolar/detented, which is not a diameter.
static const unsigned char kParamSize[] = {
    0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
};
static_assert(sizeof(kParamSize) == sizeof(kParamCtls) / sizeof(kParamCtls[0]), "kParamSize desynced");
static const PanelCtl kInputCtls[] = {
    {IN_L, WK_IN, {112.000f, 107.000f}, "L", {112.000f, 101.000f}, 0, 2.20f, 0x171713, "IN L"},
    {IN_R, WK_IN, {126.000f, 107.000f}, "R", {126.000f, 101.000f}, 0, 2.20f, 0x171713, "IN R"},
    {CLOCK, WK_IN, {140.000f, 107.000f}, "CLK", {140.000f, 101.000f}, 0, 2.20f, 0x171713, "Clock"},
    {RESET, WK_IN, {164.800f, 107.000f}, "RST", {164.800f, 101.000f}, 0, 2.20f, 0x171713, "Reset"},
};
static const PanelCtl kOutputCtls[] = {
    {OUT_L, WK_OUT, {178.800f, 107.000f}, "L", {178.800f, 101.000f}, 0, 2.20f, 0x171713, "OUT L"},
    {OUT_R, WK_OUT, {192.800f, 107.000f}, "R", {192.800f, 101.000f}, 0, 2.20f, 0x171713, "OUT R"},
    {PITCH_A, WK_OUT, {54.000f, 107.000f}, "PIT", {54.000f, 101.000f}, 0, 2.20f, 0x171713, "Pitch A"},
    {GATE_A, WK_OUT, {65.000f, 107.000f}, "GATE", {65.000f, 101.000f}, 0, 2.20f, 0x171713, "Gate A"},
    {PITCH_B, WK_OUT, {250.800f, 107.000f}, "PIT", {250.800f, 101.000f}, 0, 2.20f, 0x171713, "Pitch B"},
    {GATE_B, WK_OUT, {239.800f, 107.000f}, "GATE", {239.800f, 101.000f}, 0, 2.20f, 0x171713, "Gate B"},
};
static const PanelCtl kLightCtls[] = {
    {GATE_A_L, WK_LIGHT, {81.000f, 15.000f}, "", {81.000f, 15.000f}, 0, 2.20f, 0x171713, ""},
    {GATE_B_L, WK_LIGHT, {223.800f, 15.000f}, "", {223.800f, 15.000f}, 0, 2.20f, 0x171713, ""},
    {REC_A_L, WK_LIGHT, {77.000f, 15.000f}, "", {77.000f, 15.000f}, 0, 2.20f, 0x171713, ""},
    {REC_B_L, WK_LIGHT, {227.800f, 15.000f}, "", {227.800f, 15.000f}, 0, 2.20f, 0x171713, ""},
};
// Hardware-only: no VCV id. Rack does not render SVG text,
// so these captions must come from here (spec 2026-08-10 §5).
static const HwOnlyCtl kHwOnlyCtls[] = {
    {WK_LATCH, {140.400f, 15.000f}, "MOD", {140.400f, 21.500f}, 0, 2.20f, 0x171713},
    {WK_LATCH, {164.400f, 15.000f}, "SHIFT", {164.400f, 21.500f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {149.400f, 15.000f}, "", {149.400f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {155.400f, 15.000f}, "", {155.400f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_IN, {23.000f, 107.000f}, "FILT", {23.000f, 101.000f}, 0, 2.20f, 0x171713},
    {WK_IN, {42.500f, 107.000f}, "TIMB", {42.500f, 101.000f}, 0, 2.20f, 0x171713},
    {WK_IN, {76.250f, 107.000f}, "COLOR", {76.250f, 101.000f}, 0, 2.20f, 0x171713},
    {WK_IN, {100.000f, 107.000f}, "LVL", {100.000f, 101.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {45.500f, 15.000f}, "", {45.500f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {49.500f, 15.000f}, "", {49.500f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {53.500f, 15.000f}, "", {53.500f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {57.500f, 15.000f}, "", {57.500f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {61.500f, 15.000f}, "", {61.500f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {85.000f, 15.000f}, "", {85.000f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {89.000f, 15.000f}, "", {89.000f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_IN, {281.800f, 107.000f}, "FILT", {281.800f, 101.000f}, 0, 2.20f, 0x171713},
    {WK_IN, {262.300f, 107.000f}, "TIMB", {262.300f, 101.000f}, 0, 2.20f, 0x171713},
    {WK_IN, {228.550f, 107.000f}, "COLOR", {228.550f, 101.000f}, 0, 2.20f, 0x171713},
    {WK_IN, {204.800f, 107.000f}, "LVL", {204.800f, 101.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {259.300f, 15.000f}, "", {259.300f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {255.300f, 15.000f}, "", {255.300f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {251.300f, 15.000f}, "", {251.300f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {247.300f, 15.000f}, "", {247.300f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {243.300f, 15.000f}, "", {243.300f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {219.800f, 15.000f}, "", {219.800f, 15.000f}, 0, 2.20f, 0x171713},
    {WK_LIGHT, {215.800f, 15.000f}, "", {215.800f, 15.000f}, 0, 2.20f, 0x171713},
};
static const PanelTxt kPanelTexts[] = {
    {{152.400f, 6.000f}, 3.20f, 0.90f, 0x171713, 0, "FIREFLOW HW DRAFT 60HP"},
};
} // namespace spkyhw
