// GENERATED by res/gen_panel.py -- do not edit by hand.
#pragma once

namespace spkyvcv {

static constexpr float kInitParamDefaults[] = {
    0.116716892f, // RATE_A
    0.0f, // SHAPE_A
    0.695181072f, // DENSITY_A
    0.995180666f, // SMOOTH_A
    0.0f, // RANGE_A
    0.0f, // MELODY_A
    0.612047195f, // MOD_A
    0.0f, // TUNE_A
    0.185333401f, // ATTACK_A
    0.322666585f, // DECAY_A
    0.319000006f, // RES_A
    0.458666444f, // SUB_A
    0.438666672f, // SOURCE_A
    0.86400038f, // FLUX_A
    0.0f, // GRIT_A
    0.8f, // COMP_A
    0.0f, // STEPS_A
    0.0f, // ENGINE_A
    6.0f, // SONG_A
    0.202409565f, // RATE_B
    0.899999678f, // SHAPE_B
    0.64457792f, // DENSITY_B
    0.613253355f, // SMOOTH_B
    0.0f, // RANGE_B
    -1.0f, // MELODY_B
    0.35783118f, // MOD_B
    0.0f, // TUNE_B
    0.093333311f, // ATTACK_B
    0.450666398f, // DECAY_B
    0.217333555f, // RES_B
    0.319999605f, // SUB_B
    0.177333504f, // SOURCE_B
    1.0f, // FLUX_B
    0.0f, // GRIT_B
    0.8f, // COMP_B
    0.0f, // STEPS_B
    3.0f, // ENGINE_B
    6.0f, // SONG_B
    0.785541892f, // MORPH
    0.169333577f, // TEMPO
    1.0f, // COUPLE
    5.0f, // SCALE
    0.958666623f, // DRIFT
    0.0f, // SPOT
    0.482666761f, // MASTER_DRIVE
    0.0f, // SETTLE
    0.869332671f, // REV_SIZE
    0.790665507f, // REV_DECAY
    0.761333108f, // REV_TONE
    0.862999976f, // REV_DIFF
    0.484000504f, // REV_SMEAR
    0.237000003f, // REV_MOD
    0.0f, // CHOKE
    -0.172999933f, // FILT_A
    -0.19999963f, // FILT_B
    0.0f, // TIDE
    4.0f, // FLUXRATE_A
    3.0f, // FLUXRATE_B
    0.285667986f, // FLUXFB_A
    0.555337131f, // FLUXFB_B
    0.0f, // COLOR_A
    0.469879329f, // COLOR_B
    0.0f, // LINK_A
    0.0f, // LINK_B
    0.800000012f, // STAGES_A
    1.0f, // STAGES_B
    0.0f, // REC_A
    0.0f, // REC_B
    0.422665179f, // REV_MIX_A
    0.613332987f, // REV_MIX_B
    0.0f, // SHUFFLE
    0.171428576f, // DETUNE_A
    0.171428576f, // DETUNE_B
    0.200000003f, // DRIVE_A
    0.200000003f, // DRIVE_B
};
static_assert(sizeof(kInitParamDefaults) / sizeof(kInitParamDefaults[0])
              == NUM_PARAMS, "init snapshot must cover every ParamId");

inline float initParamDefault(int id) {
    return kInitParamDefaults[id];
}

} // namespace spkyvcv
