// GENERATED by res/gen_panel.py -- do not edit by hand.
#pragma once

namespace spkyvcv {

static constexpr float kInitParamDefaults[] = {
    0.112000011f, // RATE_A
    0.0f, // SHAPE_A
    0.604819179f, // DENSITY_A
    0.0f, // SMOOTH_A
    0.0f, // RANGE_A
    0.0f, // MELODY_A
    0.740963936f, // MOD_A
    0.500000179f, // TUNE_A
    0.685333312f, // ATTACK_A
    0.609333158f, // DECAY_A
    0.0f, // RES_A
    0.711999893f, // SUB_A
    0.0f, // SOURCE_A
    0.0f, // FLUX_A
    0.0f, // GRIT_A
    1.0f, // COMP_A
    0.0f, // STEPS_A
    5.0f, // ENGINE_A
    0.0f, // DETUNE_A
    0.0f, // SONG_A
    0.163855359f, // RATE_B
    0.0f, // SHAPE_B
    0.386746973f, // DENSITY_B
    0.971359313f, // SMOOTH_B
    0.0f, // RANGE_B
    0.671083927f, // MELODY_B
    0.710844219f, // MOD_B
    0.179020017f, // TUNE_B
    1.0f, // ATTACK_B
    1.0f, // DECAY_B
    0.539999962f, // RES_B
    0.0f, // SUB_B
    0.404000044f, // SOURCE_B
    0.650667071f, // FLUX_B
    0.0f, // GRIT_B
    1.0f, // COMP_B
    8.0f, // STEPS_B
    2.0f, // ENGINE_B
    0.455999434f, // DETUNE_B
    0.0f, // SONG_B
    0.384337217f, // MORPH
    0.19733347f, // TEMPO
    1.0f, // COUPLE
    6.0f, // SCALE
    0.0f, // DRIFT
    0.885333359f, // REV_SIZE
    0.785541177f, // REV_DECAY
    1.0f, // REV_TONE
    0.052000195f, // REV_DIFF
    0.0f, // CHOKE
    -0.066666692f, // FILT_A
    -0.06400007f, // FILT_B
    0.0f, // TIDE
    1.0f, // FLUXRATE_A
    1.0f, // FLUXRATE_B
    0.426666766f, // FLUXFB_A
    0.790665507f, // FLUXFB_B
    1.0f, // COLOR_A
    0.687095642f, // COLOR_B
    0.0f, // LINK_A
    0.0f, // LINK_B
    1.0f, // STAGES_A
    0.0f, // STAGES_B
    0.0f, // REC_A
    0.0f, // REC_B
    0.774703741f, // REV_MIX_A
    0.805333197f, // REV_MIX_B
    0.0f, // SHUFFLE
    0.167999804f, // PACE
    0.365333289f, // DEPTH_A
    0.5f, // DEPTH_B
};
static_assert(sizeof(kInitParamDefaults) / sizeof(kInitParamDefaults[0])
              == NUM_PARAMS, "init snapshot must cover every ParamId");

inline float initParamDefault(int id) {
    return kInitParamDefaults[id];
}

} // namespace spkyvcv
