// GENERATED by res/gen_panel.py -- do not edit by hand.
#pragma once

namespace spkyvcv {

static constexpr float kInitParamDefaults[] = {
    0.184337318f, // RATE_A
    0.0f, // SHAPE_A
    0.534939826f, // DENSITY_A
    0.836144507f, // SMOOTH_A
    0.0f, // RANGE_A
    0.768674195f, // MELODY_A
    0.403613269f, // MOD_A
    0.001204819f, // TUNE_A
    1.0f, // ATTACK_A
    1.0f, // DECAY_A
    0.0f, // RES_A
    0.738666236f, // SUB_A
    0.453333825f, // SOURCE_A
    0.353333473f, // FLUX_A
    0.173493922f, // GRIT_A
    0.761333168f, // COMP_A
    0.0f, // STEPS_A
    2.0f, // ENGINE_A
    0.377333373f, // DETUNE_A
    0.0f, // SONG_A
    0.163855359f, // RATE_B
    0.0f, // SHAPE_B
    0.0f, // DENSITY_B
    1.0f, // SMOOTH_B
    0.0f, // RANGE_B
    0.671083927f, // MELODY_B
    0.681928277f, // MOD_B
    0.321686625f, // TUNE_B
    1.0f, // ATTACK_B
    1.0f, // DECAY_B
    0.220000312f, // RES_B
    0.0f, // SUB_B
    0.0f, // SOURCE_B
    0.650667071f, // FLUX_B
    0.0f, // GRIT_B
    0.848000109f, // COMP_B
    0.0f, // STEPS_B
    0.0f, // ENGINE_B
    0.455999434f, // DETUNE_B
    13.0f, // SONG_B
    0.495180398f, // MORPH
    0.0f, // TEMPO
    1.0f, // COUPLE
    3.0f, // SCALE
    0.791999996f, // DRIFT
    1.0f, // REV_SIZE
    0.800755024f, // REV_DECAY
    0.905333221f, // REV_TONE
    0.768000245f, // REV_DIFF
    0.0f, // CHOKE
    -0.199999928f, // FILT_A
    -0.292000026f, // FILT_B
    0.0f, // TIDE
    1.0f, // FLUXRATE_A
    1.0f, // FLUXRATE_B
    0.643999279f, // FLUXFB_A
    0.790665507f, // FLUXFB_B
    0.001204819f, // COLOR_A
    0.862999976f, // COLOR_B
    0.0f, // LINK_A
    0.0f, // LINK_B
    0.0f, // STAGES_A
    0.0f, // STAGES_B
    0.0f, // REC_A
    0.0f, // REC_B
    0.343394309f, // REV_MIX_A
    0.805333197f, // REV_MIX_B
    0.0f, // SHUFFLE
};
static_assert(sizeof(kInitParamDefaults) / sizeof(kInitParamDefaults[0])
              == NUM_PARAMS, "init snapshot must cover every ParamId");

inline float initParamDefault(int id) {
    return kInitParamDefaults[id];
}

} // namespace spkyvcv
