// GENERATED by host/vcv/res/gen_panel.py -- do not edit by hand.
// The parameter space the shared control law speaks (spec
// docs/superpowers/specs/2026-10-09-rev-a-p6b1-shared-control-law-design.md
// section 3.1). Same PARAMS list as host/vcv/src/generated_panel.hpp,
// so every id is numerically VCV's; tests/test_control_params.cpp holds
// the two together.
#pragma once
#include "pitch/quantizer.h"   // SCALE_LIST_COUNT
#include "mod/song_ladder.h"   // kSongLadderCount
#include "mod/divisions.h"     // kFluxRateCount

namespace ffctl {

enum ParamId {
    RATE_A,
    SHAPE_A,
    DENSITY_A,
    SMOOTH_A,
    RANGE_A,
    MELODY_A,
    MOD_A,
    TUNE_A,
    ATTACK_A,
    DECAY_A,
    RES_A,
    SUB_A,
    SOURCE_A,
    FLUX_A,
    GRIT_A,
    COMP_A,
    STEPS_A,
    ENGINE_A,
    DETUNE_A,
    SONG_A,
    RATE_B,
    SHAPE_B,
    DENSITY_B,
    SMOOTH_B,
    RANGE_B,
    MELODY_B,
    MOD_B,
    TUNE_B,
    ATTACK_B,
    DECAY_B,
    RES_B,
    SUB_B,
    SOURCE_B,
    FLUX_B,
    GRIT_B,
    COMP_B,
    STEPS_B,
    ENGINE_B,
    DETUNE_B,
    SONG_B,
    MORPH,
    TEMPO,
    COUPLE,
    SCALE,
    DRIFT,
    REV_SIZE,
    REV_DECAY,
    REV_TONE,
    REV_DIFF,
    CHOKE,
    FILT_A,
    FILT_B,
    TIDE,
    FLUXRATE_A,
    FLUXRATE_B,
    FLUXFB_A,
    FLUXFB_B,
    COLOR_A,
    COLOR_B,
    LINK_A,
    LINK_B,
    STAGES_A,
    STAGES_B,
    REC_A,
    REC_B,
    REV_MIX_A,
    REV_MIX_B,
    SHUFFLE,
    PACE,
    DEPTH_A,
    DEPTH_B,
    PULL,
    PAN_A,
    PAN_B,
    MODBTN,
    MODD_SOURCE_A,
    MODD_SOURCE_B,
    MODD_DEPTH_A,
    MODD_DEPTH_B,
    MODD_FILT_A,
    MODD_FILT_B,
    MODD_FLUX_A,
    MODD_FLUX_B,
    MODD_FLUXFB_A,
    MODD_FLUXFB_B,
    MODD_REV_MIX_A,
    MODD_REV_MIX_B,
    MODD_RATE_A,
    MODD_RATE_B,
    MODD_SHAPE_A,
    MODD_SHAPE_B,
    MODD_DENSITY_A,
    MODD_DENSITY_B,
    MODD_SMOOTH_A,
    MODD_SMOOTH_B,
    MODD_RANGE_A,
    MODD_RANGE_B,
    MODD_MELODY_A,
    MODD_MELODY_B,
    MODD_SUB_A,
    MODD_SUB_B,
    MODD_DETUNE_A,
    MODD_DETUNE_B,
    MODD_ATTACK_A,
    MODD_ATTACK_B,
    MODD_DECAY_A,
    MODD_DECAY_B,
    MODD_RES_A,
    MODD_RES_B,
    MODD_COLOR_A,
    MODD_COLOR_B,
    MODD_TUNE_A,
    MODD_TUNE_B,
    MODD_LINK_A,
    MODD_LINK_B,
    MODD_COMP_A,
    MODD_COMP_B,
    MODD_PAN_A,
    MODD_PAN_B,
    MODD_MORPH,
    MODD_REV_SIZE,
    MODD_REV_DECAY,
    MODD_REV_TONE,
    MODD_REV_DIFF,
    MODD_TIDE,
    NUM_PARAMS
};

static constexpr int PART_STRIDE = 20;

enum ModKind { MODK_TDEPTH = 0, MODK_FXDEPTH = 1, MODK_HOST = 2 };
struct ModTarget { int soundId; int depthId; unsigned char kind; unsigned char slot; unsigned char part; };
static const ModTarget kModLayer[] = {
    {SOURCE_A, MODD_SOURCE_A, 0, 0, 0},
    {SOURCE_B, MODD_SOURCE_B, 0, 0, 1},
    {DEPTH_A, MODD_DEPTH_A, 0, 3, 0},
    {DEPTH_B, MODD_DEPTH_B, 0, 3, 1},
    {FILT_A, MODD_FILT_A, 0, 1, 0},
    {FILT_B, MODD_FILT_B, 0, 1, 1},
    {FLUX_A, MODD_FLUX_A, 1, 2, 0},
    {FLUX_B, MODD_FLUX_B, 1, 2, 1},
    {FLUXFB_A, MODD_FLUXFB_A, 1, 4, 0},
    {FLUXFB_B, MODD_FLUXFB_B, 1, 4, 1},
    {REV_MIX_A, MODD_REV_MIX_A, 1, 3, 0},
    {REV_MIX_B, MODD_REV_MIX_B, 1, 3, 1},
    {RATE_A, MODD_RATE_A, 2, 1, 0},
    {RATE_B, MODD_RATE_B, 2, 1, 1},
    {SHAPE_A, MODD_SHAPE_A, 2, 3, 0},
    {SHAPE_B, MODD_SHAPE_B, 2, 3, 1},
    {DENSITY_A, MODD_DENSITY_A, 2, 3, 0},
    {DENSITY_B, MODD_DENSITY_B, 2, 3, 1},
    {SMOOTH_A, MODD_SMOOTH_A, 2, 1, 0},
    {SMOOTH_B, MODD_SMOOTH_B, 2, 1, 1},
    {RANGE_A, MODD_RANGE_A, 2, 1, 0},
    {RANGE_B, MODD_RANGE_B, 2, 1, 1},
    {MELODY_A, MODD_MELODY_A, 2, 4, 0},
    {MELODY_B, MODD_MELODY_B, 2, 4, 1},
    {SUB_A, MODD_SUB_A, 2, 4, 0},
    {SUB_B, MODD_SUB_B, 2, 4, 1},
    {DETUNE_A, MODD_DETUNE_A, 2, 0, 0},
    {DETUNE_B, MODD_DETUNE_B, 2, 0, 1},
    {ATTACK_A, MODD_ATTACK_A, 2, 3, 0},
    {ATTACK_B, MODD_ATTACK_B, 2, 3, 1},
    {DECAY_A, MODD_DECAY_A, 2, 3, 0},
    {DECAY_B, MODD_DECAY_B, 2, 3, 1},
    {RES_A, MODD_RES_A, 2, 1, 0},
    {RES_B, MODD_RES_B, 2, 1, 1},
    {COLOR_A, MODD_COLOR_A, 2, 3, 0},
    {COLOR_B, MODD_COLOR_B, 2, 3, 1},
    {TUNE_A, MODD_TUNE_A, 2, 2, 0},
    {TUNE_B, MODD_TUNE_B, 2, 2, 1},
    {LINK_A, MODD_LINK_A, 2, 4, 0},
    {LINK_B, MODD_LINK_B, 2, 4, 1},
    {COMP_A, MODD_COMP_A, 2, 4, 0},
    {COMP_B, MODD_COMP_B, 2, 4, 1},
    {PAN_A, MODD_PAN_A, 2, 1, 0},
    {PAN_B, MODD_PAN_B, 2, 1, 1},
    {MORPH, MODD_MORPH, 2, 3, 2},
    {REV_SIZE, MODD_REV_SIZE, 2, 1, 2},
    {REV_DECAY, MODD_REV_DECAY, 2, 1, 2},
    {REV_TONE, MODD_REV_TONE, 2, 1, 2},
    {REV_DIFF, MODD_REV_DIFF, 2, 1, 2},
    {TIDE, MODD_TIDE, 2, 1, 2},
};

static constexpr float kInitParamDefaults[] = {
    0.112000011f, // RATE_A
    0.0f, // SHAPE_A
    0.604819179f, // DENSITY_A
    0.0f, // SMOOTH_A
    0.0f, // RANGE_A
    0.687999368f, // MELODY_A
    0.856628835f, // MOD_A
    0.500000179f, // TUNE_A
    0.685333312f, // ATTACK_A
    0.609333158f, // DECAY_A
    0.0f, // RES_A
    0.209333256f, // SUB_A
    0.0f, // SOURCE_A
    0.0f, // FLUX_A
    0.0f, // GRIT_A
    0.889155984f, // COMP_A
    0.0f, // STEPS_A
    5.0f, // ENGINE_A
    0.0f, // DETUNE_A
    0.0f, // SONG_A
    0.163855359f, // RATE_B
    0.0f, // SHAPE_B
    0.386746973f, // DENSITY_B
    0.971359313f, // SMOOTH_B
    0.0f, // RANGE_B
    0.671083927f, // MELODY_B
    0.710844219f, // MOD_B
    0.174666643f, // TUNE_B
    1.0f, // ATTACK_B
    1.0f, // DECAY_B
    0.539999962f, // RES_B
    0.662666559f, // SUB_B
    0.404000044f, // SOURCE_B
    0.650667071f, // FLUX_B
    0.0f, // GRIT_B
    1.0f, // COMP_B
    8.0f, // STEPS_B
    2.0f, // ENGINE_B
    0.455999434f, // DETUNE_B
    0.0f, // SONG_B
    0.499999762f, // MORPH
    0.19733347f, // TEMPO
    1.0f, // COUPLE
    6.0f, // SCALE
    0.0f, // DRIFT
    0.885333359f, // REV_SIZE
    0.785541177f, // REV_DECAY
    1.0f, // REV_TONE
    0.634667158f, // REV_DIFF
    0.0f, // CHOKE
    -0.302811146f, // FILT_A
    -0.06400007f, // FILT_B
    0.0f, // TIDE
    1.0f, // FLUXRATE_A
    1.0f, // FLUXRATE_B
    0.426666766f, // FLUXFB_A
    0.790665507f, // FLUXFB_B
    1.0f, // COLOR_A
    0.687095642f, // COLOR_B
    0.0f, // LINK_A
    0.0f, // LINK_B
    1.0f, // STAGES_A
    0.0f, // STAGES_B
    0.0f, // REC_A
    0.0f, // REC_B
    0.772287607f, // REV_MIX_A
    0.789153814f, // REV_MIX_B
    0.0f, // SHUFFLE
    0.099999927f, // PACE
    0.365333289f, // DEPTH_A
    0.5f, // DEPTH_B
    0.0f, // PULL
    0.0f, // PAN_A
    0.0f, // PAN_B
    0.0f, // MODBTN
    1.0f, // MODD_SOURCE_A
    1.0f, // MODD_SOURCE_B
    0.712f, // MODD_DEPTH_A
    0.712f, // MODD_DEPTH_B
    0.568f, // MODD_FILT_A
    0.568f, // MODD_FILT_B
    0.0f, // MODD_FLUX_A
    0.0f, // MODD_FLUX_B
    0.0f, // MODD_FLUXFB_A
    0.0f, // MODD_FLUXFB_B
    0.0f, // MODD_REV_MIX_A
    0.0f, // MODD_REV_MIX_B
    0.0f, // MODD_RATE_A
    0.0f, // MODD_RATE_B
    0.0f, // MODD_SHAPE_A
    0.0f, // MODD_SHAPE_B
    0.0f, // MODD_DENSITY_A
    0.0f, // MODD_DENSITY_B
    0.0f, // MODD_SMOOTH_A
    0.0f, // MODD_SMOOTH_B
    0.0f, // MODD_RANGE_A
    0.0f, // MODD_RANGE_B
    0.0f, // MODD_MELODY_A
    0.0f, // MODD_MELODY_B
    0.0f, // MODD_SUB_A
    0.8853333f, // MODD_SUB_B
    0.298666626f, // MODD_DETUNE_A
    0.250666678f, // MODD_DETUNE_B
    0.0f, // MODD_ATTACK_A
    0.0f, // MODD_ATTACK_B
    0.0f, // MODD_DECAY_A
    0.0f, // MODD_DECAY_B
    0.0f, // MODD_RES_A
    0.0f, // MODD_RES_B
    0.0f, // MODD_COLOR_A
    0.0f, // MODD_COLOR_B
    0.0f, // MODD_TUNE_A
    0.0f, // MODD_TUNE_B
    0.0f, // MODD_LINK_A
    0.0f, // MODD_LINK_B
    0.0f, // MODD_COMP_A
    0.0f, // MODD_COMP_B
    0.0f, // MODD_PAN_A
    0.0f, // MODD_PAN_B
    0.279517978f, // MODD_MORPH
    0.0f, // MODD_REV_SIZE
    0.0f, // MODD_REV_DECAY
    0.0f, // MODD_REV_TONE
    0.442666322f, // MODD_REV_DIFF
    0.0f, // MODD_TIDE
};
static_assert(sizeof(kInitParamDefaults) / sizeof(kInitParamDefaults[0]) == NUM_PARAMS,
              "init snapshot must cover every ParamId");

struct ParamRange { float lo, hi; bool snap; };
static constexpr ParamRange kParamRange[] = {
    {0.f, 1.f, false}, // RATE_A
    {0.f, 1.f, false}, // SHAPE_A
    {0.f, 1.f, false}, // DENSITY_A
    {0.f, 1.f, false}, // SMOOTH_A
    {0.f, 1.f, false}, // RANGE_A
    {-1.f, 1.f, false}, // MELODY_A
    {0.f, 1.f, false}, // MOD_A
    {0.f, 1.f, false}, // TUNE_A
    {0.f, 1.f, false}, // ATTACK_A
    {0.f, 1.f, false}, // DECAY_A
    {0.f, 1.f, false}, // RES_A
    {0.f, 1.f, false}, // SUB_A
    {0.f, 1.f, false}, // SOURCE_A
    {0.f, 1.f, false}, // FLUX_A
    {-1.f, 1.f, false}, // GRIT_A
    {0.f, 1.f, false}, // COMP_A
    {0.f, 16.f, true}, // STEPS_A
    {0.f, 5.f, true}, // ENGINE_A
    {0.f, 1.f, false}, // DETUNE_A
    {0.f, float(spky::kSongLadderCount - 1), true}, // SONG_A
    {0.f, 1.f, false}, // RATE_B
    {0.f, 1.f, false}, // SHAPE_B
    {0.f, 1.f, false}, // DENSITY_B
    {0.f, 1.f, false}, // SMOOTH_B
    {0.f, 1.f, false}, // RANGE_B
    {-1.f, 1.f, false}, // MELODY_B
    {0.f, 1.f, false}, // MOD_B
    {0.f, 1.f, false}, // TUNE_B
    {0.f, 1.f, false}, // ATTACK_B
    {0.f, 1.f, false}, // DECAY_B
    {0.f, 1.f, false}, // RES_B
    {0.f, 1.f, false}, // SUB_B
    {0.f, 1.f, false}, // SOURCE_B
    {0.f, 1.f, false}, // FLUX_B
    {-1.f, 1.f, false}, // GRIT_B
    {0.f, 1.f, false}, // COMP_B
    {0.f, 16.f, true}, // STEPS_B
    {0.f, 5.f, true}, // ENGINE_B
    {0.f, 1.f, false}, // DETUNE_B
    {0.f, float(spky::kSongLadderCount - 1), true}, // SONG_B
    {0.f, 1.f, false}, // MORPH
    {0.f, 1.f, false}, // TEMPO
    {0.f, 1.f, false}, // COUPLE
    {0.f, float(spky::SCALE_LIST_COUNT - 1), true}, // SCALE
    {0.f, 1.f, false}, // DRIFT
    {0.f, 1.f, false}, // REV_SIZE
    {0.f, 1.f, false}, // REV_DECAY
    {0.f, 1.f, false}, // REV_TONE
    {0.f, 1.f, false}, // REV_DIFF
    {-1.f, 1.f, false}, // CHOKE
    {-1.f, 1.f, false}, // FILT_A
    {-1.f, 1.f, false}, // FILT_B
    {0.f, 1.f, false}, // TIDE
    {0.f, float(spky::kFluxRateCount - 1), true}, // FLUXRATE_A
    {0.f, float(spky::kFluxRateCount - 1), true}, // FLUXRATE_B
    {0.f, 1.f, false}, // FLUXFB_A
    {0.f, 1.f, false}, // FLUXFB_B
    {0.f, 1.f, false}, // COLOR_A
    {0.f, 1.f, false}, // COLOR_B
    {0.f, 1.f, false}, // LINK_A
    {0.f, 1.f, false}, // LINK_B
    {0.f, 1.f, false}, // STAGES_A
    {0.f, 1.f, false}, // STAGES_B
    {0.f, 1.f, true}, // REC_A
    {0.f, 1.f, true}, // REC_B
    {0.f, 1.f, false}, // REV_MIX_A
    {0.f, 1.f, false}, // REV_MIX_B
    {0.f, 1.f, false}, // SHUFFLE
    {0.f, 1.f, false}, // PACE
    {0.f, 1.f, false}, // DEPTH_A
    {0.f, 1.f, false}, // DEPTH_B
    {-1.f, 1.f, false}, // PULL
    {-1.f, 1.f, false}, // PAN_A
    {-1.f, 1.f, false}, // PAN_B
    {0.f, 1.f, true}, // MODBTN
    {-1.f, 1.f, false}, // MODD_SOURCE_A
    {-1.f, 1.f, false}, // MODD_SOURCE_B
    {-1.f, 1.f, false}, // MODD_DEPTH_A
    {-1.f, 1.f, false}, // MODD_DEPTH_B
    {-1.f, 1.f, false}, // MODD_FILT_A
    {-1.f, 1.f, false}, // MODD_FILT_B
    {-1.f, 1.f, false}, // MODD_FLUX_A
    {-1.f, 1.f, false}, // MODD_FLUX_B
    {-1.f, 1.f, false}, // MODD_FLUXFB_A
    {-1.f, 1.f, false}, // MODD_FLUXFB_B
    {-1.f, 1.f, false}, // MODD_REV_MIX_A
    {-1.f, 1.f, false}, // MODD_REV_MIX_B
    {-1.f, 1.f, false}, // MODD_RATE_A
    {-1.f, 1.f, false}, // MODD_RATE_B
    {-1.f, 1.f, false}, // MODD_SHAPE_A
    {-1.f, 1.f, false}, // MODD_SHAPE_B
    {-1.f, 1.f, false}, // MODD_DENSITY_A
    {-1.f, 1.f, false}, // MODD_DENSITY_B
    {-1.f, 1.f, false}, // MODD_SMOOTH_A
    {-1.f, 1.f, false}, // MODD_SMOOTH_B
    {-1.f, 1.f, false}, // MODD_RANGE_A
    {-1.f, 1.f, false}, // MODD_RANGE_B
    {-1.f, 1.f, false}, // MODD_MELODY_A
    {-1.f, 1.f, false}, // MODD_MELODY_B
    {-1.f, 1.f, false}, // MODD_SUB_A
    {-1.f, 1.f, false}, // MODD_SUB_B
    {-1.f, 1.f, false}, // MODD_DETUNE_A
    {-1.f, 1.f, false}, // MODD_DETUNE_B
    {-1.f, 1.f, false}, // MODD_ATTACK_A
    {-1.f, 1.f, false}, // MODD_ATTACK_B
    {-1.f, 1.f, false}, // MODD_DECAY_A
    {-1.f, 1.f, false}, // MODD_DECAY_B
    {-1.f, 1.f, false}, // MODD_RES_A
    {-1.f, 1.f, false}, // MODD_RES_B
    {-1.f, 1.f, false}, // MODD_COLOR_A
    {-1.f, 1.f, false}, // MODD_COLOR_B
    {-1.f, 1.f, false}, // MODD_TUNE_A
    {-1.f, 1.f, false}, // MODD_TUNE_B
    {-1.f, 1.f, false}, // MODD_LINK_A
    {-1.f, 1.f, false}, // MODD_LINK_B
    {-1.f, 1.f, false}, // MODD_COMP_A
    {-1.f, 1.f, false}, // MODD_COMP_B
    {-1.f, 1.f, false}, // MODD_PAN_A
    {-1.f, 1.f, false}, // MODD_PAN_B
    {-1.f, 1.f, false}, // MODD_MORPH
    {-1.f, 1.f, false}, // MODD_REV_SIZE
    {-1.f, 1.f, false}, // MODD_REV_DECAY
    {-1.f, 1.f, false}, // MODD_REV_TONE
    {-1.f, 1.f, false}, // MODD_REV_DIFF
    {-1.f, 1.f, false}, // MODD_TIDE
};
static_assert(sizeof(kParamRange) / sizeof(kParamRange[0]) == NUM_PARAMS,
              "range table must cover every ParamId");

} // namespace ffctl
