#!/usr/bin/env python3
"""Emit coupon.kicad_sch from netlist.build().

Emit coupon.kicad_sch from netlist.build() through the shared writer
(hardware/gen/sch_writer.py), which carries the style notes. Running this
regenerates the committed schematic -- do so only on purpose.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..")))
import netlist as N                           # noqa: E402
from gen import sch_writer as W               # noqa: E402  (P3 spec §3.1)
from gen.project import Project, Sheet        # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.normpath(os.path.join(HERE, ".."))
SCH_PATH = os.path.join(OUT_DIR, "coupon.kicad_sch")
PAPER = "A2"


def project():
    return Project("coupon", "FireFlow test coupon",
                   [Sheet("coupon", "all", N.build())], paper=PAPER, flat=True,
                   comments=["GENERATED by hardware/gen/sch_writer.py via "
                             "hardware/coupon/scripts/generate_schematic.py "
                             "-- do not edit by hand",
                             "Source of truth: scripts/design.py and scripts/netlist.py"])


def layout(parts):
    return W.layout(parts, PAPER, {})


def overlaps(parts, placed):
    return W.overlaps(parts, placed, {})


def main(out_dir=OUT_DIR):
    layouts = W.write_project(project(), out_dir)
    _placed, needed_h = layouts["coupon"]
    if not W.fits(needed_h, PAPER):
        print("note: content is %.0f mm tall -- widen or split" % needed_h)
    print("wrote %s (%.0f mm of content)"
          % (os.path.relpath(os.path.join(out_dir, "coupon.kicad_sch")), needed_h))


if __name__ == "__main__":
    main()
