#!/usr/bin/env python3
"""Write proof/review.md -- the sheet a human actually reviews.

The schematic PDF answers "does this look like a circuit". It is the wrong
instrument for the two questions that matter here: is the channel plan right,
and is the one connection that came from convention rather than a datasheet
right. Both are tables, and a table is not easier to read as an A2 drawing.

It also checks design.REQUIREMENTS against what netlist.build() actually
creates: the requirement list names parts by reference, and a name that no part
answers to is a requirement nothing serves.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import design as D
import netlist as N

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "proof", "review.md"))


def requirement_rows(parts):
    refs = {p.ref for p in parts}
    rows, missing = [], []
    for num in sorted(D.REQUIREMENTS):
        text, named = D.REQUIREMENTS[num]
        gone = [r for r in named if r not in refs]
        missing.extend((num, r) for r in gone)
        mark = "yes" if not gone else "**NO: %s**" % ", ".join(gone)
        rows.append((num, text, ", ".join(named), mark))
    return rows, missing


def channel_rows(parts):
    """What each mux channel actually carries, read back from the netlist."""
    nets = N.nets_from(parts)
    out = []
    for prefix, plan in (("MUX16", D.MUX16_CHANNELS), ("MUX8", D.MUX8_CHANNELS)):
        for idx, intent in plan:
            net = "%s_CH%d" % (prefix, idx)
            nodes = sorted(r for r, _pin in nets.get(net, []))
            wired = [r for r in nodes if not r.startswith("U_MUX")]
            out.append((prefix, idx, intent, ", ".join(wired) or "NOTHING"))
    return out


def main():
    parts = N.build()
    by_ref = {p.ref: p for p in parts}
    reqs, missing = requirement_rows(parts)
    lines = []
    add = lines.append

    add("# Coupon review sheet")
    add("")
    add("Generated by `scripts/review.py`. Read this instead of the schematic "
        "PDF for anything that is a table; the PDF is for whether the drawing "
        "looks like a circuit at all.")
    add("")
    add("## 1. The eight requirements, and the parts that serve them")
    add("")
    add("Envelope spec section 5, addendum 2026-08-30. The last column is "
        "checked against what `netlist.build()` really creates.")
    add("")
    add("| # | requirement | parts | present |")
    add("|---|---|---|---|")
    for num, text, named, mark in reqs:
        add("| %d | %s | `%s` | %s |" % (num, text, named, mark))
    add("")
    if missing:
        add("**%d named part(s) do not exist.** That is a requirement with "
            "nothing behind it, not a typo to wave through:" % len(missing))
        for num, ref in missing:
            add("- point %d names `%s`" % (num, ref))
        add("")

    add("## 2. Channel plan, read back from the netlist")
    add("")
    add("`intent` is the line in `design.py`; `wired` is what the netlist "
        "actually puts on that channel. They have to agree.")
    add("")
    add("| mux | ch | intent | wired |")
    add("|---|---:|---|---|")
    for prefix, idx, intent, wired in channel_rows(parts):
        add("| %s | %d | %s | `%s` |" % (prefix, idx, intent, wired))
    add("")

    add("## 3. The Eurorack connector -- the one thing here that is NOT from "
        "a datasheet")
    add("")
    add("Everything else in this schematic came out of the Patch SM datasheet "
        "or a KiCad symbol. This is convention, taken on trust, and it is the "
        "single most likely thing to be wrong. Pins 7 and 8 are deliberately "
        "left open rather than grounded, because some bus boards carry +5 V "
        "there and grounding it would be a short.")
    add("")
    add("| pin | net |")
    add("|---:|---|")
    pwr = by_ref["J_PWR"]
    for pin in sorted(pwr.sym.pins, key=int):
        add("| %s | %s |" % (pin, pwr.nets.get(pin, "*left open*")))
    add("")

    add("## 4. Bill of materials")
    add("")
    groups = {}
    for p in parts:
        if p.ref.startswith("#"):
            continue
        groups.setdefault((p.value, p.footprint), []).append(p.ref)
    add("| qty | value | refs | footprint |")
    add("|---:|---|---|---|")
    for (value, fp), refs in sorted(groups.items(), key=lambda kv: -len(kv[1])):
        add("| %d | %s | %s | %s |"
            % (len(refs), value, ", ".join(sorted(refs)),
               "`%s`" % fp if fp else "*BOM only, no own footprint*"))
    add("")

    add("## 5. Known ERC violations, and why they stay")
    add("")
    add("All three come from the vendored Patch SM symbol naming pins after "
        "their default peripheral while the coupon uses them for something "
        "else -- the trap recorded in `hardware/lib/README.md`. Fixing them "
        "would mean editing a vendored symbol, which would break its "
        "provenance for a cosmetic gain.")
    add("")
    add("- `U_SR1.SER` reported as not driven: `B7` is `I2C1_SCL` in the "
        "symbol, not declared an output.")
    add("- `U_IN1.Q7` against `U_SM.D10`: two outputs connected, because "
        "`D10` is `SPI_SCK` in the symbol while the coupon reads it as the "
        "chain's data input.")
    add("- `lib_symbol_mismatch` on the 165: the embedded copy has its unit "
        "sub-symbols renamed from `74LS165_*` to `74HC165_*`, which is what "
        "makes a derived symbol loadable at all.")
    add("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s" % os.path.relpath(OUT))
    if missing:
        print("REQUIREMENTS name %d part(s) that do not exist" % len(missing))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
