#pragma once
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include "util/fast_tanh.h"
#include "util/math.h"

// Bucket-brigade delay: the Holters/Parker combined model of a BBD and its
// input/output filters (DAFx-18), with the NE570 compander and the drive path
// of an Electro-Harmonix Deluxe Memory Man around it.
//
// Derived from jpcima/bbd-delay-experimental (bbd_line, bbd_filter), used
// under the Boost Software License 1.0:
//
//   Boost Software License - Version 1.0 - August 17th, 2003
//
//   Permission is hereby granted, free of charge, to any person or
//   organization obtaining a copy of the software and accompanying
//   documentation covered by this license (the "Software") to use, reproduce,
//   display, distribute, execute, and transmit the Software, and to prepare
//   derivative works of the Software, and to permit third-parties to whom the
//   Software is furnished to do so, all subject to the following:
//
//   The copyright notices in the Software and this entire statement,
//   including the above license grant, this restriction and the following
//   disclaimer, must be included in all copies of the Software, in whole or
//   in part, and all derivative works of the Software, unless such copies or
//   derivative works are solely in the form of machine-executable object code
//   generated by a source language processor.
//
//   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
//   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
//   NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
//   DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,
//   WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
//   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//   SOFTWARE.
//
// Deviations from the reference, all deliberate: float instead of double, a
// local Cf instead of std::complex, injected memory instead of std::vector /
// unique_ptr, one init-time filter build instead of a mutex-guarded cache,
// our own filter chain (the DMM's ~3.6 kHz, not the Juno-60's ~7-10 kHz), and
// a charge-transfer loss pole the reference does not model at all.

namespace spky {

// Minimal complex float. std::complex<float> would do the same job, but it
// drags <complex> into every translation unit that includes this header and
// its operator* is not guaranteed to avoid the NaN-safe slow path on every
// toolchain. Six lines here, no surprises on the M7.
struct Cf {
    float re = 0.f;
    float im = 0.f;
};

inline Cf cf_add(Cf a, Cf b) { return Cf{ a.re + b.re, a.im + b.im }; }
inline Cf cf_scale(Cf a, float s) { return Cf{ a.re * s, a.im * s }; }
inline Cf cf_mul(Cf a, Cf b) {
    return Cf{ a.re * b.re - a.im * b.im, a.re * b.im + a.im * b.re };
}
inline Cf cf_div(Cf a, Cf b) {
    const float d = b.re * b.re + b.im * b.im;
    const float inv = (d != 0.f) ? 1.f / d : 0.f;
    return Cf{ (a.re * b.re + a.im * b.im) * inv,
               (a.im * b.re - a.re * b.im) * inv };
}
// INIT TIME ONLY -- std::exp/cos/sin. The only cf_* helper that touches libm;
// the other five are arithmetic-only. Reached from bbd_analog_spec() (pole/
// residue construction) and BbdFilterCoef building, both init-time paths --
// never call this from a per-sample path.
inline Cf cf_exp(Cf a) {
    const float m = std::exp(a.re);
    return Cf{ m * std::cos(a.im), m * std::sin(a.im) };
}

namespace bbd_tuning {

// --- the clock law ---------------------------------------------------------
// f_clk = stages / (2 * t_d), clamped. The ceiling is physical, not
// arbitrary: the fixed post-BBD filter chain sits at kFilterHz and the clock
// never overtakes it, so BBD bandwidth past kClockMaxHz/4 = 8 kHz is
// inaudible by construction. It also bounds the tick rate at
// 2 * 32000 / 48000 = 1.33 per sample, which is what makes the budget
// computable. There is deliberately NO floor.
constexpr float kClockMaxHz = 32000.f;

// --- stages ----------------------------------------------------------------
// Geometric, five octaves. 8192 is the DMM (2x MN3005 at 4096 stages each);
// the rest of the scale is a chip no pedal exposes.
constexpr int kMinStages = 512;
constexpr int kMaxStages = 16384;

// --- the fixed filter chain ------------------------------------------------
// The real device's chain is roughly six poles around 3.5-4 kHz and does NOT
// move with the clock. Modelled as two 3rd-order Butterworth sections, one
// before the line and one after: six poles, one corner, analytic residues.
// Ear-tunable (spec: the filters are the device's character, not a setting).
constexpr float kFilterHz  = 3600.f;
constexpr int   kFiltOrder = 3;

// Rows in the G interpolation table. The tick's sub-sample position d lands
// between two rows and is lerped. 65 rows over exp(p*ts*d), |p*ts| <= 0.48 at
// 48 kHz, gives a relative error below 1e-5 -- far under the model's own
// error. The table is fs-dependent only, and shared by both lines.
constexpr int kInterpSteps = 65;

// --- charge-transfer loss --------------------------------------------------
// Bandwidth follows the clock: f_-3dB ~ f_clk / 4 over 8192 stages. One
// one-pole INSIDE the clocked domain (i.e. running at the line's own sample
// rate, f_clk) with a fixed normalised corner of 1/4 tracks the clock for
// free -- no coefficient recompute when the clock moves, and the corner is
// correct at every clock by construction.
//
// For y[n] = y[n-1] + a*(x - y[n-1]) with b = 1-a, half power at w = pi/2
// requires 1 + b^2 = 2*(1-b)^2, i.e. b = 2 - sqrt(3). So a = sqrt(3) - 1.
constexpr float kLossCoef = 0.7320508f;   // sqrt(3) - 1

// --- the NE570 compander ---------------------------------------------------
// 2:1 in, 1:2 out, tau = 10 kOhm * 1 uF. Not a parameter: it is the device's
// character, and "compression" is already spoken for by COMP on the panel.
constexpr float kCompTauS = 0.010f;
constexpr float kCompRef  = 0.1f;         // -20 dBFS reference level
// Envelope floors/ceilings that bound the compander's gain to [1/4, 4] in
// each direction. Derived, not tasted: the compressor's gain is
// sqrt(kCompRef/e), so e >= kCompRef/16 caps it at 4; the expander's gain is
// e/kCompRef, so e in [kCompRef/4, 4*kCompRef] caps it at 4 either way.
constexpr float kCompFloorC = kCompRef / 16.f;
constexpr float kCompFloorE = kCompRef / 4.f;
constexpr float kCompCeilE  = kCompRef * 4.f;

// --- drive -----------------------------------------------------------------
// DRIVE sits INSIDE the loop, so every repeat saturates again. The threshold
// is fixed at the MN3005's 0.9 V_RMS ceiling (kSatCeil) and stays fixed
// regardless of DRIVE -- see BbdEcho::SetDrive for why. DRIVE only moves the
// SIGNAL against that fixed ceiling (kDriveLoDb..kDriveHiDb, into sat_in_).
//
// This pair was revised once already, by measurement, after the fixed
// ceiling first shipped at -6..+24 dB (the range inherited from the old
// makeup-gain law, never itself re-examined): that range made small-signal
// loop gain equal `g` directly (BbdEcho::SetDrive), and Flux::set_feedback's
// existing "up to 1.2x" ceiling collided with it two different ways at the
// two ends of the knob. At DRIVE 0, g(-6dB) = 0.501 pushed the self-
// oscillation FEEDBACK threshold up to ~1.71 -- ABOVE the panel's 1.2
// maximum, so self-oscillation became unreachable at DRIVE 0, violating the
// design's own "self-oscillation must stay reachable" constraint. At DRIVE 1,
// g(+24dB) = 15.85 dragged the threshold down to ~0.05 -- FEEDBACK bloomed at
// almost any setting, a hair-trigger rather than a knob.
//
// 0..+12 dB was chosen from a measured bracket (0..+9, +12, +15, +18 dB, and
// negative-floor variants down to -3 dB -- see
// .superpowers/sdd/2026-07-27-flux-bbd-delay/drive-fix-report.md, "DRIVE
// range follow-up"). A negative floor was ruled out first: any floor below 0
// pushes the DRIVE-0 threshold to within a hair of 1.2 (measured 1.19 at
// -3 dB), which is "reachable" in name only. Among 0-floor candidates, +12
// keeps DRIVE 0's threshold comfortably clear of the 1.2 ceiling (measured
// 0.84, ~30% of headroom to spare) while leaving DRIVE 1 a real span of
// non-oscillating FEEDBACK travel before it blooms (measured 0.21, roughly
// 4x the ~0.05 the old range left) -- +9 protects FEEDBACK's travel even
// more but never gets DRIVE's own distortion above ~4% THD anywhere on the
// knob, which reproduces the original "DRIVE does nothing" complaint by a
// different route; +15/+18 push the dirt earlier into the knob's travel but
// tighten FEEDBACK's headroom back down toward the hair-trigger this
// revision exists to fix.
//
// NOTE for whoever revisits this: the constraint that picked +12 no longer
// binds. Every argument above trades DRIVE's dirt against FEEDBACK's travel,
// because at the time the two were coupled. Flux::set_feedback now divides
// bbd_drive_gain() out, so the bloom point sits at the same knob position at
// every DRIVE (measured: 0.57 -> 0.56 across the range) and the range is free
// to be chosen for distortion character alone. Raising kDriveHiDb is now the
// cheap lever if DRIVE is ever judged too tame; it costs FEEDBACK nothing.
constexpr float kSatCeil   = 0.9f;
constexpr float kDriveLoDb = 0.f;
constexpr float kDriveHiDb = 12.f;

}  // namespace bbd_tuning

// The DRIVE knob's 0..1 mapped to its linear gain. Both consumers go through
// here rather than open-coding the pow: BbdEcho::SetDrive pushes it into the
// saturator, and Flux::set_feedback divides it back out of the feedback
// coefficient. If those two ever disagreed about the law -- which they would
// the first time kDriveLoDb/kDriveHiDb moved, and that pair has moved once
// already -- DRIVE would silently start dragging FEEDBACK's bloom point again,
// which is the exact defect the division exists to prevent.
inline float bbd_drive_gain(float norm) {
    const float n = clampf(norm, 0.f, 1.f);
    const float db = bbd_tuning::kDriveLoDb
                   + n * (bbd_tuning::kDriveHiDb - bbd_tuning::kDriveLoDb);
    return std::pow(10.f, db * 0.05f);
}

// The one formula. Pure, stateless, separately tested. Everything else in
// this file trusts it.
//
// A non-finite or non-positive delay returns the ceiling rather than an
// infinity: BbdLine must never see a clock it cannot count ticks from, and a
// silent, very short delay is a far better failure than a NaN in the line.
inline float bbd_clock_hz(float delay_seconds, int stages) {
    if (!(delay_seconds > 0.f) || !std::isfinite(delay_seconds))
        return bbd_tuning::kClockMaxHz;
    const float hz = static_cast<float>(stages) / (2.f * delay_seconds);
    return hz < bbd_tuning::kClockMaxHz ? hz : bbd_tuning::kClockMaxHz;
}

// FXT_FLUX_TIME's geometric depth map: 0 -> x1/4, 0.5 -> x1, 1 -> x4. Since
// pitch tracks the clock ratio directly, that is +-2 octaves at full depth --
// the original's +-10 % clock swing (+-1.65 semitones) lands in the bottom
// tenth of the control. The historical device is the start of the scale, not
// the target.
//
// A LUT, not powf: this is evaluated once per sample per part. 65 rows over
// four octaves with linear interpolation gives a worst-case error of 2.3e-4
// relative, i.e. 0.4 cents -- inaudible on a modulation depth control.
inline float bbd_time_mult(float norm) {
    static const std::array<float, 65> table = [] {
        std::array<float, 65> t{};
        for (size_t i = 0; i < t.size(); ++i) {
            const float n = static_cast<float>(i) / static_cast<float>(t.size() - 1);
            t[i] = std::pow(2.f, 4.f * (n - 0.5f));
        }
        return t;
    }();
    const float p = clampf(norm, 0.f, 1.f) * 64.f;
    int i = static_cast<int>(p);
    if (i > 64) i = 64;
    const int j = (i < 64) ? i + 1 : 64;
    return table[i] + (table[j] - table[i]) * (p - static_cast<float>(i));
}

// Discretised filter, one per direction, shared by every BbdLine at a given
// sample rate.
//
//   P[m] = exp(ts * p_m)                          per-sample pole advance
//   G[step][m]                                    the tick's sub-sample
//     input  kind: ts * R[m] * P[m]^d               position d, tabulated
//     output kind: (R[m] / p_m) * P[m]^(1-d)        and lerped in the hot path
//   H = sum(-R[m] / p_m)                          output DC feed-through
//
// The G table is why there is no powf/cosf per event: the reference's own
// suggestion, and the desktop build profits from it too.
struct BbdFilterCoef {
    Cf    G[bbd_tuning::kInterpSteps][bbd_tuning::kFiltOrder];
    Cf    P[bbd_tuning::kFiltOrder];
    float H = 0.f;

    void interpolate_g(float d, Cf* g) const {
        float row = d * static_cast<float>(bbd_tuning::kInterpSteps - 1);
        if (!(row > 0.f)) row = 0.f;                    // also catches NaN
        int r1 = static_cast<int>(row);
        if (r1 > bbd_tuning::kInterpSteps - 1) r1 = bbd_tuning::kInterpSteps - 1;
        const int r2 = (r1 + 1 < bbd_tuning::kInterpSteps) ? r1 + 1 : r1;
        const float mu = row - static_cast<float>(r1);
        for (int m = 0; m < bbd_tuning::kFiltOrder; ++m) {
            g[m].re = G[r1][m].re + (G[r2][m].re - G[r1][m].re) * mu;
            g[m].im = G[r1][m].im + (G[r2][m].im - G[r1][m].im) * mu;
        }
    }
};

// The analog specification: kFiltOrder Butterworth poles at kFilterHz and
// their partial-fraction residues for H(s) = prod(-p_j) / prod(s - p_j).
// Both directions currently share the same prototype; the flag is kept
// because the DISCRETISATION differs (see BbdFilterCoef) and because giving
// the two chains different corners later must not need a signature change.
void bbd_analog_spec(bool output_kind, Cf* poles, Cf* residues);

// Shared, built on first call and rebuilt IN PLACE if the sample rate moves.
// This is NOT the same contract as hann_curve() (fx/fx_util.h): that table is
// a magic static, built exactly once behind the standard's thread-safe
// function-local-static init guarantee, and never mutated again -- there is
// nothing for two threads to race on after the first call. bbd_filter_in/out
// are different: on a sample-rate change they mutate g_fin/g_fout's contents
// in place, while OTHER BbdLines already hold raw pointers into them (fin_/
// fout_, set in BbdLine::Init) -- a genuine shared-mutable-state hazard the
// language's static-init guarantee does not cover. It is safe here only
// because both hosts call Flux::init from one thread with the audio callback
// stopped (Rack's onSampleRateChange, the render host's setup), so no BbdLine
// is ever reading through fin_/fout_ while this rebuild runs.
const BbdFilterCoef& bbd_filter_in(float sample_rate);
const BbdFilterCoef& bbd_filter_out(float sample_rate);

// An N-cell bucket-brigade line over injected memory, driven by a clock
// frequency. It has NO read pointer: all charge packets are clocked forward
// together, and the delay is a consequence of the clock, not of an index.
//
// Even ticks WRITE one cell, odd ticks READ one cell -- that alternation is
// the two-phase clock of the physical part, and it is why the cell count is
// half the stage count and why the tick rate is twice f_clk:
//
//     ticks/sample = 2 * f_clk / fs
//     cells        = stages / 2
//     delay        = 2 * cells / tick_rate = stages / (2 * f_clk)
//
// It knows nothing about music -- no BPM, no divisions, no feedback.
class BbdLine {
public:
    BbdLine() = default;
    BbdLine(const BbdLine&) = delete;
    BbdLine& operator=(const BbdLine&) = delete;

    // `buf` holds max_cells floats and is owned by the host (FxMem).
    void Init(float* buf, size_t max_cells, float sample_rate) {
        mem_ = buf;
        max_cells_ = max_cells;
        sr_ = (sample_rate > 0.f) ? sample_rate : 48000.f;
        fin_ = &bbd_filter_in(sr_);
        fout_ = &bbd_filter_out(sr_);
        cells_ = static_cast<int>(max_cells_ > 0 ? max_cells_ : 1);
        Reset();
    }

    void Reset() {
        if (mem_ && max_cells_) std::memset(mem_, 0, max_cells_ * sizeof(float));
        imem_ = 0;
        pclk_ = 0.f;
        ptick_ = 0;
        ybbd_old_ = 0.f;
        loss_z_ = 0.f;
        for (int m = 0; m < bbd_tuning::kFiltOrder; ++m) {
            Xin_[m] = Cf{};
            Xout_mem_[m] = Cf{};
        }
    }

    // The BBD clock in Hz. Non-finite or non-positive means "hold": no ticks,
    // no division by the clock, the output filter simply coasts.
    void SetClock(float hz) {
        ticks_ = (hz > 0.f && std::isfinite(hz)) ? (2.f * hz / sr_) : 0.f;
    }

    // Physical stage count. The cell array is half of it; content is
    // deliberately NOT cleared, so a stage change drifts in time and pitch
    // instead of clicking.
    void SetStages(int stages) {
        int c = stages / 2;
        const int lo = bbd_tuning::kMinStages / 2;
        const int hi = static_cast<int>(max_cells_);
        if (c < lo) c = lo;
        if (c > hi) c = hi;
        if (c < 1) c = 1;
        if (c == cells_) return;
        cells_ = c;
        if (imem_ >= cells_) imem_ = 0;
    }

    int cells() const { return cells_; }

    float Process(float in) {
        Cf Xout[bbd_tuning::kFiltOrder] = {};

        const float fclk = ticks_;
        // mem_ can be null with cells_ still nonzero -- Init(nullptr, 0, sr)
        // leaves cells_ at 1 (its floor), and SetStages's own floor does the
        // same. No tick may run while the line has no usable memory.
        if (fclk > 0.f && mem_) {
            const float pclk_old = pclk_;
            const float p = pclk_ + fclk;
            const int tick_count = static_cast<int>(p);
            pclk_ = p - static_cast<float>(tick_count);
            const float inv = 1.f / fclk;
            Cf g[bbd_tuning::kFiltOrder];
            for (int t = 0; t < tick_count; ++t) {
                // The tick's position inside this audio sample, in [0, 1).
                float d = (1.f - pclk_old + static_cast<float>(t)) * inv;
                d -= static_cast<float>(static_cast<int>(d));
                if ((ptick_ & 1u) == 0u) {
                    // WRITE phase: sample the input filter at d and push one
                    // charge packet, after the charge-transfer loss.
                    fin_->interpolate_g(d, g);
                    float s = 0.f;
                    for (int m = 0; m < bbd_tuning::kFiltOrder; ++m)
                        s += g[m].re * Xin_[m].re - g[m].im * Xin_[m].im;
                    loss_z_ += bbd_tuning::kLossCoef * (s - loss_z_);
                    mem_[imem_] = loss_z_;
                    imem_ = (imem_ + 1 < cells_) ? imem_ + 1 : 0;
                } else {
                    // READ phase: imem_ points at the oldest cell. The output
                    // filter is driven by the STEP between consecutive
                    // readings, which is what makes the staircase exact.
                    fout_->interpolate_g(d, g);
                    const float ybbd = mem_[imem_];
                    const float delta = ybbd - ybbd_old_;
                    ybbd_old_ = ybbd;
                    for (int m = 0; m < bbd_tuning::kFiltOrder; ++m)
                        Xout[m] = cf_add(Xout[m], cf_scale(g[m], delta));
                }
                ++ptick_;
            }
        }

        // Input filter states advance by exactly one audio sample, always --
        // whether or not a tick happened. This is the continuous-time part of
        // the model and it must not be inside the tick loop.
        for (int m = 0; m < bbd_tuning::kFiltOrder; ++m) {
            const Cf p = fin_->P[m];
            const Cf x = Xin_[m];
            Xin_[m] = Cf{ x.re * p.re - x.im * p.im + in,
                          x.re * p.im + x.im * p.re };
        }

        float y = fout_->H * ybbd_old_;
        for (int m = 0; m < bbd_tuning::kFiltOrder; ++m) {
            const Cf x = cf_add(cf_mul(fout_->P[m], Xout_mem_[m]), Xout[m]);
            Xout_mem_[m] = x;
            y += x.re;
        }
        return y;
    }

private:
    const BbdFilterCoef* fin_ = nullptr;
    const BbdFilterCoef* fout_ = nullptr;
    float*   mem_ = nullptr;
    size_t   max_cells_ = 0;
    int      cells_ = 1;
    int      imem_ = 0;
    float    sr_ = 48000.f;
    float    ticks_ = 0.f;      // ticks per audio sample = 2*f_clk/fs
    float    pclk_ = 0.f;       // fractional tick phase carried between samples
    uint32_t ptick_ = 0;        // parity picks write vs read
    float    ybbd_old_ = 0.f;
    float    loss_z_ = 0.f;     // charge-transfer loss, one pole at f_clk/4
    Cf       Xin_[bbd_tuning::kFiltOrder];
    Cf       Xout_mem_[bbd_tuning::kFiltOrder];
};

// The NE570 pair: a 2:1 compressor before the line and a 1:2 expander after
// it, both with tau = 10 ms. Its job is the BBD's 75 dB noise floor; its
// audible signature is tails pulled down harder than a linear delay would
// pull them, with the noise breathing along.
//
// The round trip is unity by construction, not by tuning. With a compressor
// envelope e and reference r:
//
//   g_c = sqrt(r / e)                     -> out level = sqrt(e * r)
//   the expander's own envelope is then sqrt(e * r)
//   g_e = sqrt(e * r) / r = sqrt(e / r)
//   g_c * g_e = 1
//
// It is NOT a parameter. It is tuned by ear and fixed: the device's
// character, not a setting of it, and "compression" is already spoken for by
// COMP on the panel.
class Compander {
public:
    void Init(float sample_rate) {
        float k = 1.f / (bbd_tuning::kCompTauS * (sample_rate > 0.f ? sample_rate : 48000.f));
        coef_ = k > 1.f ? 1.f : k;
        Reset();
    }

    void Reset() {
        env_c_ = bbd_tuning::kCompFloorC;
        env_e_ = bbd_tuning::kCompFloorE;
    }

    float Compress(float x) {
        const float a = x < 0.f ? -x : x;
        env_c_ += coef_ * (a - env_c_);
        float e = env_c_;
        if (!(e > bbd_tuning::kCompFloorC)) e = bbd_tuning::kCompFloorC;
        return x * std::sqrt(bbd_tuning::kCompRef / e);
    }

    float Expand(float x) {
        const float a = x < 0.f ? -x : x;
        env_e_ += coef_ * (a - env_e_);
        float e = env_e_;
        if (!(e > bbd_tuning::kCompFloorE)) e = bbd_tuning::kCompFloorE;
        if (e > bbd_tuning::kCompCeilE) e = bbd_tuning::kCompCeilE;
        return x * (e * (1.f / bbd_tuning::kCompRef));
    }

    // Observers for tests only: the 10 ms time constant is otherwise
    // unobservable, and "the compander breathes" is not an assertion.
    float env_comp() const { return env_c_; }
    float env_exp() const { return env_e_; }

private:
    float coef_ = 1.f;
    float env_c_ = bbd_tuning::kCompFloorC;
    float env_e_ = bbd_tuning::kCompFloorE;
};

// The chain: DRIVE -> soft saturation -> compressor -> BbdLine -> expander,
// with the feedback path re-entering BEFORE the compander so every repeat
// pays the whole chain again.
//
// Drops into EchoDelay's place with the same Process(in, ...) shape -- only
// the second argument changed meaning, from a length in samples to a clock in
// Hz, which is the entire redesign in one signature.
class BbdEcho {
public:
    BbdEcho() = default;
    BbdEcho(const BbdEcho&) = delete;
    BbdEcho& operator=(const BbdEcho&) = delete;

    void Init(float sample_rate, float* buf, size_t max_cells) {
        line_.Init(buf, max_cells, sample_rate);
        comp_.Init(sample_rate);
        feedback_ = 0.f;
        fb_state_ = 0.f;
        SetDrive(0.f);
    }

    void SetFeedback(float fb) { feedback_ = fb; }
    float Feedback() const { return feedback_; }

    // 0..1 -> kDriveLoDb .. kDriveHiDb into a FIXED-threshold saturator.
    //
    // sat_out_ is a FIXED ceiling (kSatCeil), not `kSatCeil / g`. The
    // inverse-gain makeup law that used to live here held small-signal loop
    // gain at unity across all of DRIVE -- deliberate, and there was a
    // passing test for it -- but it also meant the saturator's MAXIMUM
    // possible output (the value `fast_tanh` returns once driven anywhere
    // near its asymptote, times sat_out_) fell by exactly the dB range's own
    // width across the knob -- 30 dB at the range then in force (-6..+24,
    // 1.796 -> 0.057). The 2026-07-27 DRIVE investigation
    // (.superpowers/sdd/2026-07-27-flux-bbd-delay/drive-investigation.md)
    // measured the audible consequence: a 14.0 dB peak-level drop in the
    // actual echo return between DRIVE 0 and DRIVE 1, at the level a real
    // patch produces. THD was climbing the entire time (0.6% -> 29%) but the
    // level collapse was the easier cue to notice, so cranking DRIVE read as
    // "getting weaker," not "getting dirtier."
    //
    // The real MN3005 has a FIXED headroom ceiling: you drive harder against
    // it, and the result gets denser and louder up to that limit, not
    // quieter. No physical circuit's ceiling recedes as you push it harder.
    // A fixed sat_out_ matches that: small-signal loop gain now equals `g`
    // itself (no longer DRIVE-independent), so within THIS class FEEDBACK
    // moves closer to self-oscillation as DRIVE rises -- what the physical
    // circuit does, and the loop still cannot diverge: fast_tanh clamps hard
    // at +-1, so Process() is bounded by construction at sat_out_ = kSatCeil
    // regardless of DRIVE or FEEDBACK.
    //
    // That coupling is real but proved unplayable at the panel: measured, the
    // FEEDBACK knob producing a 15 s tail slid from 0.57 at DRIVE 0 to 0.14 at
    // DRIVE 1, so most of FEEDBACK's travel was runaway above a quarter DRIVE.
    // Flux::set_feedback therefore divides bbd_drive_gain() back out of the
    // coefficient it hands down -- see the comment there. BbdEcho itself is
    // left honest: its loop gain IS feedback * g, and test_bbd.cpp's "DRIVE
    // now raises the small-signal loop gain, monotonically" still holds it to
    // that. Anything reasoning about what a FEEDBACK knob position does at the
    // panel has to go through Flux, not this class.
    //
    // The dB range itself (kDriveLoDb, kDriveHiDb -- see their own comment)
    // was revised once already, by measurement, because the fixed ceiling
    // makes FEEDBACK's self-oscillation point track DRIVE directly: the
    // first range tried (-6..+24, inherited unexamined from the old law)
    // pushed the DRIVE-0 threshold to ~1.71, past Flux::set_feedback's own
    // 1.2 ceiling -- self-oscillation became UNREACHABLE at DRIVE 0, and at
    // DRIVE 1 the threshold fell to ~0.05, a hair-trigger. At the shipped
    // 0..+12 range: DRIVE 0 puts the loop at unity gain (g=1, no attenuation
    // or boost) with the self-oscillation threshold comfortably below the
    // 1.2 ceiling (measured ~0.84); DRIVE 1 puts it +12 dB up (g~3.98),
    // leaving FEEDBACK a real non-oscillating span before that point
    // (measured ~0.21) rather than collapsing to a switch.
    void SetDrive(float norm) {
        const float g = bbd_drive_gain(norm);   // control rate only
        sat_in_ = g * (1.f / bbd_tuning::kSatCeil);
        sat_out_ = bbd_tuning::kSatCeil;
    }

    void SetStages(int stages) { line_.SetStages(stages); }

    float Process(float in, float clock_hz) {
        line_.SetClock(clock_hz);
        const float x = in + fb_state_ * feedback_;
        // MN3005 ceiling: the loop saturates softly and then self-oscillates
        // as a thick distorted tone rather than a screech.
        const float sat = fast_tanh(x * sat_in_) * sat_out_;
        const float y = comp_.Expand(line_.Process(comp_.Compress(sat)));
        fb_state_ = y;
        return y;
    }

private:
    BbdLine   line_;
    Compander comp_;
    float feedback_ = 0.f;
    float sat_in_ = 1.f;
    float sat_out_ = 1.f;
    float fb_state_ = 0.f;
};

}  // namespace spky
