#pragma once
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include "util/math.h"

// Bucket-brigade delay: the Holters/Parker combined model of a BBD and its
// input/output filters (DAFx-18), with the NE570 compander and the drive path
// of an Electro-Harmonix Deluxe Memory Man around it.
//
// Derived from jpcima/bbd-delay-experimental (bbd_line, bbd_filter), used
// under the Boost Software License 1.0:
//
//   Boost Software License - Version 1.0 - August 17th, 2003
//
//   Permission is hereby granted, free of charge, to any person or
//   organization obtaining a copy of the software and accompanying
//   documentation covered by this license (the "Software") to use, reproduce,
//   display, distribute, execute, and transmit the Software, and to prepare
//   derivative works of the Software, and to permit third-parties to whom the
//   Software is furnished to do so, all subject to the following:
//
//   The copyright notices in the Software and this entire statement,
//   including the above license grant, this restriction and the following
//   disclaimer, must be included in all copies of the Software, in whole or
//   in part, and all derivative works of the Software, unless such copies or
//   derivative works are solely in the form of machine-executable object code
//   generated by a source language processor.
//
//   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
//   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
//   NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
//   DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,
//   WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
//   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//   SOFTWARE.
//
// Deviations from the reference, all deliberate: float instead of double, a
// local Cf instead of std::complex, injected memory instead of std::vector /
// unique_ptr, one init-time filter build instead of a mutex-guarded cache,
// our own filter chain (the DMM's ~3.6 kHz, not the Juno-60's ~7-10 kHz), and
// a charge-transfer loss pole the reference does not model at all.

namespace spky {

// Minimal complex float. std::complex<float> would do the same job, but it
// drags <complex> into every translation unit that includes this header and
// its operator* is not guaranteed to avoid the NaN-safe slow path on every
// toolchain. Six lines here, no surprises on the M7.
struct Cf {
    float re = 0.f;
    float im = 0.f;
};

inline Cf cf_add(Cf a, Cf b) { return Cf{ a.re + b.re, a.im + b.im }; }
inline Cf cf_scale(Cf a, float s) { return Cf{ a.re * s, a.im * s }; }
inline Cf cf_mul(Cf a, Cf b) {
    return Cf{ a.re * b.re - a.im * b.im, a.re * b.im + a.im * b.re };
}
inline Cf cf_div(Cf a, Cf b) {
    const float d = b.re * b.re + b.im * b.im;
    const float inv = (d != 0.f) ? 1.f / d : 0.f;
    return Cf{ (a.re * b.re + a.im * b.im) * inv,
               (a.im * b.re - a.re * b.im) * inv };
}
inline Cf cf_exp(Cf a) {
    const float m = std::exp(a.re);
    return Cf{ m * std::cos(a.im), m * std::sin(a.im) };
}

namespace bbd_tuning {

// --- the clock law ---------------------------------------------------------
// f_clk = stages / (2 * t_d), clamped. The ceiling is physical, not
// arbitrary: the fixed post-BBD filter chain sits at kFilterHz and the clock
// never overtakes it, so BBD bandwidth past kClockMaxHz/4 = 8 kHz is
// inaudible by construction. It also bounds the tick rate at
// 2 * 32000 / 48000 = 1.33 per sample, which is what makes the budget
// computable. There is deliberately NO floor.
constexpr float kClockMaxHz = 32000.f;

// --- stages ----------------------------------------------------------------
// Geometric, five octaves. 8192 is the DMM (2x MN3005 at 4096 stages each);
// the rest of the scale is a chip no pedal exposes.
constexpr int kMinStages = 512;
constexpr int kMaxStages = 16384;

// --- the fixed filter chain ------------------------------------------------
// The real device's chain is roughly six poles around 3.5-4 kHz and does NOT
// move with the clock. Modelled as two 3rd-order Butterworth sections, one
// before the line and one after: six poles, one corner, analytic residues.
// Ear-tunable (spec: the filters are the device's character, not a setting).
constexpr float kFilterHz  = 3600.f;
constexpr int   kFiltOrder = 3;

// Rows in the G interpolation table. The tick's sub-sample position d lands
// between two rows and is lerped. 65 rows over exp(p*ts*d), |p*ts| <= 0.48 at
// 48 kHz, gives a relative error below 1e-5 -- far under the model's own
// error. The table is fs-dependent only, and shared by all four lines.
constexpr int kInterpSteps = 65;

// --- charge-transfer loss --------------------------------------------------
// Bandwidth follows the clock: f_-3dB ~ f_clk / 4 over 8192 stages. One
// one-pole INSIDE the clocked domain (i.e. running at the line's own sample
// rate, f_clk) with a fixed normalised corner of 1/4 tracks the clock for
// free -- no coefficient recompute when the clock moves, and the corner is
// correct at every clock by construction.
//
// For y[n] = y[n-1] + a*(x - y[n-1]) with b = 1-a, half power at w = pi/2
// requires 1 + b^2 = 2*(1-b)^2, i.e. b = 2 - sqrt(3). So a = sqrt(3) - 1.
constexpr float kLossCoef = 0.7320508f;   // sqrt(3) - 1

// --- the NE570 compander ---------------------------------------------------
// 2:1 in, 1:2 out, tau = 10 kOhm * 1 uF. Not a parameter: it is the device's
// character, and "compression" is already spoken for by COMP on the panel.
constexpr float kCompTauS = 0.010f;
constexpr float kCompRef  = 0.1f;         // -20 dBFS reference level
// Envelope floors/ceilings that bound the compander's gain to [1/4, 4] in
// each direction. Derived, not tasted: the compressor's gain is
// sqrt(kCompRef/e), so e >= kCompRef/16 caps it at 4; the expander's gain is
// e/kCompRef, so e in [kCompRef/4, 4*kCompRef] caps it at 4 either way.
constexpr float kCompFloorC = kCompRef / 16.f;
constexpr float kCompFloorE = kCompRef / 4.f;
constexpr float kCompCeilE  = kCompRef * 4.f;

// --- drive -----------------------------------------------------------------
// DRIVE sits INSIDE the loop, so every repeat saturates again. The threshold
// is fixed at the MN3005's 0.9 V_RMS ceiling; DRIVE moves the signal against
// it, with makeup gain after the saturator so that small-signal loop gain --
// and therefore FEEDBACK's meaning -- does not move with DRIVE.
constexpr float kSatCeil   = 0.9f;
constexpr float kDriveLoDb = -6.f;
constexpr float kDriveHiDb = 24.f;

}  // namespace bbd_tuning

// The one formula. Pure, stateless, separately tested. Everything else in
// this file trusts it.
//
// A non-finite or non-positive delay returns the ceiling rather than an
// infinity: BbdLine must never see a clock it cannot count ticks from, and a
// silent, very short delay is a far better failure than a NaN in the line.
inline float bbd_clock_hz(float delay_seconds, int stages) {
    if (!(delay_seconds > 0.f) || !std::isfinite(delay_seconds))
        return bbd_tuning::kClockMaxHz;
    const float hz = static_cast<float>(stages) / (2.f * delay_seconds);
    return hz < bbd_tuning::kClockMaxHz ? hz : bbd_tuning::kClockMaxHz;
}

// Discretised filter, one per direction, shared by every BbdLine at a given
// sample rate.
//
//   P[m] = exp(ts * p_m)                          per-sample pole advance
//   G[step][m]                                    the tick's sub-sample
//     input  kind: ts * R[m] * P[m]^d               position d, tabulated
//     output kind: (R[m] / p_m) * P[m]^(1-d)        and lerped in the hot path
//   H = sum(-R[m] / p_m)                          output DC feed-through
//
// The G table is why there is no powf/cosf per event: the reference's own
// suggestion, and the desktop build profits from it too.
struct BbdFilterCoef {
    Cf    G[bbd_tuning::kInterpSteps][bbd_tuning::kFiltOrder];
    Cf    P[bbd_tuning::kFiltOrder];
    float H = 0.f;

    void interpolate_g(float d, Cf* g) const {
        float row = d * static_cast<float>(bbd_tuning::kInterpSteps - 1);
        if (!(row > 0.f)) row = 0.f;                    // also catches NaN
        int r1 = static_cast<int>(row);
        if (r1 > bbd_tuning::kInterpSteps - 1) r1 = bbd_tuning::kInterpSteps - 1;
        const int r2 = (r1 + 1 < bbd_tuning::kInterpSteps) ? r1 + 1 : r1;
        const float mu = row - static_cast<float>(r1);
        for (int m = 0; m < bbd_tuning::kFiltOrder; ++m) {
            g[m].re = G[r1][m].re + (G[r2][m].re - G[r1][m].re) * mu;
            g[m].im = G[r1][m].im + (G[r2][m].im - G[r1][m].im) * mu;
        }
    }
};

// The analog specification: kFiltOrder Butterworth poles at kFilterHz and
// their partial-fraction residues for H(s) = prod(-p_j) / prod(s - p_j).
// Both directions currently share the same prototype; the flag is kept
// because the DISCRETISATION differs (see BbdFilterCoef) and because giving
// the two chains different corners later must not need a signature change.
void bbd_analog_spec(bool output_kind, Cf* poles, Cf* residues);

// Shared, built on first call and rebuilt in place if the sample rate moves.
// Not thread-safe by design: both hosts call Flux::init from one thread with
// the audio callback stopped (Rack's onSampleRateChange, the render host's
// setup), which is the same contract hann_curve() in fx/fx_util.h already
// relies on.
const BbdFilterCoef& bbd_filter_in(float sample_rate);
const BbdFilterCoef& bbd_filter_out(float sample_rate);

// An N-cell bucket-brigade line over injected memory, driven by a clock
// frequency. It has NO read pointer: all charge packets are clocked forward
// together, and the delay is a consequence of the clock, not of an index.
//
// Even ticks WRITE one cell, odd ticks READ one cell -- that alternation is
// the two-phase clock of the physical part, and it is why the cell count is
// half the stage count and why the tick rate is twice f_clk:
//
//     ticks/sample = 2 * f_clk / fs
//     cells        = stages / 2
//     delay        = 2 * cells / tick_rate = stages / (2 * f_clk)
//
// It knows nothing about music -- no BPM, no divisions, no feedback.
class BbdLine {
public:
    BbdLine() = default;
    BbdLine(const BbdLine&) = delete;
    BbdLine& operator=(const BbdLine&) = delete;

    // `buf` holds max_cells floats and is owned by the host (FxMem).
    void Init(float* buf, size_t max_cells, float sample_rate) {
        mem_ = buf;
        max_cells_ = max_cells;
        sr_ = (sample_rate > 0.f) ? sample_rate : 48000.f;
        fin_ = &bbd_filter_in(sr_);
        fout_ = &bbd_filter_out(sr_);
        cells_ = static_cast<int>(max_cells_ > 0 ? max_cells_ : 1);
        Reset();
    }

    void Reset() {
        if (mem_ && max_cells_) std::memset(mem_, 0, max_cells_ * sizeof(float));
        imem_ = 0;
        pclk_ = 0.f;
        ptick_ = 0;
        ybbd_old_ = 0.f;
        loss_z_ = 0.f;
        for (int m = 0; m < bbd_tuning::kFiltOrder; ++m) {
            Xin_[m] = Cf{};
            Xout_mem_[m] = Cf{};
        }
    }

    // The BBD clock in Hz. Non-finite or non-positive means "hold": no ticks,
    // no division by the clock, the output filter simply coasts.
    void SetClock(float hz) {
        ticks_ = (hz > 0.f && std::isfinite(hz)) ? (2.f * hz / sr_) : 0.f;
    }

    // Physical stage count. The cell array is half of it; content is
    // deliberately NOT cleared, so a stage change drifts in time and pitch
    // instead of clicking.
    void SetStages(int stages) {
        int c = stages / 2;
        const int lo = bbd_tuning::kMinStages / 2;
        const int hi = static_cast<int>(max_cells_);
        if (c < lo) c = lo;
        if (c > hi) c = hi;
        if (c < 1) c = 1;
        if (c == cells_) return;
        cells_ = c;
        if (imem_ >= cells_) imem_ = 0;
    }

    int cells() const { return cells_; }

    float Process(float in) {
        Cf Xout[bbd_tuning::kFiltOrder] = {};

        const float fclk = ticks_;
        // mem_ can be null with cells_ still nonzero -- Init(nullptr, 0, sr)
        // leaves cells_ at 1 (its floor), and SetStages's own floor does the
        // same. No tick may run while the line has no usable memory.
        if (fclk > 0.f && mem_) {
            const float pclk_old = pclk_;
            const float p = pclk_ + fclk;
            const int tick_count = static_cast<int>(p);
            pclk_ = p - static_cast<float>(tick_count);
            const float inv = 1.f / fclk;
            Cf g[bbd_tuning::kFiltOrder];
            for (int t = 0; t < tick_count; ++t) {
                // The tick's position inside this audio sample, in [0, 1).
                float d = (1.f - pclk_old + static_cast<float>(t)) * inv;
                d -= static_cast<float>(static_cast<int>(d));
                if ((ptick_ & 1u) == 0u) {
                    // WRITE phase: sample the input filter at d and push one
                    // charge packet, after the charge-transfer loss.
                    fin_->interpolate_g(d, g);
                    float s = 0.f;
                    for (int m = 0; m < bbd_tuning::kFiltOrder; ++m)
                        s += g[m].re * Xin_[m].re - g[m].im * Xin_[m].im;
                    loss_z_ += bbd_tuning::kLossCoef * (s - loss_z_);
                    mem_[imem_] = loss_z_;
                    imem_ = (imem_ + 1 < cells_) ? imem_ + 1 : 0;
                } else {
                    // READ phase: imem_ points at the oldest cell. The output
                    // filter is driven by the STEP between consecutive
                    // readings, which is what makes the staircase exact.
                    fout_->interpolate_g(d, g);
                    const float ybbd = mem_[imem_];
                    const float delta = ybbd - ybbd_old_;
                    ybbd_old_ = ybbd;
                    for (int m = 0; m < bbd_tuning::kFiltOrder; ++m)
                        Xout[m] = cf_add(Xout[m], cf_scale(g[m], delta));
                }
                ++ptick_;
            }
        }

        // Input filter states advance by exactly one audio sample, always --
        // whether or not a tick happened. This is the continuous-time part of
        // the model and it must not be inside the tick loop.
        for (int m = 0; m < bbd_tuning::kFiltOrder; ++m) {
            const Cf p = fin_->P[m];
            const Cf x = Xin_[m];
            Xin_[m] = Cf{ x.re * p.re - x.im * p.im + in,
                          x.re * p.im + x.im * p.re };
        }

        float y = fout_->H * ybbd_old_;
        for (int m = 0; m < bbd_tuning::kFiltOrder; ++m) {
            const Cf x = cf_add(cf_mul(fout_->P[m], Xout_mem_[m]), Xout[m]);
            Xout_mem_[m] = x;
            y += x.re;
        }
        return y;
    }

private:
    const BbdFilterCoef* fin_ = nullptr;
    const BbdFilterCoef* fout_ = nullptr;
    float*   mem_ = nullptr;
    size_t   max_cells_ = 0;
    int      cells_ = 1;
    int      imem_ = 0;
    float    sr_ = 48000.f;
    float    ticks_ = 0.f;      // ticks per audio sample = 2*f_clk/fs
    float    pclk_ = 0.f;       // fractional tick phase carried between samples
    uint32_t ptick_ = 0;        // parity picks write vs read
    float    ybbd_old_ = 0.f;
    float    loss_z_ = 0.f;     // charge-transfer loss, one pole at f_clk/4
    Cf       Xin_[bbd_tuning::kFiltOrder];
    Cf       Xout_mem_[bbd_tuning::kFiltOrder];
};

}  // namespace spky
