#pragma once
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include "util/math.h"

// Bucket-brigade delay: the Holters/Parker combined model of a BBD and its
// input/output filters (DAFx-18), with the NE570 compander and the drive path
// of an Electro-Harmonix Deluxe Memory Man around it.
//
// Derived from jpcima/bbd-delay-experimental (bbd_line, bbd_filter), used
// under the Boost Software License 1.0:
//
//   Boost Software License - Version 1.0 - August 17th, 2003
//
//   Permission is hereby granted, free of charge, to any person or
//   organization obtaining a copy of the software and accompanying
//   documentation covered by this license (the "Software") to use, reproduce,
//   display, distribute, execute, and transmit the Software, and to prepare
//   derivative works of the Software, and to permit third-parties to whom the
//   Software is furnished to do so, all subject to the following:
//
//   The copyright notices in the Software and this entire statement,
//   including the above license grant, this restriction and the following
//   disclaimer, must be included in all copies of the Software, in whole or
//   in part, and all derivative works of the Software, unless such copies or
//   derivative works are solely in the form of machine-executable object code
//   generated by a source language processor.
//
//   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
//   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
//   NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
//   DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,
//   WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
//   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//   SOFTWARE.
//
// Deviations from the reference, all deliberate: float instead of double, a
// local Cf instead of std::complex, injected memory instead of std::vector /
// unique_ptr, one init-time filter build instead of a mutex-guarded cache,
// our own filter chain (the DMM's ~3.6 kHz, not the Juno-60's ~7-10 kHz), and
// a charge-transfer loss pole the reference does not model at all.

namespace spky {

namespace bbd_tuning {

// --- the clock law ---------------------------------------------------------
// f_clk = stages / (2 * t_d), clamped. The ceiling is physical, not
// arbitrary: the fixed post-BBD filter chain sits at kFilterHz and the clock
// never overtakes it, so BBD bandwidth past kClockMaxHz/4 = 8 kHz is
// inaudible by construction. It also bounds the tick rate at
// 2 * 32000 / 48000 = 1.33 per sample, which is what makes the budget
// computable. There is deliberately NO floor.
constexpr float kClockMaxHz = 32000.f;

// --- stages ----------------------------------------------------------------
// Geometric, five octaves. 8192 is the DMM (2x MN3005 at 4096 stages each);
// the rest of the scale is a chip no pedal exposes.
constexpr int kMinStages = 512;
constexpr int kMaxStages = 16384;

// --- the fixed filter chain ------------------------------------------------
// The real device's chain is roughly six poles around 3.5-4 kHz and does NOT
// move with the clock. Modelled as two 3rd-order Butterworth sections, one
// before the line and one after: six poles, one corner, analytic residues.
// Ear-tunable (spec: the filters are the device's character, not a setting).
constexpr float kFilterHz  = 3600.f;
constexpr int   kFiltOrder = 3;

// Rows in the G interpolation table. The tick's sub-sample position d lands
// between two rows and is lerped. 65 rows over exp(p*ts*d), |p*ts| <= 0.48 at
// 48 kHz, gives a relative error below 1e-5 -- far under the model's own
// error. The table is fs-dependent only, and shared by all four lines.
constexpr int kInterpSteps = 65;

// --- charge-transfer loss --------------------------------------------------
// Bandwidth follows the clock: f_-3dB ~ f_clk / 4 over 8192 stages. One
// one-pole INSIDE the clocked domain (i.e. running at the line's own sample
// rate, f_clk) with a fixed normalised corner of 1/4 tracks the clock for
// free -- no coefficient recompute when the clock moves, and the corner is
// correct at every clock by construction.
//
// For y[n] = y[n-1] + a*(x - y[n-1]) with b = 1-a, half power at w = pi/2
// requires 1 + b^2 = 2*(1-b)^2, i.e. b = 2 - sqrt(3). So a = sqrt(3) - 1.
constexpr float kLossCoef = 0.7320508f;   // sqrt(3) - 1

// --- the NE570 compander ---------------------------------------------------
// 2:1 in, 1:2 out, tau = 10 kOhm * 1 uF. Not a parameter: it is the device's
// character, and "compression" is already spoken for by COMP on the panel.
constexpr float kCompTauS = 0.010f;
constexpr float kCompRef  = 0.1f;         // -20 dBFS reference level
// Envelope floors/ceilings that bound the compander's gain to [1/4, 4] in
// each direction. Derived, not tasted: the compressor's gain is
// sqrt(kCompRef/e), so e >= kCompRef/16 caps it at 4; the expander's gain is
// e/kCompRef, so e in [kCompRef/4, 4*kCompRef] caps it at 4 either way.
constexpr float kCompFloorC = kCompRef / 16.f;
constexpr float kCompFloorE = kCompRef / 4.f;
constexpr float kCompCeilE  = kCompRef * 4.f;

// --- drive -----------------------------------------------------------------
// DRIVE sits INSIDE the loop, so every repeat saturates again. The threshold
// is fixed at the MN3005's 0.9 V_RMS ceiling; DRIVE moves the signal against
// it, with makeup gain after the saturator so that small-signal loop gain --
// and therefore FEEDBACK's meaning -- does not move with DRIVE.
constexpr float kSatCeil   = 0.9f;
constexpr float kDriveLoDb = -6.f;
constexpr float kDriveHiDb = 24.f;

}  // namespace bbd_tuning

// The one formula. Pure, stateless, separately tested. Everything else in
// this file trusts it.
//
// A non-finite or non-positive delay returns the ceiling rather than an
// infinity: BbdLine must never see a clock it cannot count ticks from, and a
// silent, very short delay is a far better failure than a NaN in the line.
inline float bbd_clock_hz(float delay_seconds, int stages) {
    if (!(delay_seconds > 0.f) || !std::isfinite(delay_seconds))
        return bbd_tuning::kClockMaxHz;
    const float hz = static_cast<float>(stages) / (2.f * delay_seconds);
    return hz < bbd_tuning::kClockMaxHz ? hz : bbd_tuning::kClockMaxHz;
}

}  // namespace spky
