#!/usr/bin/env python3
"""Bake the fixed, curated wavetable bank used by the WAVE oscillator."""

import argparse
import hashlib
import math
from pathlib import Path


MIP_LENGTHS = (1024, 512, 256, 128, 64, 32, 16)
GUARD_DIVISOR = 4
RECIPES = [
    [(1, 1.00, 0.00)],
    [(1, 1.00, 0.00), (2, 0.16, 0.13), (3, 0.28, 0.37), (5, 0.10, 0.61)],
    [(1, 0.90, 0.00), (3, 0.38, 0.23), (6, 0.23, 0.47), (9, 0.15, 0.71)],
    [(1, 0.82, 0.00), (2, 0.22, 0.17), (5, 0.36, 0.41), (8, 0.20, 0.67), (13, 0.11, 0.83)],
    "formant_ah",
    "formant_oh",
    "formant_uh",
    "formant_eh",
    "odd_hollow",
    "comb_3",
    "fifth_heavy",
    "resonant_7",
    "soft_saw",
    "hard_saw",
    "spectral_junk",
    "bit_organ",
]


def formants(*bands):
    partials = []
    for h in range(1, 128):
        weight = sum(
            gain * math.exp(-0.5 * ((h - center) / width) ** 2)
            for center, width, gain in bands
        )
        partials.append((h, weight / h, (h * 0.097) % 1.0))
    return partials


def symbolic_recipe(name):
    if name == "formant_ah":
        return formants((4.0, 1.5, 1.00), (10.0, 2.2, 0.62), (18.0, 3.0, 0.28))
    if name == "formant_oh":
        return formants((3.0, 1.3, 1.00), (7.0, 1.8, 0.70), (15.0, 2.8, 0.24))
    if name == "formant_uh":
        return formants((2.5, 1.2, 1.00), (6.0, 1.7, 0.56), (12.0, 2.5, 0.20))
    if name == "formant_eh":
        return formants((5.0, 1.5, 1.00), (12.0, 2.1, 0.72), (20.0, 3.2, 0.25))
    if name == "odd_hollow":
        return [(h, 1.0 / h, (h * 0.173) % 1.0) for h in range(1, 48, 2)]
    if name == "comb_3":
        return [(h, 0.8 / h, (h * 0.119) % 1.0) for h in range(1, 64) if h % 3 != 0]
    if name == "fifth_heavy":
        return [(h, (1.0 if h % 3 == 0 else 0.28) / h, (h * 0.071) % 1.0) for h in range(1, 64)]
    if name == "resonant_7":
        return [(h, (1.0 + 2.4 * math.exp(-0.5 * ((h - 7.0) / 1.3) ** 2)) / h,
                 (h * 0.137) % 1.0) for h in range(1, 64)]
    if name == "soft_saw":
        return [(h, 1.0 / (h ** 1.35), 0.0) for h in range(1, 128)]
    if name == "hard_saw":
        return [(h, 1.0 / h, 0.0) for h in range(1, 256)]
    if name == "spectral_junk":
        return [(h, (0.35 + ((h * 37) % 19) / 19.0) / math.sqrt(h),
                 ((h * 73) % 101) / 101.0) for h in range(1, 128) if h % 5 != 0]
    if name == "bit_organ":
        return [(h, 1.0 / math.sqrt(h), 0.25 if h % 4 == 0 else 0.0)
                for h in (1, 2, 4, 8, 16, 32, 48, 64, 96)]
    raise ValueError(name)


def expand_recipe(recipe):
    return symbolic_recipe(recipe) if isinstance(recipe, str) else recipe


def bake_mip(recipe, length):
    partials = [partial for partial in recipe if partial[0] <= length // GUARD_DIVISOR]
    samples = []
    for index in range(length):
        phase = index / length
        samples.append(sum(
            amplitude * math.sin(2.0 * math.pi * (harmonic * phase + offset))
            for harmonic, amplitude, offset in partials
        ))

    mean = sum(samples) / length
    centered = [sample - mean for sample in samples]
    peak = max(abs(sample) for sample in centered)
    return [round(sample * 0.98 / peak * 32767) for sample in centered]


def bake_bank():
    bank = []
    for recipe in RECIPES:
        expanded = expand_recipe(recipe)
        for length in MIP_LENGTHS:
            bank.extend(bake_mip(expanded, length))
    return bank


def render_cpp():
    samples = bake_bank()
    assert len(samples) == 32512
    digest = hashlib.sha256(",".join(str(sample) for sample in samples).encode("ascii")).hexdigest()
    lines = [
        "// Generated by tools/bake_wavetables.py; do not edit.",
        "// Sample SHA-256: " + digest,
        "#include \"synth/wt_bank.h\"",
        "",
        "#if defined(__ARM_EABI__)",
        "#define WT_BANK_QSPI __attribute__((section(\".qspiflash_data\")))",
        "#else",
        "#define WT_BANK_QSPI",
        "#endif",
        "",
        "namespace spky::wt {",
        "",
        "const int kMipLength[kMipCount] = {1024, 512, 256, 128, 64, 32, 16};",
        "const int kMipOffset[kMipCount] = {0, 1024, 1536, 1792, 1920, 1984, 2016};",
        "const int16_t kBankSamples[kTotalSamples] WT_BANK_QSPI = {",
    ]
    for index in range(0, len(samples), 16):
        lines.append("    " + ", ".join(str(sample) for sample in samples[index:index + 16]) + ",")
    lines.extend(["};", "", "} // namespace spky::wt", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed bank is stale")
    args = parser.parse_args()
    output_path = Path(__file__).resolve().parents[1] / "engine" / "synth" / "wt_bank.cpp"
    generated = render_cpp()

    if args.check:
        if not output_path.exists() or output_path.read_text(encoding="utf-8") != generated:
            return 1
        return 0

    output_path.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
