#!/usr/bin/env python3
"""Rev A schematic: blocks -> project.

The check tool loads this file:
    python hardware/gen/check.py --project hardware/reva/build.py --fast|--sheet NAME|--full
`python hardware/reva/build.py` writes the committed files under kicad/.
Saving the project from the KiCad GUI rewrites kicad/reva.kicad_pro;
reva_build_guard then reports it stale -- rerun build.py.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HW = os.path.normpath(os.path.join(HERE, ".."))
for p in (HW, HERE):
    if p not in sys.path:
        sys.path.insert(0, p)

import assign                      # noqa: E402
import blocks                      # noqa: E402
import parts                       # noqa: E402
import review                      # noqa: E402
from gen import bom as B           # noqa: E402
from gen.project import Project    # noqa: E402

PANEL_MAP = os.path.join(HERE, "panel-map.json")
WAIVERS = os.path.join(HERE, "erc-waivers.txt")
THONK_DIR = os.path.join(HW, "lib", "Thonk")
FIREFLOW_DIR = os.path.join(HW, "lib", "FireFlow")
COVERED = {"jack", "key", "led", "sd", "pot"}


def load_panel_map():
    with open(PANEL_MAP, encoding="utf-8") as fh:
        return json.load(fh)


def project():
    pm = load_panel_map()
    holes = [h for h in assign.load_holes() if h["kind"] in COVERED]
    refs = blocks.Refs()
    sheets = [blocks.power(refs), blocks.module(refs)]
    sheets += [blocks.mux_region(refs, pm, s) for s in pm["sense_order"]]
    sheets += [blocks.chains(refs), blocks.leds(refs, pm["leds"]),
               blocks.jacks(refs, [h for h in holes if h["kind"] == "jack"]),
               blocks.sd(refs)]
    return Project("reva", "FireFlow Rev A", sheets, power=blocks.POWER,
                   domain_rails=blocks.DOMAINS, holes=holes, waivers=WAIVERS,
                   paper="A3", lib_dirs={"Thonk": THONK_DIR, "FireFlow": FIREFLOW_DIR},
                   comments=["GENERATED by hardware/reva/build.py -- do not edit",
                             "Spec: docs/superpowers/specs/2026-09-29-rev-a-p3-schematic-design.md"])


from gen import check as C          # noqa: E402
from gen import sch_writer as W     # noqa: E402

KICAD = "kicad"
# In the committed tables vendored libraries resolve relative to the
# project, so nothing machine-specific reaches the repository.
LIB_URIS = {"Daisy-Boards": "${KIPRJMOD}/../../lib/DaisyKiCad",
            "Thonk": "${KIPRJMOD}/../../lib/Thonk",
            "FireFlow": "${KIPRJMOD}/../../lib/FireFlow"}


def write_all(root=HERE):
    """Write every generated Rev A file under `root`; return their paths
    relative to `root`, sorted. The guard writes to a temp dir and compares."""
    proj = project()
    kdir = os.path.join(root, KICAD)
    os.makedirs(kdir, exist_ok=True)
    for name in os.listdir(kdir):                # a renamed sheet must not linger
        if name.endswith(".kicad_sch"):
            os.remove(os.path.join(kdir, name))
    sheets = W.write_project(proj, kdir)         # {sheet name: (placed, height)}
    C.write_lib_tables(proj.parts(), kdir, LIB_URIS, extra_sym_libs={"power"})
    C.write_project_file(kdir, proj.name)
    # What was written, not a directory listing: opening the project in KiCad
    # leaves by-products (.kicad_prl, backups, caches) that are not ours.
    names = ([proj.name + ".kicad_sch"] + [n + ".kicad_sch" for n in sheets]
             + ["sym-lib-table", "fp-lib-table", proj.name + ".kicad_pro"])
    written = ["%s/%s" % (KICAD, n) for n in names]
    # The BOMs and the review sheet sit next to build.py, not under kicad/.
    files = {"bom-jlc.csv": B.to_csv(B.jlc_rows(proj.parts()), B.JLC_FIELDS),
             "bom-hand.csv": B.to_csv(B.hand_rows(proj.parts()), B.HAND_FIELDS),
             "review.md": review.review_md(proj, load_panel_map(),
                                           C.load_waivers(WAIVERS), parts.CATALOGUE)}
    for name, text in files.items():
        with open(os.path.join(root, name), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
    return sorted(written + list(files))


def main():
    for path in write_all():
        print("wrote hardware/reva/" + path)


if __name__ == "__main__":
    main()
