#!/usr/bin/env python3
"""Rev A schematic: blocks -> project.

The check tool loads this file:
    python hardware/gen/check.py --project hardware/reva/build.py --fast|--sheet NAME|--full
Task 4 of plan 2 adds main(), which writes the committed files.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HW = os.path.normpath(os.path.join(HERE, ".."))
for p in (HW, HERE):
    if p not in sys.path:
        sys.path.insert(0, p)

import assign                      # noqa: E402
import blocks                      # noqa: E402
from gen.project import Project    # noqa: E402

PANEL_MAP = os.path.join(HERE, "panel-map.json")
WAIVERS = os.path.join(HERE, "erc-waivers.txt")
THONK_DIR = os.path.join(HW, "lib", "Thonk")
COVERED = {"jack", "key", "led", "sd", "pot"}


def load_panel_map():
    with open(PANEL_MAP, encoding="utf-8") as fh:
        return json.load(fh)


def project():
    pm = load_panel_map()
    holes = [h for h in assign.load_holes() if h["kind"] in COVERED]
    refs = blocks.Refs()
    sheets = [blocks.power(refs), blocks.module(refs)]
    sheets += [blocks.mux_region(refs, pm, s) for s in pm["sense_order"]]
    sheets += [blocks.chains(refs), blocks.leds(refs, pm["leds"]),
               blocks.jacks(refs, [h for h in holes if h["kind"] == "jack"]),
               blocks.sd(refs)]
    return Project("reva", "FireFlow Rev A", sheets, power=blocks.POWER,
                   domain_rails=blocks.DOMAINS, holes=holes, waivers=WAIVERS,
                   paper="A3", lib_dirs={"Thonk": THONK_DIR},
                   comments=["GENERATED by hardware/reva/build.py -- do not edit",
                             "Spec: docs/superpowers/specs/2026-09-29-rev-a-p3-schematic-design.md"])
