#!/usr/bin/env python3
"""The Rev A review sheet (P3 spec §7 stage 5), generated -- never edited.

It summarises what a reviewer checks before the layout starts: the sheets,
what JLC fits (and which Extended types it charges a loading fee for), what
is hand-soldered, the pot scan regions, every ERC waiver with its reason, and
the open items. The drawing itself is the PDF from the check tool.
"""
import math
import os
import sys

_HW = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
if _HW not in sys.path:
    sys.path.insert(0, _HW)

from gen import bom as B            # noqa: E402
from gen import netlist as N        # noqa: E402

OPEN_ITEMS = (
    "SD socket footprint is open (`P4`); J_SD's part and LCSC number come with it.",
    "P2's pin table calls C1 'CV out 1' and C10 'CV out 2'; the Patch SM datasheet "
    "names C1 CV_OUT_2 and C10 CV_OUT_1. The wiring (C1 = PITCH_A, C10 = PITCH_B) "
    "follows P2 by pin; P6's firmware table must follow the pins, not the names.",
    "AMS1117-3.3 output: 22 µF X5R MLCC (C45783). Stability with a low-ESR output "
    "capacitor is a bring-up check (P7), with the regulator's temperature at full LED load.",
    "SD card on SM_3V3 (A10): pot-scan noise while the card streams is a bring-up check.",
    "The key symbol (Switch:SW_Push_DPDT) draws pin 1 as the rest contact; Thonk's "
    "button closes 1-2 when pushed. The netlist is right at the pads (pin 2 common, "
    "pin 1 to the key net); read the printed keys as normally open.",
    "J_PWR pins 7/8 are left open, as on the coupon; the Doepfer A-100 bus has GND on "
    "3-8 -- confirm against the actual bus board (carried from the coupon's TO CONFIRM).",
    "COM pads C_SENSE0-3 are fitted unpopulated (P2 §3).",
    "JLC stock is checked at the schematic freeze (13 Nov) and again before the order.",
)


def _worst(rows):
    cx = sum(r["x_mm"] for r in rows) / len(rows)
    cy = sum(r["y_mm"] for r in rows) / len(rows)
    return max(math.hypot(r["x_mm"] - cx, r["y_mm"] - cy) for r in rows)


def review_md(project, panel_map, waivers, catalogue):
    parts = project.parts()
    real = [p for p in parts if not N.is_virtual(p.ref)]
    nets = {n for p in real for n in p.nets.values()}
    out = ["# FireFlow Rev A -- schematic review", "",
           "Generated by `hardware/reva/build.py`; do not edit. The drawing: "
           "`python hardware/gen/check.py --project hardware/reva/build.py --full` "
           "writes `hardware/reva/out/reva.pdf` and one PNG per sheet.", "",
           # The second figure is every part including the PWR_FLAGs (the
           # number the check tool and the spec quote).
           "%d parts (%d with power flags), %d nets, %d sheets under an overview." % (
               len(real), len(parts), len(nets), len(project.sheets)), "",
           "## Sheets", "", "| Sheet | Title | Parts |", "|---|---|---|"]
    for s in project.sheets:
        out.append("| %s | %s | %d |" % (s.name, s.title,
                                        len([p for p in s.parts if not N.is_virtual(p.ref)])))
    jlc = B.jlc_rows(parts)
    types = {t.lcsc: t for t in catalogue.values() if t.lcsc}
    extended = sorted({r["LCSC"] for r in jlc if types[r["LCSC"]].jlc_type == "Extended"})
    out += ["", "## JLC assembly", "",
            "%d lines, %d parts. Extended types (one loading fee each, price read on "
            "the JLC page on the day): %s." % (
                len(jlc), sum(len(r["Designator"].split(",")) for r in jlc),
                ", ".join("%s (%s)" % (l, types[l].note) for l in extended) or "none"),
            "", "| LCSC | Type | Value | Qty |", "|---|---|---|---|"]
    for r in jlc:
        out.append("| %s | %s | %s | %d |" % (r["LCSC"], types[r["LCSC"]].jlc_type,
                                              r["Comment"], len(r["Designator"].split(","))))
    out += ["", "## Hand-soldered", "", "| Source | Part | Qty |", "|---|---|---|"]
    for r in B.hand_rows(parts):
        out.append("| %s | %s | %d |" % (r["Source"], r["Part"], r["Qty"]))
    out += ["", "## Pot scan", "", "| Sense pin | Muxes | Pots | Farthest pot from its "
            "mux group's centre |", "|---|---|---|---|"]
    for sense in panel_map["sense_order"]:
        rows = [p for p in panel_map["pots"] if p["sense"] == sense]
        worst = max(_worst([r for r in rows if r["mux"] == m])
                    for m in panel_map["muxes"][sense] if any(r["mux"] == m for r in rows))
        out.append("| %s | %s | %d | %.1f mm |" % (
            sense, ", ".join("U_MUX%d" % m for m in panel_map["muxes"][sense]),
            len(rows), worst))
    out += ["", "## ERC waivers", ""]
    out += (["| Type | Item | Count | Reason |", "|---|---|---|---|"]
            + ["| %s | `%s` | %d | %s |" % w for w in waivers]) if waivers else ["None."]
    out += ["", "## Open items", ""] + ["- " + item for item in OPEN_ITEMS]
    return "\n".join(out) + "\n"
