#!/usr/bin/env python3
"""The committed Rev A files are exactly what build.py writes today.

Byte for byte, except git's own autocrlf (a Windows checkout turns LF into
CRLF). A stale schematic, BOM or review sheet goes red here; the check tool's
full level (ctest reva_check_guard) proves the schematic itself.

    python hardware/reva/test_build.py
"""
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
import build  # noqa: E402


def read(path):
    with open(path, encoding="utf-8", newline="") as fh:
        return fh.read().replace("\r\n", "\n")


TOP_LEVEL = ("bom-jlc.csv", "bom-hand.csv", "review.md")
# The one tracked file under kicad/ that build.py does not write: the routed
# board is generated by route.py (P4-2), guarded by reva_route_guard
# (test_route.py: fresh run == committed board). Exempt from the orphan check
# by exactly this name, nothing broader.
ROUTED_BOARD = "%s/reva.kicad_pcb" % build.KICAD


def lib_table_failures(kdir):
    """Every ${KIPRJMOD} uri in the committed lib tables must resolve to a
    vendored .kicad_sym file or .pretty directory; KiCad's own rows are not
    ours to check. A guard that finds no ${KIPRJMOD} row examined nothing."""
    failures = []
    found = 0
    for table in ("sym-lib-table", "fp-lib-table"):
        path = os.path.join(kdir, table)
        if not os.path.exists(path):
            continue
        for uri in re.findall(r'\(uri "([^"]*)"\)', read(path)):
            if not uri.startswith("${KIPRJMOD}"):
                continue
            found += 1
            target = os.path.normpath(kdir + uri[len("${KIPRJMOD}"):])
            ok = (os.path.isfile(target) and target.endswith(".kicad_sym")) \
                or (os.path.isdir(target) and target.endswith(".pretty"))
            if not ok:
                failures.append("%s: %s does not resolve to a .kicad_sym or .pretty (%s)"
                                % (table, uri, target))
    if not found:
        failures.append("no ${KIPRJMOD} row in the committed lib tables -- "
                        "the lib-path guard examined nothing")
    return failures


def rules_file_failures(kdir):
    """The committed reva.kicad_pro carries the board rules from rules.py
    (P4-2 spec §4.1): the values below are this guard's own, not re-read from
    rules.py."""
    import json
    path = os.path.join(kdir, "reva.kicad_pro")
    try:
        pro = json.load(open(path, encoding="utf-8"))
        r = pro["board"]["design_settings"]["rules"]
    except (OSError, ValueError, KeyError) as exc:
        return ["reva.kicad_pro carries no board rules: %s" % exc]
    want = {"min_track_width": 0.25, "min_via_diameter": 0.6, "min_through_hole_diameter": 0.3,
            "min_clearance": 0.2, "min_copper_edge_clearance": 0.5}
    return ["reva.kicad_pro rule %s is %r, not %r" % (k, r.get(k), v)
            for k, v in sorted(want.items()) if r.get(k) != v]


def main():
    failures = []
    # What git tracks: the kicad/ tree and the three top-level outputs.
    # Untracked, ignored KiCad by-products (.kicad_prl, backups, caches) are
    # never orphans, and a generated file that exists but was never `git add`ed
    # is "not committed" -- it would be missing from a fresh clone.
    try:
        out = subprocess.run(
            ["git", "ls-files", "--", "hardware/reva/" + build.KICAD]
            + ["hardware/reva/" + t for t in TOP_LEVEL],
            cwd=REPO, capture_output=True, text=True, check=True).stdout
        tracked = {line.strip()[len("hardware/reva/"):]
                   for line in out.splitlines() if line.strip()}
    except (OSError, subprocess.CalledProcessError) as exc:
        failures.append("git ls-files failed: %s" % exc)
        tracked = set()
    with tempfile.TemporaryDirectory() as tmp:
        written = build.write_all(tmp)
        if len(written) < 17:
            failures.append("build.write_all wrote only %d files" % len(written))
        for rel in written:
            committed = os.path.join(HERE, rel)
            if rel not in tracked:
                failures.append("%s is not committed -- run python hardware/reva/build.py "
                                "and git add it" % rel)
            elif not os.path.exists(committed):
                failures.append("%s is tracked but missing from the work tree" % rel)
            elif read(committed) != read(os.path.join(tmp, rel)):
                failures.append("%s is stale -- run python hardware/reva/build.py" % rel)
        # Two generators must not own one file: the routed board belongs to
        # route.py, so build.py writing it would be a second owner.
        if ROUTED_BOARD in written:
            failures.append("build.write_all writes %s, which route.py owns" % ROUTED_BOARD)
        # Orphans: tracked under kicad/ but no longer written by build.py.
        failures += ["%s is committed but no longer generated" % e
                     for e in sorted(tracked - set(written) - {ROUTED_BOARD})]
    failures += lib_table_failures(os.path.join(HERE, build.KICAD))
    failures += rules_file_failures(os.path.join(HERE, build.KICAD))
    if failures:
        for f in failures:
            print("FAIL " + f)
        return 1
    print("ok: %d generated Rev A files match the committed ones" % len(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
